//=============================================================================
//
//	NTradeClientProcessDefines.h
//
//	Copyright 2007 HQGame
//
//=============================================================================
#ifndef _NSELLEDLOGCLIENTPROCESSDEFINES_H_
#define _NSELLEDLOGCLIENTPROCESSDEFINES_H_

#define MAX_SELLEDLOGCLIENT_PACKET_SIZE		5000
#define MAX_SELLEDLOGCLIENT_PACKET_COUNT	1000

#define MAX_SELLEDLOGCLIENT_CHANNEL		1

#define MAX_SELLEDLOG_CONNECTING_TIME	20 * 1000	// 20√ 

enum
{
	SELLEDLOGCLIENTPROCESS_STATE_IDLE,
	SELLEDLOGCLIENTPROCESS_STATE_REQUESTCONNECTING,
	SELLEDLOGCLIENTPROCESS_STATE_CONNECTING,
	SELLEDLOGCLIENTPROCESS_STATE_ESTABLISH,
	SELLEDLOGCLIENTPROCESS_STATE_WAITLOG,
	SELLEDLOGCLIENTPROCESS_STATE_FINISHLOG,
	SELLEDLOGCLIENTPROCESS_STATE_WRONGID,
	SELLEDLOGCLIENTPROCESS_STATE_WRONGPASS,
	SELLEDLOGCLIENTPROCESS_STATE_DONOTINPUTID,
};

#endif
