#ifndef _GAMEDBPROCESS_H
#define _GAMEDBPROCESS_H

#define DBCONNECTION_NUMBER		5

#define DBSELECT_BASE			0
#define DBSELECT_LOGIN			1
#define DBSELECT_SUB			2
#define DBSELECT_LETTER			3	// 쪽지, 제자조회등 단순 조회 요청에 대해서. 
#define DBSELECT_SYSTEM			4
//#define DBSELECT_CASH			5   // cash

#include "ITZSessionFactory.h"
#include "ITZSessionManager.h"
#include "ITZNetIOCP.h"
#include "ITZPerson.h"

enum LOGCOMMAND_TYPE
{
	LOGCOMMAND_TYPE_LOGIN			= 1,
	LOGCOMMAND_TYPE_CHARACTOR,			// 02
	LOGCOMMAND_TYPE_QUEST,				// 03	
	LOGCOMMAND_TYPE_RECOMMENDER,		// 04
	LOGCOMMAND_TYPE_FATHER,				// 05
	LOGCOMMAND_TYPE_STOCK,				// 06
	LOGCOMMAND_TYPE_SUMMON,				// 07
	LOGCOMMAND_TYPE_CITYHALL,			// 08
	LOGCOMMAND_TYPE_BANK,				// 09
	LOGCOMMAND_TYPE_MARKET,				// 10
	LOGCOMMAND_TYPE_STORAGE,			// 11
	LOGCOMMAND_TYPE_POSTOFFICE,			// 12
	LOGCOMMAND_TYPE_HORSEMARKET,		// 13
	LOGCOMMAND_TYPE_FARM,				// 14
	LOGCOMMAND_TYPE_MINE,				// 15
	LOGCOMMAND_TYPE_PARTY,				// 16
	LOGCOMMAND_TYPE_FRIEND,				// 17
	LOGCOMMAND_TYPE_ITEMMALL,			// 18
	LOGCOMMAND_TYPE_PRIVATETRADE,		// 19
	LOGCOMMAND_TYPE_NPCTRADE,			// 20
	LOGCOMMAND_TYPE_PRISON,				// 21
	LOGCOMMAND_TYPE_FEAST,				// 22
	LOGCOMMAND_TYPE_GACHA,				// 23
	LOGCOMMAND_TYPE_GENERALMEETING,		// 24
	LOGCOMMAND_TYPE_GUILD,				// 25
	LOGCOMMAND_TYPE_HORSESET,			// 26
	LOGCOMMAND_TYPE_HOUSE,				// 27
	LOGCOMMAND_TYPE_HOUSEHORSE,			// 28
	LOGCOMMAND_TYPE_HUNT,				// 29
	LOGCOMMAND_TYPE_INPORTANTPARAMEATA,	// 30
	LOGCOMMAND_TYPE_MINISTER,			// 31
	LOGCOMMAND_TYPE_MOFUMOFU_EVENT,		// 32
	LOGCOMMAND_TYPE_NPC,				// 33
	LOGCOMMAND_TYPE_TEACHER,			// 34
	LOGCOMMAND_TYPE_PERSONITEM,			// 35
	LOGCOMMAND_TYPE_RANK,				// 36
	LOGCOMMAND_TYPE_REALESTATE,			// 37
	LOGCOMMAND_TYPE_SKILL,				// 38
	LOGCOMMAND_TYPE_STRUCTURE,			// 39
	LOGCOMMAND_TYPE_SUMMON_HERO_MARKET,	// 40
	LOGCOMMAND_TYPE_SUMMON_MARKET,		// 41
	LOGCOMMAND_TYPE_SYSTEM,				// 42
	LOGCOMMAND_TYPE_TAX,				// 43
	LOGCOMMAND_TYPE_TRADE_SERVER,		// 44
	LOGCOMMAND_TYPE_VILLAGE,			// 45
	LOGCOMMAND_TYPE_WORLD_MONEY,		// 46
	LOGCOMMAND_TYPE_SELL_TO_FOREIGN_MERCHANT,	// 47
	LOGCOMMAND_TYPE_ARTIFACT,			// 48
	LOGCOMMAND_TYPE_ATTEND,				// 49
	LOGCOMMAND_TYPE_SPACEBOX,			// 50
	LOGCOMMAND_TYPE_SERVER_EVENT,		// 51
	LOGCOMMAND_TYPE_WORLD_PASSPORT,		// 52
	LOGCOMMAND_TYPE_BLACKARMY,			// 53 배틀필드 흑의군단
	LOGCOMMAND_TYPE_PERSONALPVP,		// 54 개인간 PVP
	LOGCOMMAND_TYPE_PERSONALPVP_LEAGUE,	// 55 PVP 리그
	LOGCOMMAND_TYPE_NEWMARKET,			// 56
	LOGCOMMAND_TYPE_FAMILY,				// 57 가족관련
	LOGCOMMAND_TYPE_BALANCECURRENCY,	// 58 통화량흡수정책
	LOGCOMMAND_TYPE_RACCOONDODGE_EVENT,	// 59 라쿤 피하기 이벤트
	LOGCOMMAND_TYPE_GAWIBAWIBO,			// 60 가위바위보
	LOGCOMMAND_TYPE_BOKBULBOK,			// 61 복불복 게임
	LOGCOMMAND_TYPE_DORMANCY,			// 62 휴면 계정 시스템
	LOGCOMMAND_TYPE_REWARD,				// 63 보상
	LOGCOMMAND_TYPE_BATTLEROYAL,		// 64 배틀로얄
	LOGCOMMAND_TYPE_COMMISSION		// 65 의뢰
};


enum // LOGCOMMAND_TYPE_LOGIN
{
	LOGCOMMAND_INDEX_LOGIN = 1,
	LOGCOMMAND_INDEX_LOGOUT
};
	    
enum // LOGCOMMAND_TYPE_CHARACTOR
{
	LOGCOMMAND_INDEX_MAKECHAR = 1,
	LOGCOMMAND_INDEX_DELCHAR,
	LOGCOMMAND_INDEX_CHARDIE,
	LOGCOMMAND_INDEX_CHARLEVELUP,
	LOGCOMMAND_INDEX_CHARLPK,
	
	LOGCOMMAND_INDEX_CHARACTER_CHANGE_MONEY,
	LOGCOMMAND_INDEX_CHARACTER_BLOCK_USER,
	LOGCOMMAND_INDEX_CHARACTER_MOVE_MONEY,			//사용안함.
	LOGCOMMAND_INDEX_CHARACTER_CHANGE_NAME,
	LOGCOMMAND_INDEX_CHARACTER_CHANGE_KIND,
	LOGCOMMAND_INDEX_CHARACTER_GAME_EVENT,			//사용안함.
	LOGCOMMAND_INDEX_CHARACTER_RECOMMEND_POINT_SET,	//사용안함. LOGCOMMAND_INDEX_RECOMMENDER_POINT_SET로 사용.
	LOGCOMMAND_INDEX_CHARACTER_RECOMMEND_POINT_GIVE,	//사용안함.LOGCOMMAND_INDEX_RECOMMENDER_POINT_GIVE로 사용.
	LOGCOMMAND_INDEX_CHARACTER_BUF_ADD,
	LOGCOMMAND_INDEX_CHARACTER_BUF_DELETE,
	LOGCOMMAND_INDEX_CHARACTER_PUCHIKIMI_SET,	//사용안함
	LOGCOMMAND_INDEX_CHARACTER_TEACHER_SET,			//사용안함
	LOGCOMMAND_INDEX_CHARACTER_TEACHER_POINT_SET,	//사용안함
	LOGCOMMAND_INDEX_CHARACTER_TEACHER_POINT_USE,	//사용안함
	LOGCOMMAND_INDEX_CHARACTER_TEACHER_RENOUNCE_PUPIL,	//사용안함, LOGCOMMAND_INDEX_FATHER_RENOUNCEPUPIL로 사용.

	LOGCOMMAND_INDEX_CHARLDIE_VILLAGEWAR,
	LOGCOMMAND_INDEX_CHARLDIE_GUILDWAR,
	LOGCOMMAND_INDEX_CHARHOUSE_GET,					// 캐릭터보관소에서 캐릭터 꺼내기
	LOGCOMMAND_INDEX_USEGMCOMMAND,					// GM명령어 사용
	LOGCOMMAND_INDEX_CHARACTER_USESUBTITLE,			// 자막광고 이용권 사용기록
};

enum{//LOGCOMMAND_TYPE_STOCK

	LOGCOMMAND_INDEX_STOCKRESPONSE = 1,		//주식 공모
	LOGCOMMAND_INDEX_STOCKBUY,				//주식 매입
	LOGCOMMAND_INDEX_STOCKSELL,				//주식 매각
	LOGCOMMAND_INDEX_STOCKRESIDENSHARE,		//주식 배당금
	LOGCOMMAND_INDEX_STOCKLOSS,				//주식 소각

	LOGCOMMAND_INDEX_STOCK_ORDER_CANCEL,	// 주식주문을 취소할 것을 요청.
	LOGCOMMAND_INDEX_STOCK_ORDER,			// 주식주문
	LOGCOMMAND_INDEX_STOCK_TRADE,			// 사용안함
	LOGCOMMAND_INDEX_STOCK_BID_COMPLETE,		// 주식 증자 완료.
	LOGCOMMAND_INDEX_STOCK_DISTRIBUTION,		// 주식 공모 구입
	LOGCOMMAND_INDEX_STOCK_MAX_DISTRIBUTION_SET,// 최대 주식 공모.
	LOGCOMMAND_INDEX_STOCK_VILLAGE_WAR_LOSS,	// 사용안함
	LOGCOMMAND_INDEX_STOCK_BID_RETURN,			// 사용안함
	LOGCOMMAND_INDEX_STOCK_BID,						// 주식 증자 참여기록.
	LOGCOMMAND_INDEX_STOCK_BID_BUY,					// 증자주식 사기
	LOGCOMMAND_INDEX_STOCK_OFFERING_SET,			// 주식 공모 마을 설정 (공모 청약 시작)
	LOGCOMMAND_INDEX_STOCK_OFFERING_END,			// 주식 공모 청약 종료
	LOGCOMMAND_INDEX_STOCK_OFFERING_ORDER,			// 주식 공모 청약 주문.
	LOGCOMMAND_INDEX_STOCK_OFFERING_ORDER_EXECUTE,	// 주식 청약 주문 실행
	LOGCOMMAND_INDEX_STOCK_OFFERING_ORDER_RESET,	// 주식 청약 주문 리셋.
	LOGCOMMAND_INDEX_STOCK_PRIVATETRADE				// 주식 개인 거래 습득
};


//------------------------------------------------------------------------------------//
// -> [로그추가 : 황진성 2007.9.3]

enum	//LOGCOMMAND_TYPE_QUEST
{
	LOGCOMMAND_INDEX_QUEST_START = 1,			// 현재 해피빈 퀘스트에서만 쓰이고 있음. 주석처리
	LOGCOMMAND_INDEX_QUEST_RUN,					// 사용안함.
	LOGCOMMAND_INDEX_QUEST_COMPLITE,			// 현재 해피빈 퀘스트에서만 쓰이고 있음. 주석처리

	LOGCOMMAND_INDEX_QUEST_INFO_SET,
	LOGCOMMAND_INDEX_QUEST_DAILY_QUEST_ADD,
	LOGCOMMAND_INDEX_QUEST_DAILY_QUEST_END,
	LOGCOMMAND_INDEX_QUEST_DAILY_QUEST_CHANGE,
	LOGCOMMAND_INDEX_QUEST_SPECIALL_INFO_SET,	// 사용안함, LOGCOMMAND_INDEX_QUEST_SPECIALL_QUEST_CHANGE과 LOGCOMMAND_INDEX_QUEST_SPECIALL_QUEST_END로 나누어서 관리함.
	LOGCOMMAND_INDEX_QUEST_NAMING_INFO_SET,
	LOGCOMMAND_INDEX_QUEST_DAILY_QUEST2_ADD,
	LOGCOMMAND_INDEX_QUEST_DAILY_QUEST2_END,
	LOGCOMMAND_INDEX_QUEST_DAILY_QUEST2_CHANGE,
	LOGCOMMAND_INDEX_QUEST_DAILY_QUEST3_ADD,
	LOGCOMMAND_INDEX_QUEST_DAILY_QUEST3_END,
	LOGCOMMAND_INDEX_QUEST_DAILY_QUEST3_CHANGE,
	LOGCOMMAND_INDEX_QUEST_SPECIALL_QUEST_CHANGE,
	LOGCOMMAND_INDEX_QUEST_SPECIALL_QUEST_END
};

enum	//LOGCOMMAND_TYPE_RECOMMENDER
{
	LOGCOMMAND_INDEX_RECOMMENDER_ADD = 1,			// 추천인 등록.(추천인을 등록)
	LOGCOMMAND_INDEX_RECOMMENDER_RECOMMENDPERSON,	// 추천인 대상.(추천을 받음), 주석처리
	LOGCOMMAND_INDEX_RECOMMENDER_REWARD,			// 추천인 보상.(사용안함)
	LOGCOMMAND_INDEX_COMMENDER_REWARD,				// 피추천인 보상.
	LOGCOMMAND_INDEX_RECOMMENDER_POINT_SET,			// 추천인 포인트확인
	LOGCOMMAND_INDEX_RECOMMENDER_POINT_GIVE			// 추천인 포인트받기(사용안함)
};

enum	//LOGCOMMAND_TYPE_SUMMON
{
	LOGCOMMAND_INDEX_SUMMON_MAKE = 1,			// 소환수 생성. (사용안함)
	LOGCOMMAND_INDEX_SUMMON_EVOLVE,				// 소환수 진화.
	LOGCOMMAND_INDEX_SUMMON_FREE,				// 소환수 풀어주기. (사용안함)

	LOGCOMMAND_INDEX_SUMMON_SET,				// 상태 변화.
	LOGCOMMAND_INDEX_SUMMON_REVIVE,				// 부활.
	LOGCOMMAND_INDEX_SUMMON_SCROLL,				// 부적 및 강화시 (사용안함)
	LOGCOMMAND_INDEX_SUMMON_STATUS_INIT,		// 소환수 초기화
	LOGCOMMAND_INDEX_SUMMON_SET_AUTO_HEAL,		// 소환수 자동 회복.(사용안함)
	LOGCOMMAND_INDEX_SUMMON_TRADE,				// 소환수 판매.
	LOGCOMMAND_INDEX_SUMMON_STON,				// 소환수 장비 장착석 (사용안함)
	LOGCOMMAND_INDEX_SUMMON_LEVELUP				// 소환수 레벨업
};

enum //LOGCOMMAND_TYPE_FATHER
{
	LOGCOMMAND_INDEX_FATHER_APPLYFATHER = 1,	// 스승 신청.
	LOGCOMMAND_INDEX_FATHER_SETFATHER,			// 스승 등록.
	LOGCOMMAND_INDEX_FATHER_SETCHILD,			// 제자 등록. (사용안함)
	LOGCOMMAND_INDEX_FATHER_CHANGE,				// 스승 변경. (사용안함, LOGCOMMAND_INDEX_FATHER_RENOUNCEFATHER로 대체)
	LOGCOMMAND_INDEX_FATHER_RENOUNCEPUPIL,		// 제자 해지.
	LOGCOMMAND_INDEX_FATHER_RENOUNCEFATHER,		// 스승 해지.
	LOGCOMMAND_INDEX_FATHER_OVERTAKE_TEACHER_LEVEL		//제자가 스승레벨을 앞질렀다.(LOGCOMMAND_INDEX_TEACHER_OVERTAKE_TEACHER_LEVEL에서 가져옴)
};

enum // LOGCOMMAND_TYPE_MINE <광산> 
{
	LOGCOMMAND_INDEX_RENT_APPLY = 1,	// 임차 신청. 사용안함(LOGCOMMAND_INDEX_MINE_RENT_APPLY로 대체)
	LOGCOMMAND_INDEX_CANCEL_APPLY,		// 임차 취소. 사용안함(LOGCOMMAND_INDEX_MINE_CANCEL_RENT_APPLY로 대체)
	LOGCOMMAND_INDEX_RENT,				// 임대. 시용안함(LOGCOMMAND_INDEX_MINE_RENT로 대체)
	LOGCOMMAND_INDEX_RENT_RECALL,		// 임대완료.(반환시점), 사용안함(LOGCOMMAND_INDEX_MINE_RECALL로 대체)

	LOGCOMMAND_INDEX_MINE_RENT_APPLYER_DELETE,	// 광산임대 희망자 제거.
	LOGCOMMAND_INDEX_MINE_RENT_RENT_FREE_PAY,	// 광산임대 수수료 지불.
	LOGCOMMAND_INDEX_MINE_RECALL,				

	LOGCOMMAND_INDEX_MINE_RENT_APPLY,				// 임차 신청.
	LOGCOMMAND_INDEX_MINE_CANCEL_RENT_APPLY,		// 임차 취소.
	LOGCOMMAND_INDEX_MINE_RENT						// 임대.				
};

enum // LOGCOMMAND_TYPE_PARTY <파티>
{
	LOGCOMMAND_INDEX_PARTY_START = 1,	// 파티 시작. 사용안함(LOGCOMMAND_INDEX_PARTY_CREATEJOIN으로 대체)
	LOGCOMMAND_INDEX_PARTY_OPTION,		// 파티 설정. 사용안함(LOGCOMMAND_INDEX_PARTY_CHANGEITEMGETPATTERN로 대체)
	LOGCOMMAND_INDEX_PARTYFORCE_LEAVE,	// 파티 강퇴. 사용안함(LOGCOMMAND_INDEX_PARTY_FORCELEAVE로 대체)
	LOGCOMMAND_INDEX_PARTY_END,			// 파티 종료.

	LOGCOMMAND_INDEX_PARTY_CREATEJOIN ,						// 파티 시작.
	LOGCOMMAND_INDEX_PARTY_CHANGEITEMGETPATTERN,			// 파티 설정 (아이템 획득방식 변경)
	LOGCOMMAND_INDEX_PARTY_FORCELEAVE						// 파티 강퇴.
};


enum	// LOGCOMMAND_TYPE_FRIEND
{
	LOGCOMMAND_INDEX_FRIEND_ADD = 1,	// 친구 등록.
	LOGCOMMAND_INDEX_FRIEND_DEL			// 친구 삭제.
};

enum	// LOGCOMMAND_TYPE_ITEMMALL
{
	LOGCOMMAND_INDEX_ITEMMALL_BUY = 1,	// 아이템 몰 구입.
	LOGCOMMAND_INDEX_ITEMMALL_GET,		// 아이템 몰 수령.

	LOGCOMMAND_INDEX_ITEMMALL_GIFT,
	LOGCOMMAND_INDEX_ITEMMALL_GIFTITEMGLOBAL,	// !!주석
	LOGCOMMAND_INDEX_ITEMMALL_BUYITEMGLOBAL,	// !!주석
	LOGCOMMAND_INDEX_ITEMMALL_WEB_GIFT			
};

enum	// LOGCOMMAND_TYPE_PRIVATETRADE
{
	LOGCOMMAND_INDEX_PRIVATETRADE_START = 1,// 개인상점 시작.
	LOGCOMMAND_INDEX_PRIVATETRADE_SELL,		// 개인상점 판매.
	LOGCOMMAND_INDEX_PRIVATETRADE_BUY,		// 개인상점 구매.
	LOGCOMMAND_INDEX_PRIVATETRADE_END		// 개인상점 종료.
};

enum	// LOGCOMMAND_TYPE_NPCTRADE	
{
	LOGCOMMAND_INDEX_NPCTRADE_BUY = 1,	// NPC 구매, 사용안함
	LOGCOMMAND_INDEX_NPCTRADE_SELL		// NPC 판매, 사용안함
};

enum	// LOGCOMMAND_TYPE_CITYHALL
{
	LOGCOMMAND_INDEX_CITYHALL_APPLYRESIDENT = 1,		// 주민등록 신청.
	LOGCOMMAND_INDEX_CITYHALL_BERESIDENT,				// 주민등록 허락.
	LOGCOMMAND_INDEX_CITYHALL_PAYDIVIDEND,				// 주주배당.		[현재 주석 처리]
	LOGCOMMAND_INDEX_CITYHALL_RESIDENTCANCEL,			// 주민등록 신청 취소.
	LOGCOMMAND_INDEX_CITYHALL_NPCHIRE,					// NPC고용
	LOGCOMMAND_INDEX_CITYHALL_INOUTMONEY,				// 관청 보유자금 입출금 내역.				
	LOGCOMMAND_INDEX_CITYHALL_PROFITTOCAPITALFUND,		// 이익금을 증가 시키거나 감소. (사용안함)
	LOGCOMMAND_INDEX_CITYHALL_SATATECHANGE,				// 마을 상태 변경.							
	LOGCOMMAND_INDEX_CITYHALL_DIVIDENDSUMMARY,			// 마을에서 자동 배당하기.	
	LOGCOMMAND_INDEX_CITYHALL_DIVIDENDSTOCKHOLDERTOP100,// 사용안함
	LOGCOMMAND_INDEX_CITYHALL_DIVIDENDRESIDENTS,		// 주식 배당금.
	LOGCOMMAND_INDEX_CITYHALL_VILLAGEGIVEITEM,			// 마을주민에게 아이템 지급하기.		
	LOGCOMMAND_INDEX_CITYHALL_DISMISS_RESIDENT			// 1년동안 로그인하지 않아 강제 주민을 내보냄.
};

enum	// LOGCOMMAND_TYPE_BANK
{
	LOGCOMMAND_INDEX_BANK_CREATEBANKACCOUNT = 1,// 통장개설.
	LOGCOMMAND_INDEX_BANK_CLOSEBANKACCOUNT,		// 통장해지.
	LOGCOMMAND_INDEX_BANK_INPUTMONEYTOBANK,		// 입금.
	LOGCOMMAND_INDEX_BANK_OUTPUTMONEYFROMBANK,	// 출금.
	LOGCOMMAND_INDEX_BANK_SET_BANK,				// 세팅.
	LOGCOMMAND_INDEX_BANK_SET_FEE				// 수수료 세팅.
};

enum	// LOGCOMMAND_TYPE_MARKET
{
	LOGCOMMAND_INDEX_MARKET_ORDERMARKET = 1,	// 물품등록.
	LOGCOMMAND_INDEX_MARKET_GETITEMFROMMARKET,	// 물품회수.
	LOGCOMMAND_INDEX_MARKET_SELL,				// 물품판매.
	LOGCOMMAND_INDEX_MARKET_BUY,				// 물품구매.
	
	LOGCOMMAND_INDEX_MARKET_ITEMPRICESET,		// 거래된 가격을 설정. 사용안함.
	LOGCOMMAND_INDEX_MARKET_REDUCEORDERPRICE	// 변경된 주문 정보(가격인하). 
};

enum	// LOGCOMMAND_TYPE_STORAGE
{
	LOGCOMMAND_INDEX_STORAGE_HOUSERENTAPPLY = 1,	// 창고 임차신청. 사용안함
	LOGCOMMAND_INDEX_STORAGE_HOUSERENTAPPLYCANCEL,  // 창고 임차신청 취소. 사용안함
	LOGCOMMAND_INDEX_STORAGE_MOVEITEMINVTOSTG,		// 창고 보관. (아이템을 인벤에서 창고로 옮기는것에 대한 응답.) 사용안함
	LOGCOMMAND_INDEX_STORAGE_MOVEITEMSTGTOINV		// 창고에서 아이템 회수. (아이템을 창고에서 인벤으로 옮기는것에 대한 응답.) 사용안함
};

enum	// LOGCOMMAND_TYPE_POSTOFFICE
{
	LOGCOMMAND_INDEX_POSTOFFICE_SEND_ITEM = 1,		// 아이템 보내기.
	LOGCOMMAND_INDEX_POSTOFFICE_SEND_MONEY,			// 송금 하기.
	LOGCOMMAND_INDEX_POSTOFFICE_SEND_MSG,			// 메시지 보내기.
	LOGCOMMAND_INDEX_POSTOFFICE_GET,				// 수신하기. 사용안함(LOGCOMMAND_INDEX_POSTOFFICE_GET_MSG, LOGCOMMAND_INDEX_POSTOFFICE_GET_ITEM, LOGCOMMAND_INDEX_POSTOFFICE_GET_MONEY로 분리함)

	LOGCOMMAND_INDEX_POSTOFFICE_GET_MSG,			// 메시지 수신하기.
	LOGCOMMAND_INDEX_POSTOFFICE_GET_ITEM,			// 아이템 수신하기.
	LOGCOMMAND_INDEX_POSTOFFICE_HOUSEUNIT_EXPIRED_ITEM_GET,			// 클라라 김선달 NPC에게 아이템 회수.
	LOGCOMMAND_INDEX_POSTOFFICE_HOUSEUNIT_EXPIRED_HORSE_GET,		// 클라라 NPC에게 말 회수.
	LOGCOMMAND_INDEX_POSTOFFICE_GET_MONEY			// 돈 수신하기.
};


enum //LOGCOMMAND_TYPE_HORSEMARKET
{
	LOGCOMMAND_INDEX_HORSEMARKET_ORDERSELL = 1,			// 탈것 판매등록.
	LOGCOMMAND_INDEX_HORSEMARKET_SELLCANCEL,			// 탈것 판매취소.
	LOGCOMMAND_INDEX_HORSEMARKET_SELL,					// 탈것 판매.
	LOGCOMMAND_INDEX_HORSEMARKET_BUY,					// 탈것 구입.
	LOGCOMMAND_INDEX_HORSEMARKET_REDUCEHORSEORDERPRICE,	// 말의 가격 하락.
	LOGCOMMAND_INDEX_HORSEMARKET_PRICESET				// 말 시세.
};

enum //LOGCOMMAND_TYPE_FARM
{
	LOGCOMMAND_INDEX_FARM_RENTAPPLY = 1,			// 농장 임차 신청.
	LOGCOMMAND_INDEX_FARM_CANCELRENTAPPLY,			// 농장 임차 취소.
	LOGCOMMAND_INDEX_FARM_RENT,						// 농장 임대.
	LOGCOMMAND_INDEX_FARM_END,						// 농장 임대 완료.(반환)

	LOGCOMMAND_INDEX_FARM_RENTAPPLYDELETE,			// 농장 임대 희망자 명단을 삭제. 
	LOGCOMMAND_INDEX_FARM_RENTFEEPAY,				// 농장 이용료 지불. 
	LOGCOMMAND_INDEX_FARM_RECALL,					// 사용안함.
	LOGCOMMAND_INDEX_FARM_WORKINGPAYMONEYFORRENT,	// 농장 임시로 빌려.
	LOGCOMMAND_INDEX_FARM_AGRICULTURE_EXPIRE		// 농장 만기.			
};

enum //LOGCOMMAND_TYPE_PRISON
{
	LOGCOMMAND_INDEX_PRISON_IN = 1,					// 감옥 이동.
	LOGCOMMAND_INDEX_GUILTY_INFORECORD,				// 범죄 기록.
	LOGCOMMAND_INDEX_REQUEST_SUSPECTUSER,			// 매크로 의심 유저 신고
	LOGCOMMAND_INDEX_CHECK_SUSPECTUSER_BYQUIZ,		// 매크로 의심 유저에게 퀴즈 보냄.
};

enum // LOGCOMMAND_TYPE_FEAST						// 연회.
{
	LOGCOMMAND_INDEX_FEAST_RESERVE = 1,				// 연회 예약				
	LOGCOMMAND_INDEX_FEAST_ADDPRESENTLIST,			// 연회 중 선물로 아이템 얻어.
	LOGCOMMAND_INDEX_FEAST_DELPRESENTLIST,			// 연회 선물 목록에서 삭제.	
	LOGCOMMAND_INDEX_FEAST_STGITEMIN,				// 내자시 행수가 창고에 아이템을 넣는다	
	LOGCOMMAND_INDEX_FEAST_STGITEMOUT,				// 내자시 행수가 창고에서 아이템을 빼낸다.		
	LOGCOMMAND_INDEX_FEAST_SETCOST,					// 연회 금액 설정.
	LOGCOMMAND_INDEX_FEAST_OPEN,					// 연회를 시작
	LOGCOMMAND_INDEX_FEAST_CLOSE,					// 연회를 끝낸다.
	LOGCOMMAND_INDEX_FEAST_GIVEITEM,				// 연회 신청자가 연회 물품을 지급
	LOGCOMMAND_INDEX_FEAST_USEEFFECT				// 연회 폭죽.
};

enum	// LOGCOMMAND_TYPE_GACHA
{
	LOGCOMMAND_INDEX_GACHA_BUYUSED = 1,				// 가차 열쇠로 아이템을 구입할 것을 요청
	LOGCOMMAND_INDEX_GACHA_BUY
};

enum	// LOGCOMMAND_TYPE_GENERALMEETING				// 주주총회.
{
	LOGCOMMAND_INDEX_GENERALMEETING_SUGGESTCHIEF = 1,	// 주주총회 발의. 
	LOGCOMMAND_INDEX_GENERALMEETING_VOTE,				// 투표.
	LOGCOMMAND_INDEX_GENERALMEETING_ACCEPTCANDIDATE,	// 주주총회 동의
	LOGCOMMAND_INDEX_GENERALMEETING_CLOSECHIEF,			// 주주총회 종료.
	LOGCOMMAND_INDEX_GENERALMEETING_VOTERSTATESET		// 주주총회 참여 여부를 설정한다
};

enum	// LOGCOMMAND_TYPE_GUILD						// 길드.
{
	LOGCOMMAND_INDEX_GUILD_CREATE = 1,					// 길드개설
	LOGCOMMAND_INDEX_GUILD_DESTROY,						// 길드제거.
	LOGCOMMAND_INDEX_GUILD_CHANGEVILLAGE,				// 변경된 길드의 정보
	LOGCOMMAND_INDEX_GUILD_JOINCONFIRM,					// 길드 가입을 허가,불허를 결정.
	LOGCOMMAND_INDEX_GUILD_LEAVE,						// 길드 탈퇴
	LOGCOMMAND_INDEX_GUILD_JOIN,						// 길드 가입을 요청
	LOGCOMMAND_INDEX_GUILD_CONFIRMCREATE,				// 길드 생성을 허가.
	LOGCOMMAND_INDEX_GUILD_GIVEMONEY,					// 길드 자금을 납부
	LOGCOMMAND_INDEX_GUILD_SETSECONDMASTER,				// 부길드 장.
	LOGCOMMAND_INDEX_GUILD_SETSTRFEERATE,				// 길드 건물의 수수료가 변경.
	LOGCOMMAND_INDEX_GUILD_CHANGEGUILDPOINT,			// 길드의 GP가 변화.
	LOGCOMMAND_INDEX_GUILD_GIVEFEE,						// 길드 수수료.
	LOGCOMMAND_INDEX_GUILD_STATUSCHANGE,				// 길드 능력치가 변경.
	LOGCOMMAND_INDEX_GUILD_NAMECHANGE,					// 길드 이름 변경.
	LOGCOMMAND_INDEX_GUILD_MASTERCHANGE,				// 길드 마스터 변경
	LOGCOMMAND_INDEX_GUILD_WARADDRESERVE,				// 길드전 예약	
	LOGCOMMAND_INDEX_GUILD_DUNGEONAPPLY,				// 사냥터 소유권 신청하기.
	LOGCOMMAND_INDEX_GUILD_DUNGEONSAVESTATUS,			// 사용안함.
	LOGCOMMAND_INDEX_GUILD_DUNGEONTRANSFEROWNERSHIP,	// 사용안함
	LOGCOMMAND_INDEX_GUILD_DESTROY_MONTH,				// 휴면길드제거.
	LOGCOMMAND_INDEX_GUILD_MASTERCHANGE_NOTCONNECT_MONTH,	// 한달이상 미접속 길드 마스터 변경
	LOGCOMMAND_INDEX_GUILD_WARRESULT					// 길드전 결과
};


//enum		// LOGCOMMAND_TYPE_HORSESET					// 탈것.
//{
//	LOGCOMMAND_INDEX_HORSESET_SET = 1,					// 말 설정.
//	LOGCOMMAND_INDEX_HORSESET_NAMECHANGE,				// 말 이름 변경.
//	LOGCOMMAND_INDEX_HORSESET_AUTOFOOD					// 사용안함.
//};

enum		// LOGCOMMAND_TYPE_HORSESET					// 탈것.
{
	LOGCOMMAND_INDEX_HORSESET_SET = 1,					// 말 설정.
	LOGCOMMAND_INDEX_HORSESET_NAMECHANGE,				// 말 이름 변경.
	LOGCOMMAND_INDEX_HORSESET_AUTOFOOD,					// 사용안함.
	LOGCOMMAND_INDEX_HORSESET_PRIVATETRADE				// 개인 거래
};

enum		// LOGCOMMAND_TYPE_HOUSE
{
	LOGCOMMAND_INDEX_HOUSE_RENTAPPLY = 1,				// 시전 임대 신청 
	LOGCOMMAND_INDEX_HOUSE_RENT,						// 시전 임대 
	LOGCOMMAND_INDEX_HOUSE_RENTAPPLYCANCEL,				// 시전 임대 취소	
	LOGCOMMAND_INDEX_HOUSE_DELETEHOUSERENTAPPLYER,		// 임차 희망자의 명단을 삭제.	
	LOGCOMMAND_INDEX_HOUSE_RENTFEEPAY,					// 시전의 임대료를 지불	
	LOGCOMMAND_INDEX_HOUSE_RECALL,						// 시전 회수
	LOGCOMMAND_INDEX_HOUSE_EXTENDHOUSECONTRACT,			// 시전 계약을 연장.
	LOGCOMMAND_INDEX_HOUSE_CREATE,						// 시전에서 고물상 생성. 사용안함
	LOGCOMMAND_INDEX_HOUSE_SALVAGEFROM,					// 고물 하는 물품 MakePercent = 59% (회수율), 사용안함.
	LOGCOMMAND_INDEX_HOUSE_SALVAGETO,					// 사용안함.
	LOGCOMMAND_INDEX_HOUSE_MOVEITEMINVTOSTG,			// 창고에 아이템 보관. 
	LOGCOMMAND_INDEX_HOUSE_MOVEITEMSTGTOINV,			// 창고 아이템 회수.
};

enum		// LOGCOMMAND_TYPE_HOUSEHORSE
{
	LOGCOMMAND_INDEX_HOUSEHORSE_HORSEINHOUSE = 1,		// 마구간에서 말 넣은 기록.
	LOGCOMMAND_INDEX_HOUSEHORSE_HORSEOUTHOUSE,			// 마구간에서 말 꺼낸 기록.
	LOGCOMMAND_INDEX_HOUSEHORSE_CREATE_HORSE_STABLE,	// 마구간을 생성.		
	LOGCOMMAND_INDEX_HOUSEHORSE_SETHOUSEHORSEINFO,		// 시전에 보관된 말의 상태가 변경된 내역이 기록
};

enum		// LOGCOMMAND_TYPE_HUNT
{
	LOGCOMMAND_INDEX_HUNT_STGINPUT = 1,					// 수렵장 창고에 동물을 넣는다.
	LOGCOMMAND_INDEX_HUNT_STGOUTPUT,					// 수렵장 창고에 들어가 있는 동물을 빼낸다.
	LOGCOMMAND_INDEX_HUNT_MONSTERADD,					// 수렵장에 넣을 동물과 마리수를 입력한다. ( 리스트에 추가 )
	LOGCOMMAND_INDEX_HUNT_MONSTERDEL,					// 수렵장에 넣어진 동물과 마리수를 리스트에서 삭제한다. ( 리스트에서 삭제 )
};

enum		// LOGCOMMAND_TYPE_INPORTANTPARAMEATA
{
	LOGCOMMAND_INDEX_INPORTANTPARAMEATA_SETLEVELINFO = 1,	// 레벨 정보를 설정, 사용안함.
	LOGCOMMAND_INDEX_INPORTANTPARAMEATA_SETBONUSINFO,		// 캐릭터 보너스 수치 상태 변경.
	LOGCOMMAND_INDEX_INPORTANTPARAMEATA_SETPOSLIFEMANA,		// 위치, 체력, 마법력 정보
	LOGCOMMAND_INDEX_INPORTANTPARAMEATA_EXPCHAMGE,			// 경험치 변동 내역(직접적인 사냥 이외의 다른 경우에 의한…)
	LOGCOMMAND_INDEX_INPORTANTPARAMEATA_INITSTATUS,			// 상태 초기화. (능력을 모두 5로 초기화 할때.)
	LOGCOMMAND_INDEX_INPORTANTPARAMEATA_CHANGEFAMEEXP,		// 명성 경험치가  변경.
};

enum		// LOGCOMMAND_TYPE_MINISTER
{
	LOGCOMMAND_INDEX_MINISTER_YEZO_SET = 1,					// 예조설정, 사용안함(5대신에 예조는 포함안됨)
	LOGCOMMAND_INDEX_MINISTER_BYUNGZO_SET,					// 병조설정.
	LOGCOMMAND_INDEX_MINISTER_BYUNGZO_VILLAGE_WAR_SET,		// 병조마을 전쟁.
	LOGCOMMAND_INDEX_MINISTER_HOZO_SET,						// 호조설정
	LOGCOMMAND_INDEX_MINISTER_IZO_SET,						// 이조설정
	LOGCOMMAND_INDEX_MINISTER_GONGZO_SET,					// 공조설정
	LOGCOMMAND_INDEX_MINISTER_HYUNGZO_SET,					// 형조설정
	LOGCOMMAND_INDEX_MINISTER_GOONZU_FINANCES_SET,			// 군주재정.		
	LOGCOMMAND_INDEX_MINISTER_ANGEL_APPLY_SET,				// 수호천사등록.
	LOGCOMMAND_INDEX_MINISTER_ANGEL_SET,					// 수호천사 임명과 해임.
	LOGCOMMAND_INDEX_MINISTER_SET,							// 판서설정
	LOGCOMMAND_INDEX_MINISTER_POLICE_SET,					// 보안관임명.
	LOGCOMMAND_INDEX_MINISTER_GOONZU_BONUS_SET,				// 보너스타임설정.(정보가 부족한듯...)
};

enum		// LOGCOMMAND_TYPE_MOFUMOFU_EVENT
{
	LOGCOMMAND_INDEX_MOFUMOFU_EVENT_START = 1,				// 모후모후 이벤트 시작.
	LOGCOMMAND_INDEX_MOFUMOFU_EVENT_ADD_RESERVE,			// 모후모후 이벤트 예약.
};

enum		// LOGCOMMAND_TYPE_NPC
{
	LOGCOMMAND_INDEX_NPC_TRADE_MERCHANT_SET = 1,			// 어떤 무역상인이 구입할려는 것을 설정.
	LOGCOMMAND_INDEX_NPC_TRADE_MERCHANT_BUY_ITEM,			// 유저가 무역 상인에게 물건을 판매한다.
	LOGCOMMAND_INDEX_NPC_TRADE_MERCHANT_BUY_HORSE,			// 상인이 말을 구입
	LOGCOMMAND_INDEX_NPC_TRADE_MERCHANT_BUY_CASHITEM,		// 무역상에 캐쉬아이템 판매시 기록.
};

enum		// LOGCOMMAND_TYPE_TEACHER
{
	LOGCOMMAND_INDEX_TEACHER_OVERTAKE_TEACHER_LEVEL = 1,	// 제자가 스승레벨을 앞질렀다, 사용안함(LOGCOMMAND_INDEX_FACHER_OVERTAKE_TEACHER_LEVEL로 옮김)
};

enum		// LOGCOMMAND_TYPE_PERSONITEM
{
	LOGCOMMAND_INDEX_PERSONITEM_GET_ITEM = 1,							//1 아이템 획득.
	LOGCOMMAND_INDEX_PERSONITEM_GET_ITEM_FROM_GM, // 사용안함			//2 운영자로부터 아이템 획득. - 사용안함
	LOGCOMMAND_INDEX_PERSONITEM_GET_ITEM_FROM_WAR, // 사용안함			//3 전쟁 중 획득한 보상품.(일반 몬스터를 잡아도) - 사용안함
	LOGCOMMAND_INDEX_PERSONITEM_PICKUP_ITEM, // 사용안함				//4 땅에서 주웠다. - 사용안함
	LOGCOMMAND_INDEX_PERSONITEM_MOVE_ITEM,								//5 person이 아이템 창간에 아이템을 이동시킨다. (인벤에서 갑옷창이나 그 반대와 같은 경우. ) 
	LOGCOMMAND_INDEX_PERSONITEM_OUTPUT_ITEM, // 사용안함				//6/ 사용안함
	LOGCOMMAND_INDEX_PERSONITEM_MOVE_ITEM_TO_PERSON,					//7 Person간에 아이템을 이동시킨다.
	LOGCOMMAND_INDEX_PERSONITEM_USE_ITEM,								//8 아이템 사용.
	LOGCOMMAND_INDEX_PERSONITEM_SELL_ITEM,								//9 NPC에게 판매.
	LOGCOMMAND_INDEX_PERSONITEM_BUY_ITEM,								//10 NPC에게 구매.
	LOGCOMMAND_INDEX_PERSONITEM_MOVE_INV_ITEM_TO_STG, // 사용안함		//11 <추가된 로그 사용 : LOGCOMMAND_INDEX_STORAGE_MOVEITEMINVTOSTG> - 사용안함.
	LOGCOMMAND_INDEX_PERSONITEM_STG_ITEM_TO_INV, // 사용안함			//12 <추가된 로그 사용 : LOGCOMMAND_INDEX_STORAGE_MOVEITEMSTGTOINV> - 사용안함
	LOGCOMMAND_INDEX_PERSONITEM_WASTE_DUR_ITEM,							//13 내구도 변경 기록.
	LOGCOMMAND_INDEX_PERSONITEM_REPAIR_ITEM,							//14 아이템 수리.
	LOGCOMMAND_INDEX_PERSONITEM_DROP_ITEM,								//15 아이템 버려.
	LOGCOMMAND_INDEX_PERSONITEM_MAKE_ITEM,								//16 아이템 제작으로 생산.
	LOGCOMMAND_INDEX_PERSONITEM_MAKE_ITEM_USED,							//17 사용안함.
	LOGCOMMAND_INDEX_PERSONITEM_ENCHANT_ITEM,							//18 부적을 무기에 적용시킨 내역.(부적 -> 강화아이템의 위치)
	LOGCOMMAND_INDEX_PERSONITEM_ENCHANT_ITEM_USED,						//19 사용안함
	LOGCOMMAND_INDEX_PERSONITEM_ENCHANT_ITEM_INV,						//20 인벤토리내에서 아이템 만들기.
	LOGCOMMAND_INDEX_PERSONITEM_PRIVATE_TRADE,							//21 개인 거래. (수정필요 : 정보가 너무 많음. 뭘 어떻게 넣어야 할지...)
	LOGCOMMAND_INDEX_PERSONITEM_WARP_VILLAGE, // 사용안함				//22 사용자를 Warp시킨다.
	LOGCOMMAND_INDEX_PERSONITEM_UPGRADE_ITEM,							//23 무기 강화.
	LOGCOMMAND_INDEX_PERSONITEM_UPGRADE_ITEM_USED,						//24
	LOGCOMMAND_INDEX_PERSONITEM_PERSONALSHOP_BUY_ITEM,					//25 <추가된 로그 사용>
	LOGCOMMAND_INDEX_PERSONITEM_PERSONALSHOP_SELL_ITEM,					//26 <추가된 로그 사용>
	LOGCOMMAND_INDEX_PERSONITEM_START_PERSONALSHOP,	// 사용안함			//27 <추가된 로그 사용>
	LOGCOMMAND_INDEX_PERSONITEM_FISHING,								//28 낚시로 고기 낚은 내용이 기록.
	LOGCOMMAND_INDEX_PERSONITEM_FISHING_TOOL_DUR_DECREASE, // 사용안함	//29 낚시대 내구 감소 내역.
	LOGCOMMAND_INDEX_PERSONITEM_PERSONITEM_PERFORMANCE_UPGRADE,			//30 아이템 성능 향상
	LOGCOMMAND_INDEX_PERSONITEM_PERSONITEM_PERFORMANCE_UPGRADE_USED,	//31 사용안함
	LOGCOMMAND_INDEX_PERSONITEM_PERSONITEM_AGRICULTURE,					//32 농경.
	LOGCOMMAND_INDEX_PERSONITEM_COUNT_ATTACK_INFO,						//33 사용안함
	LOGCOMMAND_INDEX_PERSONITEM_PREMIUM_SET,							//34 프리미엄 효과.
	LOGCOMMAND_INDEX_PERSONITEM_WENNY_OLDMAN_USEITEM,					//35
	LOGCOMMAND_INDEX_PERSONITEM_WENNY_OLDMAN_SAVE_INV,					//36 혹부리(2호식) 인벤토리에 저장 요청(수정필요 : 아이템 배열 리스트 정보들...)	
	LOGCOMMAND_INDEX_PERSONITEM_WENNY_OLDMAN_STG_TO_INV,				//37 혹부리(2호식) 인벤토리에 사용자 인벤으로 이동
	LOGCOMMAND_INDEX_PERSONITEM_BUY_RECOMMEND_PRODUCT,					//38 추천 포인트로 아이템을 구입.
	LOGCOMMAND_INDEX_PERSONITEM_EXCHANGE_ITEM_FROM, // 사용안함			//39 아이템 교체.
	LOGCOMMAND_INDEX_PERSONITEM_EXCHANGE_ITEM_TO,						//40 사용안함
	LOGCOMMAND_INDEX_PERSONITEM_TREASUREBOX_OPEN_USED,  				//41 보물상자 열기.
	LOGCOMMAND_INDEX_PERSONITEM_TREASUREBOX_OPEN_MAKED,	// 사용안함		//42 OPEN_USED와 중복되는 위치에 있어서...?
	LOGCOMMAND_INDEX_PERSONITEM_TREASUREBOX_OPEN_KEYUSED, // 사용안함	//43 보물상자 열때 사용된 키.
	LOGCOMMAND_INDEX_PERSONITEM_TREASUREBOX_OPEN_ADDED,	// 사용안함		//44 보물상자로 획득한 아이템.
	LOGCOMMAND_INDEX_PERSONITEM_ARTIFACT_USEITEM,						//45 아티펙트 환원에 사용된 아이템
	LOGCOMMAND_INDEX_PERSONITEM_ARTIFACT_SAVE_INV,						//46 아티펙트 환원에 의해 생성된 아이템 저장
	LOGCOMMAND_INDEX_PERSONITEM_ARTIFACT_STG_TO_INV,					//47 아티펙트 결과를 인벤토리로 이동
	LOGCOMMAND_INDEX_PERSONITEM_AMBER_BOX_GET_ITEM,						//48 [진성] 호박상자로 얻은 아이템.
	LOGCOMMAND_INDEX_PERSONITEM_NEWSELECTBOX_GET_ITEM,					//49 [영훈] 새로운 선택 상자로 아이템 얻음.
	LOGCOMMAND_INDEX_PERSONITEM_PRESENT_ITEM_TONPC,						//50 [기형] NPC에게 선물한 아이템.
	LOGCOMMAND_INDEX_PERSONITEM_PREMIUMITEM_USE,						//51 [기형] 프리미엄 아이템 사용
	LOGCOMMAND_INDEX_PERSONITEM_EXTENDTHETERM,							//52 [기형] 아이템 기간 연장
	LOGCOMMAND_INDEX_PERSONITEM_SPIRIT_CHARGE,							//53 [기형] 스피릿 충전
};

enum	// LOGCOMMAND_TYPE_RANK
{
	LOGCOMMAND_INDEX_RANK_SET = 1,		// Person을 특정 Rank로 만들어.			
	LOGCOMMAND_INDEX_RANK_ERSIGN		// 등록된 신분직을 사임.
};

enum	// LOGCOMMAND_TYPE_REALESTATE
{
	LOGCOMMAND_INDEX_REALESTATE_SELL_ORDER = 1,		// 부동산 판매 등록.
	LOGCOMMAND_INDEX_REALESTATE_SELL_ORDER_CANCEL,	// 부동산 판매 등록 취소.
	LOGCOMMAND_INDEX_REALESTATE_SELL_SET_FEE,		// 부동산 거래 수수료를  설정
	LOGCOMMAND_INDEX_REALESTATE_PRICE_REDUCE,		// 부동산 주문 정보 정리. 가격이 다운된다.
	LOGCOMMAND_INDEX_REALESTATE_BUY,				// 부동산 구입 내역.
	LOGCOMMAND_INDEX_REALESTATE_SELL_ORDER_DELETE,	// 부동산 주문이 유효 하지 않을 경우 삭제.
};

enum	// LOGCOMMAND_TYPE_SKILL
{
	LOGCOMMAND_INDEX_SKILL_INCREASE = 1,			// 캐릭터의 스킬 상승(책 읽거나, 경험에의해 상승될 때), LOGCOMMAND_INDEX_SKILL_CHANGE로 옮김
	LOGCOMMAND_INDEX_SKILL_DECREASE,				// 캐릭터의 스킬 감소. LOGCOMMAND_INDEX_SKILL_CHANGE로 옮김.
	LOGCOMMAND_INDEX_SKILL_SET_SKILL_EXP,			// 스킬 경험치가 변경될 때
	LOGCOMMAND_INDEX_SKILL_INCREASE_SKILL_MASTER,	// 해당 스킬 레벨로의 경험이 증가. <MASTER>.
	LOGCOMMAND_INDEX_SKILL_INCREASE_SKILL_WEAPON,	// 홍길동으로부터 스킬을 배울 경우 기록됨.
	LOGCOMMAND_INDEX_SKILL_CHANGE					// 캐릭터의 스킬증가와 감소
};

enum	// LOGCOMMAND_TYPE_STRUCTURE
{
	LOGCOMMAND_INDEX_STRUCTURE_PAY_FEE = 1,				//1 각각의 건물의 수수료 납부를 요청.
	LOGCOMMAND_INDEX_STRUCTURE_CHANGE_STRUCTURE_MONEY,	//2 각각의 건물의 건물의 보유 자금을 증가 시키거나 감소.
	LOGCOMMAND_INDEX_STRUCTURE_BUILD_STRUCTURE,			//3 건물을 건설.
	LOGCOMMAND_INDEX_STRUCTURE_DESTROY,					//4 건물 제거
	LOGCOMMAND_INDEX_STRUCTURE_SET_REPAIR_ITEM,			//5 사용안함.	
	LOGCOMMAND_INDEX_STRUCTURE_SET_REPAIR_AMOUNT,		//6 건물의 수리량. 사용안함.
	LOGCOMMAND_INDEX_STRUCTURE_SET_STRDUR,				//7 건물의 내구도.
	LOGCOMMAND_INDEX_STRUCTURE_CHANGE_STRDUR,			//8 건물의 내구도 변경으로 건물해체. 사용안함.
	LOGCOMMAND_INDEX_STRUCTURE_REPAIR,					//9 건물 수리. 
	LOGCOMMAND_INDEX_STRUCTURE_BASE_MONEY_CHANGE,		//10 건물의 자본금(수리시 필요한 돈)을 변화한다. 사용안함.
};

enum	// LOGCOMMAND_TYPE_SUMMON_HERO_MARKET,
{
	LOGCOMMAND_INDEX_SUMMON_HERO_MARKET_SELL_ORDER = 1,			// 소환 영웅 주문, 사용안함
	LOGCOMMAND_INDEX_SUMMON_HERO_MARKET_SELL_ORDER_CANCEL,		// 소환 영웅 주문 취소
	LOGCOMMAND_INDEX_SUMMON_HERO_MARKET_BUY,					// 소환영웅 구입.	
	LOGCOMMAND_INDEX_SUMMON_HERO_MARKET_PRICE_REDUCE,			// 소환영웅 주문 가격을 낮춤
};

enum	// LOGCOMMAND_TYPE_SUMMON_MARKET
{
	LOGCOMMAND_INDEX_SUMMON_MARKET_SELL_ORDER = 1,				// 소환수 판매 등록. 사용안함
	LOGCOMMAND_INDEX_SUMMON_MARKET_SELL_ORDER_CANCEL,			// 소환수 판매 등록. 취소
	LOGCOMMAND_INDEX_SUMMON_MARKET_BUY,							// 소환수 구매.
	LOGCOMMAND_INDEX_SUMMON_MARKET_PRICE_REDUCE,				// 등록된 소환수 가격 변동.
};

enum	// LOGCOMMAND_TYPE_SYSTEM
{
	LOGCOMMAND_INDEX_SYSTEM_GIVE_ITEM = 1,						// 시스템에서 아이템 주기.(RESPONSE 가 없어서 REQUEST에 작성)
	LOGCOMMAND_INDEX_SYSTEM_USER_INFO_GET,						// 사용자 캐릭터 정보 요청. (확인필요 : 정보가 부족할듯.)
	LOGCOMMAND_INDEX_SYSTEM_USER_ITEM_BUY,						// 시스템에서 유저가 시장에 올려 놓은 아이템을 사간다.
};

enum	// LOGCOMMAND_TYPE_TAX
{
	LOGCOMMAND_INDEX_TAX_PAY = 1,								// 세금 납부.
};

enum	// LOGCOMMAND_TYPE_TRADE_SERVER
{
	LOGCOMMAND_INDEX_TRADE_SERVER_SELL_ORDER = 1,				// 현재 무역 서버와의 판매 등록.
	LOGCOMMAND_INDEX_TRADE_SERVER_CANCEL_SELL,					// 현재 무역 서버와의 판매 등록 취소.
	LOGCOMMAND_INDEX_TRADE_SERVER_BUY,							// 현재 무역 서버와의 구매.	
	LOGCOMMAND_INDEX_TRADE_SERVER_SELLED,						// 현재 무역 서버와의 판매.	
	LOGCOMMAND_INDEX_TRADE_WITHDRAW_ACU,						// 현재 무역서버에 저장된 아큐 받기
};

enum	// LOGCOMMAND_TYPE_VILLAGE
{
	LOGCOMMAND_INDEX_VILLAGE_END_VILLAGE_WAR = 1,		// 사용안함.
	LOGCOMMAND_INDEX_VILLAGE_DECLARE_WAR,				// 마을 전쟁 선포.
	LOGCOMMAND_INDEX_VILLAGE_DECLARE_WAR_CANCEL,		// 마을 전쟁 선포 취소.
	LOGCOMMAND_INDEX_VILLAGE_SYMBOL_SET,				// 마을 수호신.(잦은 메시지 전달로 일단 주석처리함.)
	LOGCOMMAND_INDEX_VILLAGE_SYMBOL_STATUS_SET,			// 성황신 설정.
	LOGCOMMAND_INDEX_VILLAGE_CASTLE_SET,				// 마을밖 성벽의 상태가 변경될 때. 사용안함.
	LOGCOMMAND_INDEX_VILLAGE_CASTLE_STATUS_SET,			// 성벽 업그레이드시 관청 건물과 연결되어 변경되는 값이 저장.
	LOGCOMMAND_INDEX_VILLAGE_LEVEL_SET,					// 마을 레벨.
	LOGCOMMAND_INDEX_VILLAGE_MARK_SET,					// 마을 마크 설정.
	LOGCOMMAND_INDEX_VILLAGE_MAP_CHANGE,				// 마을 지도 변경.
	LOGCOMMAND_INDEX_VILLAGE_EVENT_SUCCESS,				// 마을 이벤트 성공. 사용안함.
	LOGCOMMAND_INDEX_VILLAGE_WAR_KILL_NUMBER,			// 사용안함
	LOGCOMMAND_INDEX_VILLAGE_JOIN_PLAY_TIME,			// 유저의 마을 가입 후 플레이 시간.
	LOGCOMMAND_INDEX_VILLAGE_JOIN_LEVEL_UP,				// 마을이 있는경우 레벨업 정보.
	LOGCOMMAND_INDEX_VILLAGE_JOIN_WAR_KILL_NUMBER,		// 사용안함.
	LOGCOMMAND_INDEX_VILLAGE_JOIN_MAKE_RARE_ITEM,		// 명품 제조. 사용안함.	
	LOGCOMMAND_INDEX_VILLAGE_JOIN_MAKE_ITEM_SKILL_EXP,	// 마을이 있는경우 아이템 만든 스킬 정보.
	LOGCOMMAND_INDEX_VILLAGE_RESULT,					// 마을 전쟁이 끝난 결과.
	LOGCOMMAND_INDEX_VILLAGE_EVENT_INSERTMATERIAL,		// 마을 전쟁이 끝난 결과.
};

enum	// LOGCOMMAND_TYPE_WORLD_MONEY
{
	LOGCOMMAND_INDEX_WORLD_MONEY_DISTRIBUTION = 1,		// 아큐 공모
	LOGCOMMAND_INDEX_WORLD_MONEY_SELL_ORDER,			// 아큐 판매 등록
	LOGCOMMAND_INDEX_WORLD_MONEY_CANCEL_ORDER,			// 아큐 판매 등록 취소
	LOGCOMMAND_INDEX_WORLD_MONEY_BUY,					// 아큐 구입
	LOGCOMMAND_INDEX_WORLD_MONEY_AVERAGE_PRICE,			// 아큐 평균 가격.
	LOGCOMMAND_INDEX_WORLD_MONEY_REDUCE_PRICE,			// 아큐의 가격을 떨군다. 사용안함
	LOGCOMMAND_INDEX_WORLD_MONEY_ADD,					// 아큐 추가.
};

enum	// LOGCOMMAND_TYPE_SELL_TO_FOREIGN_MERCHANT - 사용안함
{ 
	LOGCOMMAND_INDEX_SELL_TO_FOREIGN_MERCHANT_RARELEVEL_1 = 1,		// 호품등급. 사용안함
	LOGCOMMAND_INDEX_SELL_TO_FOREIGN_MERCHANT_RARELEVEL_2,			// 명품등급. 사용안함
	LOGCOMMAND_INDEX_SELL_TO_FOREIGN_MERCHANT_RARELEVEL_3,			// 사용안함
	LOGCOMMAND_INDEX_SELL_TO_FOREIGN_MERCHANT_RARELEVEL_4,			// 사용안함		
	LOGCOMMAND_INDEX_SELL_TO_FOREIGN_MERCHANT_RARELEVEL_5,			// 고급품등급.	사용안함.
	LOGCOMMAND_INDEX_SELL_TO_FOREIGN_MERCHANT_RARELEVEL_6,			// 일반등급.(고물품 포함.), 사용안함
};

enum	// LOGCOMMAND_TYPE_ARTIFACT
{ 
	LOGCOMMAND_INDEX_ARTIFACT_MIXTURE		= 1,
	LOGCOMMAND_INDEX_ARTIFACT_SLOT_CREATE,
	LOGCOMMAND_INDEX_ARTIFACT_REMOVE,
	LOGCOMMAND_INDEX_ARTIFACT_RESTORE,		// 사용안함
};

enum	// LOGCOMMAND_TYPE_ATTEND
{
	LOGCOMMAND_INDEX_ATTEND_CHANGE	= 1,							// 출석 도장을 찍는다
	LOGCOMMAND_INDEX_ATTEND_FAIL,									// 출석 도장 찍기 실패, 사용안함
	LOGCOMMAND_INDEX_ATTEND_REWARD_SUCCESS,							// 출석 보상 아이템을 주다
	LOGCOMMAND_INDEX_ATTEND_REWARD_FAIL,							// 출석 보상 아이템을 주기 실패

};

enum	// LOGCOMMAND_TYPE_SPACEBOX
{
	LOGCOMMAND_INDEX_TO_SPACEBOX	= 1,			// 공간상자에 저장.
	LOGCOMMAND_INDEX_TO_TREASUREBOX,				// 보물상자에 저장. - 사용안함
	LOGCOMMAND_INDEX_SPACEBOX_TO_INVENTORY,			// 공간상자 아이템을 내 인벤토리로 꺼내기.
	LOGCOMMAND_INDEX_TREASUREBOX_TO_INVENTORY, // 사용안함	// 보물상자 아이템을 내 인벤토리로 꺼내기. - 사용안함
	LOGCOMMAND_INDEX_SPACEBOX, // 사용안함			// 출석 보상 아이템을 주기 실패

};

enum	// LOGCOMMAND_TYPE_SERVER_EVENT
{
	LOGCOMMAND_INDEX_SERVER_EVENT_TOTAL_RANK	= 1,		// 서버 전체 순위 랭킹.
	LOGCOMMAND_INDEX_SERVER_EVENT_TOTAL_SCORE,				// 서버 전체 순위 추가 점수.
	LOGCOMMAND_INDEX_SERVER_EVENT_DAILY_RANK,				// 서버 하루 순위 랭킹 1등하면 버프 적용.
	LOGCOMMAND_INDEX_SERVER_EVENT_DAILY_SCORE,				// 서버 하루 순위 추가 점수. 인던 단계가 같으면 추가 점수. 
	LOGCOMMAND_INDEX_SERVER_EVENT_DAILY_BUF,				// 서버 하루 버프.
	LOGCOMMAND_INDEX_SERVER_EVENT_DAILY_BONUS_ITEM,			// 인던 종료시 단계 조합으로 얻는 아이템 정보.
	LOGCOMMAND_INDEX_SERVER_EVENT_PREMIUM_GINSENG,			// 백년삼
};

enum	// LOGCOMMAND_TYPE_WORLD_PASSPORT
{
	LOGCOMMAND_INDEX_WORLD_PASSPORT_SET		= 1,			// 여권 발급
	LOGCOMMAND_INDEX_WORLD_PASSPORT_EXTEND					// 여권 연장
};

enum	// LOGCOMMAND_TYPE_BLACKARMY
{
	LOGCOMMAND_INDEX_BLACKARMY_APPLY,		// 참가신청
	LOGCOMMAND_INDEX_BLACKARMY_APPLYMAP,	// 맵에 할당 받음
	LOGCOMMAND_INDEX_BLACKARMY_START,		// 전쟁 시작
	LOGCOMMAND_INDEX_BLACKARMY_BOSS,		// 보스소환됨
	LOGCOMMAND_INDEX_BLACKARMY_END,			// 전쟁 끝
};

enum	//LOGCOMMAND_TYPE_PERSONALPVP	// 개인간 PVP
{
	LOGCOMMAND_INDEX_PERSONALPVP_REQUEST = 1	,		// 개인간 PVP 신청
	LOGCOMMAND_INDEX_PERSONALPVP_START		,			// 개인간 PVP 시작
	LOGCOMMAND_INDEX_PERSONALPVP_END_WARP	,			// 개인간 PVP 끝(워프)
	LOGCOMMAND_INDEX_PERSONALPVP_END_LOGOUT	,			// 개인간 PVP 끝(로그아웃)
	LOGCOMMAND_INDEX_PERSONALPVP_END_DIE	,			// 개인간 PVP 끝(하나죽음)
	LOGCOMMAND_INDEX_PERSONALPVP_DRAW		,			// 개인간 PVP 비김 (사용안함)
	LOGCOMMAND_INDEX_PERSONALPVP_REFUSE				// 개인간 pvp 상대가 거절 상태 (사용안함)
};

enum	//LOGCOMMAND_TYPE_PERSONALPVP_LEAGUE	// PVP리그
{
	LOGCOMMAND_INDEX_PVP_LEAGUE_RESERVE = 1,	// PVP리그	신청
	LOGCOMMAND_INDEX_PVP_LEAGUE_MATCHING,		// PVP리그	매칭되서 싸우게 된 사람들
	LOGCOMMAND_INDEX_PVP_LEAGUE_RESULT,		// PVP리그	결과
	LOGCOMMAND_INDEX_PVP_LEAGUE_RESULT_DRAW,		// PVP리그	결과 비김
	LOGCOMMAND_INDEX_PVP_LEAGUE_GIFT,		// PVP리그	받은 아이템
	LOGCOMMAND_INDEX_PVP_LEAGUE_GOAL,		// PVP리그	목표달성
	LOGCOMMAND_INDEX_PVP_LEAGUE_GRADE_UP,		// PVP리그	등급업
	LOGCOMMAND_INDEX_PVP_LEAGUE_GRADE_DOWN	// PVP리그	등급다운	
};

enum    // LOGCOMMAND_TYPE_NEWMARKET
{
	LOGCOMMAND_INDEX_NEWMARKET_ORDER = 1,		// 물품등록.
	LOGCOMMAND_INDEX_NEWMARKET_GETITEMFROM,		// 물품회수.
	LOGCOMMAND_INDEX_NEWMARKET_SELL,			// 물품판매.
	LOGCOMMAND_INDEX_NEWMARKET_BUY,				// 물품구매.
	LOGCOMMAND_INDEX_NEWMARKET_REDUCEPRICE,		// 등록 물품 가격 하락.
};

enum // LOGCOMMAND_TYPE_FAMILY 가족관련
{
	LOGCOMMAND_INDEX_FAMILY_PROPOSE = 1,		// 프로포즈
	LOGCOMMAND_INDEX_FAMILY_PROPOSE_FAIL,		// 프로포즈 실패
	LOGCOMMAND_INDEX_FAMILY_MARRY,				// 결혼
	LOGCOMMAND_INDEX_FAMILY_RESERVE_WEDDING		// 결혼식 예약
};

enum // LOGCOMMAND_TYPE_BALANCECURRENCY 통화량 흡수정책 관련
{
	LOGCOMMAND_INDEX_BALANCECURRENCY = 1,		// 프로포즈
};

enum	//LOGCOMMAND_TYPE_RACCOONDODGE_EVENT	// 라쿤 피하기 이벤트
{
	LOGCOMMAND_INDEX_PVP_RACCOONDODGE_EVENT_RESERVE = 1,	// 라쿤 피하기 이벤트 신청 
	LOGCOMMAND_INDEX_PVP_RACCOONDODGE_EVENT_FAIL,		// 중간에 실패해서 튕기질러 나갔다.
	LOGCOMMAND_INDEX_PVP_RACCOONDODGE_EVENT_REWARD,		// 끝까지 버텨서 리워드를 받았다
};

enum	//LOGCOMMAND_TYPE_GAWIBAWIBO		// 가위바위보
{
	LOGCOMMAND_INDEX_GAWIBAWIBO_DEL_MONEY = 1,	// 플레이어가 가위바위보에 지출한 금액
	LOGCOMMAND_INDEX_GAWIBAWIBO_ADD_MONEY,		// 플레이어가 벌어들인 금액
};

enum	// LOGCOMMAND_TYPE_BOKBULBOK
{
	LOGCOMMAND_INDEX_BOKBULBOK_PAID = 1,		// 플레이어가 입장료로 지불한 금액
	LOGCOMMAND_INDEX_BOKBULBOK_REWARD_MONEY,	// 플레이어가 보상으로 받은 금액
	LOGCOMMAND_INDEX_BOKBULBOK_CLEAR_FAIL		// 클리어 실패
};

enum // LOGCOMMAND_TYPE_DORMANCY
{
	LOGCOMMAND_INDEX_DORMANCY_INCREASE_POINT = 1,	// 휴면 포인트가 올라 갈때
	LOGCOMMAND_INDEX_DORMANCY_BUY_ITEM,				// 휴면 포인트로 아이템을 살 때
	LOGCOMMAND_INDEX_DORMANCY_END					// 휴면 계정 종료
};

enum	// LOGCOMMAND_TYPE_REWARD
{
	LOGCOMMAND_INDEX_REWARD_TINTIN = 1,				// 팅팅한테 아이템 받아 갈 떄
};

enum	// LOGCOMMAND_TYPE_BATTLEROYAL
{
	LOGCOMMAND_INDEX_BATTLEROYAL_WINNER = 1,		// 승자 정보
	LOGCOMMAND_INDEX_BATTLEROYAL_GAMERCOUNT = 2		// 참여 유저 수
};

enum	//LOGCOMMAND_TYPE_COMMISSION,		// 65 의뢰
{
	LOGCOMMAND_INDEX_COMMISSION_START = 1,		// 의뢰 시작
	LOGCOMMAND_INDEX_COMMISSION_END ,		// 의뢰 종료
	LOGCOMMAND_INDEX_COMMISSION_CLIENT ,		// 제조 의뢰
	LOGCOMMAND_INDEX_COMMISSION_MAKER 		// 제작 의뢰
};

// <- [로그추가 : 황진성 2007.9.3]
//------------------------------------------------------------------------------------//


class cGameDB : public ITZPerson
{
public:
	cGameDB() {};
	~cGameDB() {};
};


class GameDBProcess
{
private:

public:
	GameDBProcess();
	~GameDBProcess();

public:
	void			Init( TCHAR *ip, UI16 usPort );
	void			Run();

	bool			SendMsg(sPacketHeader *pPacket);
	bool			SendMsg( SI32 siSelect, sPacketHeader *pPacket );

	BOOL			IsEstablished();

	SI32			m_siWorkSlot;

private:
	ITZSessionFactory< cGameDB >	m_sf;										// 세션 팩토리
	ITZSessionManager				m_sm;										// 세션 매니저
	ITZNetIOCP						m_iocp;										// IOCP 

	ITZSession*						m_pGameDBSession[ DBCONNECTION_NUMBER ];	// 게임 DB매니저 세션 포인터

	TCHAR							m_gameDBManagerIP[ 20 ];					// 게임 DB매니저 IP
	UI16							m_gameDBManagerPort;						// 게임 DB매니저 PORT
	
public:	
	BOOL							m_bPing[ DBCONNECTION_NUMBER ];
	DWORD							m_dwPingTick[ DBCONNECTION_NUMBER ];
	DWORD							m_dwDBLatency[ DBCONNECTION_NUMBER ];		// DB응답시간
	
	DWORD							m_dwTick;
	
	DWORD							m_dwCurrentDBLatency;
};

#endif

