//=============================================================================
//
//	NLogClientProcessDefines.h
//
//	Copyright 2007 HQGame
//
//=============================================================================
#ifndef _NNEWLOGCLIENTPROCESSDEFINES_H_
#define _NNEWLOGCLIENTPROCESSDEFINES_H_

#define MAX_NEWLOGCLIENT_PACKET_SIZE	5000
#define MAX_NEWLOGCLIENT_PACKET_COUNT	1000

#define MAX_NEWLOGCLIENT_CHANNEL		1

#define MAX_CONNECTING_TIME			20 * 1000	// 20√ 

enum
{
	NEWLOGCLIENTPROCESS_STATE_IDLE,
	NEWLOGCLIENTPROCESS_STATE_REQUESTCONNECTING,
	NEWLOGCLIENTPROCESS_STATE_CONNECTING,
	NEWLOGCLIENTPROCESS_STATE_ESTABLISH,
	NEWLOGCLIENTPROCESS_STATE_WAITLOG,
	NEWLOGCLIENTPROCESS_STATE_FINISHLOG,
	NEWLOGCLIENTPROCESS_STATE_WRONGID,
	NEWLOGCLIENTPROCESS_STATE_WRONGPASS,
	NEWLOGCLIENTPROCESS_STATE_DONOTINPUTID,
};

#endif
