//---------------------------------
// 2003/6/11 김태곤
//---------------------------------
#include <CommonLogic.h>
#include "AttackType.h"

#include "..\..\Common\Bullet\Bullet.h"
//----------------------------------------------
// cltAttackTargetList
//----------------------------------------------
cltAttackTargetList::cltAttackTargetList()
{
	siIndex = 0;
}


BOOL cltAttackTargetList::IsInList(SI32 id)
{
	SHORT i;

	for(i = 0;i < siIndex;i++)
	{
		if(siID[i]==id)return TRUE;
	}

	return FALSE;
}


void cltAttackTargetList::Push(SI32 id, cltAttackDamageInfo* pcldamageinfo)
{
	if(siIndex >= MAX_ATTACK_TARGET_LIST_NUMBER)return ;

	siID[siIndex]		=	id;
	clDamageInfo[siIndex].Set(pcldamageinfo);
	siIndex++;
}

BOOL cltAttackTargetList::Pop(SI32* pid, cltAttackDamageInfo* pcldamageinfo)
{
	SI32 i;
	if(siIndex == 0)return FALSE;

	*pid	= siID[0];
	pcldamageinfo->Set(&clDamageInfo[0]);

	for(i = 1;i < siIndex;i++)
	{
		siID[i-1]		= siID[i];
		clDamageInfo[i-1].Set( &clDamageInfo[i]);
	}

	siIndex --;

	return TRUE;
}


//---------------------------------------
// cltAttackTypeInfo
//---------------------------------------
cltAttackTypeInfo::cltAttackTypeInfo(TCHAR* szattacktypecode, SI32 attacktype, SI32 bulletunique,
									 SI32 flag1, SI32 flag2, SI32 flag3)
{
	StringCchCopy(szAttackTypeCode, 60, szattacktypecode);

	siAttackType	= attacktype;
	siBulletUnique	= bulletunique;
	siFlag1			= flag1;
	siFlag2			= flag2;
	siFlag3			= flag3;
}


cltAttackTypeInfo::~cltAttackTypeInfo()
{
}


//---------------------------------------
// cltAttackTypeInfoManager
//---------------------------------------
cltAttackTypeInfoManager::cltAttackTypeInfoManager()
{
	SI32 i;

	for(i = 0;i < MAX_ATTACKTYPE_NUMBER;i++)
	{
		pclAttackTypeInfo[i] = NULL;
	}

	Add(ATTACKTYPE_HAND, 			TEXT("ATTACKTYPE_HAND"),				BULLETKIND_NONE,				ATTACKTYPE_ATB_RANGE1,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_CRITICAL) ;
	Add(ATTACKTYPE_SWORD, 			TEXT("ATTACKTYPE_SWORD"),				BULLETKIND_NONE,				ATTACKTYPE_ATB_RANGE1,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_CRITICAL) ;
	Add(ATTACKTYPE_SPEAR,		 	TEXT("ATTACKTYPE_SPEAR"),				BULLETKIND_NONE,				ATTACKTYPE_ATB_RANGE1,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_CRITICAL) ;
	Add(ATTACKTYPE_AXE, 			TEXT("ATTACKTYPE_AXE"),					BULLETKIND_NONE,				ATTACKTYPE_ATB_RANGE1,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_CRITICAL) ;

	Add(ATTACKTYPE_STAFF,		 	TEXT("ATTACKTYPE_STAFF"),				BULLETKIND_NONE,				ATTACKTYPE_ATB_RANGE1,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_CRITICAL) ;
	Add(ATTACKTYPE_BOW,				TEXT("ATTACKTYPE_BOW"),					BULLETKIND_ARROW,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_GUN,				TEXT("ATTACKTYPE_GUN"),					BULLETKIND_GUN,					ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_CAKE,			TEXT("ATTACKTYPE_CAKE"),				BULLETKIND_CAKE,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_EGG,				TEXT("ATTACKTYPE_EGG"),					BULLETKIND_EGG,					ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_CANNON,			TEXT("ATTACKTYPE_CANNON"),				BULLETKIND_CANNONBALL,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_SHELL,			TEXT("ATTACKTYPE_SHELL"),				BULLETKIND_TURTLEBACKSHELL,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_CATFISH,			TEXT("ATTACKTYPE_CATFISH"),				BULLETKIND_CATFISH,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_LADYBUGFAN,		TEXT("ATTACKTYPE_LADYBUGFAN"),			BULLETKIND_LADYBUGFAN,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_SNOW,			TEXT("ATTACKTYPE_SNOW"),				BULLETKIND_SNOW,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);

	Add(ATTACKTYPE_STAFF1,			TEXT("ATTACKTYPE_STAFF1"),				BULLETKIND_STAFF1,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, /*ATTACKTYPE_ATB_MINRANGE*/0);			

	Add(ATTACKTYPE_SELFBOMB,	 	TEXT("ATTACKTYPE_SELFBOMB"),			BULLETKIND_NONE,				ATTACKTYPE_ATB_RANGE1,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_CRITICAL) ;
	Add(ATTACKTYPE_MADOGHOSTFIRE,	TEXT("ATTACKTYPE_MADOGHOSTFIRE"),		BULLETKIND_MADOGHOSTFIRE,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_JAPANHEADER,		TEXT("ATTACKTYPE_JAPANHEADER"),			BULLETKIND_JAPANHEADER,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_TOHANG,			TEXT("ATTACKTYPE_TOHANG"),				BULLETKIND_TOHANG,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);	
	Add(ATTACKTYPE_MAGIC, 			TEXT("ATTACKTYPE_MAGIC"),				BULLETKIND_NONE,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_CRITICAL) ;
	Add(ATTACKTYPE_POISONSTATUS,	TEXT("ATTACKTYPE_POISONSTATUS"),		BULLETKIND_NONE,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	0);	
	Add(ATTACKTYPE_SKULLBATFIRE,	TEXT("ATTACKTYPE_SKULLBATFIRE"),		BULLETKIND_SKULLBATFIRE,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_FIREGOBLIN,		TEXT("ATTACKTYPE_FIREGOBLIN"),			BULLETKIND_FIREGOBLIN,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_CASTLECANNON,	TEXT("ATTACKTYPE_CASTLECANNON"),		BULLETKIND_CASTLECANNONBALL,	ATTACKTYPE_ATB_RANGE3,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE);

	Add(ATTACKTYPE_POISON,			TEXT("ATTACKTYPE_POISON"),				BULLETKIND_MAGICPOISON,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);	
	Add(ATTACKTYPE_ICE,				TEXT("ATTACKTYPE_ICE"),					BULLETKIND_MAGICICE,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_KNIFE,			TEXT("ATTACKTYPE_KNIFE"),				BULLETKIND_KNIFE,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_GREENFIRE,		TEXT("ATTACKTYPE_GREENFIRE"),			BULLETKIND_GREENFIRE,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_BLACKINK,		TEXT("ATTACKTYPE_BLACKINK"),			BULLETKIND_BLACKINK,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_BOOMERANG,		TEXT("ATTACKTYPE_BOOMERANG"),			BULLETKIND_BOOMERANG,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_WINDBLADE,		TEXT("ATTACKTYPE_WINDBLADE"),			BULLETKIND_WINDBLADE,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_SHELLFISHBOMB,	TEXT("ATTACKTYPE_SHELLFISHBOMB"),		BULLETKIND_SHELLFISHBOMB,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_TREEMON,			TEXT("ATTACKTYPE_TREEMON"),				BULLETKIND_TREEMON,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_VINE,			TEXT("ATTACKTYPE_VINE"),				BULLETKIND_VINE,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_GHOSTFIRE,		TEXT("ATTACKTYPE_GHOSTFIRE"),			BULLETKIND_GHOSTFIRE,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_SIMTORYONG,		TEXT("ATTACKTYPE_SIMTORYONG"),			BULLETKIND_SIMTORYONG,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_KINGCUTTLEFISH,	TEXT("ATTACKTYPE_KINGCUTTLEFISH"),		BULLETKIND_KINGCUTTLEFISH,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_CRANE,			TEXT("ATTACKTYPE_CRANE"),				BULLETKIND_CRANE,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_MONKEY,			TEXT("ATTACKTYPE_MONKEY"),				BULLETKIND_MONKEYDRILL,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);

	Add(ATTACKTYPE_CURSEDEFENSE,	TEXT("ATTACKTYPE_CURSEDEFENSE"),		BULLETKIND_NONE,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_CURSEMOVESPEED,	TEXT("ATTACKTYPE_CURSEMOVESPEED"),		BULLETKIND_MONKEYDRILL,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_BUTCHER,			TEXT("ATTACKTYPE_BUTCHER"),				BULLETKIND_BUTCHER,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	Add(ATTACKTYPE_STONEOLDMAN,		TEXT("ATTACKTYPE_STONEOLDMAN"),			BULLETKIND_STONEOLDMAN,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_KINGCRAB,		TEXT("ATTACKTYPE_KINGCRAB"),			BULLETKIND_KINGCRAB,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	
	Add(ATTACKTYPE_FIREARROW,		TEXT("ATTACKTYPE_FIREARROW"),			BULLETKIND_FIREARROW,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_LOBSTER,			TEXT("ATTACKTYPE_LOBSTER"),				BULLETKIND_LOBSTER,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE);
	
	Add(ATTACKTYPE_DEADMESSENGER,	TEXT("ATTACKTYPE_DEADMESSENGER"),		BULLETKIND_DEADMESSENGER,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_MASKMONK,		TEXT("ATTACKTYPE_MASKMONK"),			BULLETKIND_MASKMONK,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_PERSONCANNON,	TEXT("ATTACKTYPE_PERSONCANNON"),		BULLETKIND_PERSONCANNON,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_CANNON_MAGIC,	TEXT("ATTACKTYPE_CANNON_MAGIC"),		BULLETKIND_CANNON_MAGIC,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_HEROSWORD, 		TEXT("ATTACKTYPE_HEROSWORD"),			BULLETKIND_NONE,				ATTACKTYPE_ATB_RANGE1,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_CRITICAL) ;

	Add(ATTACKTYPE_STAFF2,			TEXT("ATTACKTYPE_STAFF2"),				BULLETKIND_STAFF_SCROLL,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, /*ATTACKTYPE_ATB_MINRANGE*/0);
	Add(ATTACKTYPE_BOW1,			TEXT("ATTACKTYPE_BOW1"),				BULLETKIND_BOW_SCROLL,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_GUN1,			TEXT("ATTACKTYPE_GUN1"),				BULLETKIND_GUN_SCROLL,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_FOAM,			TEXT("ATTACKTYPE_FOAM"),				BULLETKIND_FOAM_FIRE,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_FIREBALL,		TEXT("ATTACKTYPE_FIREBALL"),			BULLETKIND_FIREBALL,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_MORTAL, 			TEXT("ATTACKTYPE_MORTAL"),				BULLETKIND_MORTAL,				ATTACKTYPE_ATB_RANGE1,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_CRITICAL) ;

	Add(ATTACKTYPE_WATERARROW,		TEXT("ATTACKTYPE_WATERARROW"),			BULLETKIND_WATERARROW,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_STAFFWIND,		TEXT("ATTACKTYPE_STAFFWIND"),			BULLETKIND_STAFFWIND,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_FLYVINE,			TEXT("ATTACKTYPE_FLYVINE"),				BULLETKIND_FLYVINE,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_MAGICFIRESTATUS,	TEXT("ATTACKTYPE_MAGICFIRESTATUS"),		BULLETKIND_NONE,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, 0);	
	Add(ATTACKTYPE_MAGICFIREBURN,	TEXT("ATTACKTYPE_MAGICFIREBURN"),		BULLETKIND_NONE,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);	

	Add(ATTACKTYPE_SKELLFISH,		TEXT("ATTACKTYPE_SKELLFISH"),			BULLETKIND_SKELLFISH,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_FROZEN,			TEXT("ATTACKTYPE_FROZEN"),				BULLETKIND_MAGICFROZEN,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_ICESTONE,		TEXT("ATTACKTYPE_ICESTONE"),			BULLETKIND_ICESTONE,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_NEW_STAFF2,		TEXT("ATTACKTYPE_NEW_STAFF2"),			BULLETKIND_NEW_STAFF_SCROLL,	ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, /*ATTACKTYPE_ATB_MINRANGE*/0);
	Add(ATTACKTYPE_NEW_BOW1,		TEXT("ATTACKTYPE_NEW_BOW1"),			BULLETKIND_NEW_BOW_SCROLL,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_NEW_GUN1,		TEXT("ATTACKTYPE_NEW_GUN1"),			BULLETKIND_NEW_GUN_SCROLL,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_ENERGYARROW,		TEXT("ATTACKTYPE_ENERGYARROW"),			BULLETKIND_ENERGYARROW,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_SPEAR_MANA,		TEXT("ATTACKTYPE_SPEAR_MANA"),			BULLETKIND_SPEAR_MANA,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_BLACKBOSS,		TEXT("ATTACKTYPE_BLACKBOSS"),			BULLETKIND_BLACKBOSS,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_OCTOPUS,			TEXT("ATTACKTYPE_OCTOPUS"),				BULLETKIND_OCTOPUS,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_OTOHIME,			TEXT("ATTACKTYPE_OTOHIME"),				BULLETKIND_OTOHIME,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	Add(ATTACKTYPE_BLACKSPIDER,		TEXT("ATTACKTYPE_BLACKSPIDER"),			BULLETKIND_BLACKSPIDER,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_EVILEYE,			TEXT("ATTACKTYPE_EVILEYE"),				BULLETKIND_EVILEYE,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_FROZENSORCERER,	TEXT("ATTACKTYPE_FROZENSORCERER"),		BULLETKIND_FROZENSORCERER,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_CANNONMOL,		TEXT("ATTACKTYPE_CANNONMOL"),			BULLETKIND_CANNONMOL,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_PRIEST,			TEXT("ATTACKTYPE_PRIEST"),				BULLETKIND_PRIEST,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_MINEGIRL,		TEXT("ATTACKTYPE_MINEGIRL"),			BULLETKIND_MINEGIRL,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL); 
	Add(ATTACKTYPE_GREENTURTLE,		TEXT("ATTACKTYPE_GREENTURTLE"),			BULLETKIND_GREENTURTLE,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_MAGICALRACCOON,	TEXT("ATTACKTYPE_MAGICALRACCOON"),		BULLETKIND_MAGICALRACCOON,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_MAGIC,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_MAMARACCOON,		TEXT("ATTACKTYPE_MAMARACCOON"),			BULLETKIND_MAMARACCOON,			ATTACKTYPE_ATB_RANGE3,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_RACCOONTOWER,	TEXT("ATTACKTYPE_RACCOONTOWER"),		BULLETKIND_RACCOONTOWER,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_MAGIC,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_CHICKENBIG,		TEXT("ATTACKTYPE_CHICKENBIG"),			BULLETKIND_CHICKENBIG,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_MAGIC,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_MOONBLADE,		TEXT("ATTACKTYPE_MOONBLADE"),			BULLETKIND_MOONBLADE,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_EMPERORARCHER,	TEXT("ATTACKTYPE_EMPERORARCHER"),		BULLETKIND_EMPERORARCHER,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_NINJAMAN,		TEXT("ATTACKTYPE_NINJAMAN"),			BULLETKIND_NINJAMAN,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_PIRATEARCHER,	TEXT("ATTACKTYPE_PIRATEARCHER"),		BULLETKIND_PIRATEARCHER,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_EMPERORMASTER,	TEXT("ATTACKTYPE_EMPERORMASTER"),		BULLETKIND_EMPERORMASTER,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_GREATWALLSOLDIER,TEXT("ATTACKTYPE_GREATWALLSOLDIER"),	BULLETKIND_GREATWALLSOLDIER,	ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_GREATWALLMAGICIAN,TEXT("ATTACKTYPE_GREATWALLMAGICIAN"),	BULLETKIND_GREATWALLMAGICIAN,	ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_CATRANGE,		TEXT("ATTACKTYPE_CATRANGE"),			BULLETKIND_CATRANGE,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_GREATWALLSPIDER, TEXT("ATTACKTYPE_GREATWALLSPIDER"),		BULLETKIND_GREATWALLSPIDER,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_BEARTANG,		TEXT("ATTACKTYPE_BEARTANG"),			BULLETKIND_BEARTANG,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_SUPERBEARTANG,	TEXT("ATTACKTYPE_SUPERBEARTANG"),		BULLETKIND_SUPERBEARTANG,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_HALLOWEENGHOST,	TEXT("ATTACKTYPE_HALLOWEENGHOST"),		BULLETKIND_HALLOWEENGHOST,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);	
	Add(ATTACKTYPE_CHRISTMASRANGE,	TEXT("ATTACKTYPE_CHRISTMASRANGE"),		BULLETKIND_CHRISTMASRANGE,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_GREATWALLASURA,  TEXT("ATTACKTYPE_GREATWALLASURA"),		BULLETKIND_GREATWALLASURA,		ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	Add(ATTACKTYPE_FROZENQUEEN,		TEXT("ATTACKTYPE_FROZENQUEEN"),			BULLETKIND_ARROW,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS, ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL) ;
	Add(ATTACKTYPE_FIGHTINGMENRANGE,TEXT("ATTACKTYPE_FIGHTINGMENRANGE"),	BULLETKIND_FIGHTINGMENRANGE,	ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);

	// 요정스피릿(남) 블렛추가.
	Add(ATTACKTYPE_FAIRYRANGE,		TEXT("ATTACKTYPE_FAIRYRANGE"),			BULLETKIND_FAIRYRANGE,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	// 가챠 - 12월 스피릿 상자	눈의 여왕 사스콰치
	Add(ATTACKTYPE_SNOWQUEEN,		TEXT("ATTACKTYPE_SNOWQUEEN"),			BULLETKIND_SNOWQUEEN,			ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);
	// 안개미궁 - 어릿광대
	Add(ATTACKTYPE_CLOWN,			TEXT("ATTACKTYPE_CLOWN"),				BULLETKIND_CLOWN,				ATTACKTYPE_ATB_RANGE2,	ATTACKTYPE_ATB_PHYSICS,	ATTACKTYPE_ATB_MINRANGE|ATTACKTYPE_ATB_CRITICAL);	
}

cltAttackTypeInfoManager::~cltAttackTypeInfoManager()
{
	SI32 i;

	for(i = 0;i < MAX_ATTACKTYPE_NUMBER;i++)
	{
		if(pclAttackTypeInfo[i])
		{
			delete pclAttackTypeInfo[i];
			pclAttackTypeInfo[i] = NULL;
		}
	}

}

// 공격 타입을 추가한다. 
BOOL cltAttackTypeInfoManager::Add(SI32 attacktype, TCHAR* szattacktypecode,
								   SI32 bulletunique, SI32 flag1, SI32 flag2, SI32 flag3)
{
	if(pclAttackTypeInfo[attacktype])
	{
		MsgBox(TEXT("fd08724"), TEXT("D983:%d"), attacktype);
		return FALSE;
	}

	pclAttackTypeInfo[attacktype] = new cltAttackTypeInfo(szattacktypecode, attacktype,bulletunique,
														  flag1, flag2, flag3);

	return TRUE;
}

// 공격 타입의 총알 종류를 구한다.
SI32 cltAttackTypeInfoManager::GetBulletUnique(SI32 attacktype)
{
	if(attacktype <= 0)return 0;

	return pclAttackTypeInfo[attacktype]->siBulletUnique;

}

// Code를 근거로 AttackType을 찾는다.
SI32 cltAttackTypeInfoManager::FindAttackTypeFromCode(TCHAR* code)
{
	SI32 i;

	for(i = 0;i < MAX_ATTACKTYPE_NUMBER;i++)
	{
		if(pclAttackTypeInfo[i])
		{
			if(_tcscmp(pclAttackTypeInfo[i]->szAttackTypeCode, code) == 0)
			{
				return i;
			}
		}
	}

	return -1;
}

// 공격 타입의 속성을 확인한다. 
bool cltAttackTypeInfoManager::IsAtb(SI32 attacktype, SI32 atb)
{
	if(attacktype < 0 || attacktype >= MAX_ATTACKTYPE_NUMBER)return false;
	if(pclAttackTypeInfo[attacktype] == NULL)return false;

	if(pclAttackTypeInfo[attacktype]->siFlag3 & atb)return true;


	return false;
}
