//=============================================================================
//
//	NTradeClientProcessDefines.h
//
//	Copyright 2007 HQGame
//
//=============================================================================
#ifndef _NTRADELOGCLIENTPROCESSDEFINES_H_
#define _NTRADELOGCLIENTPROCESSDEFINES_H_

#define MAX_TRADELOGCLIENT_PACKET_SIZE	5000
#define MAX_TRADELOGCLIENT_PACKET_COUNT	1000

#define MAX_TRADELOGCLIENT_CHANNEL		1

#define MAX_TRADELOG_CONNECTING_TIME	20 * 1000	// 20√ 

enum
{
	TRADELOGCLIENTPROCESS_STATE_IDLE,
	TRADELOGCLIENTPROCESS_STATE_REQUESTCONNECTING,
	TRADELOGCLIENTPROCESS_STATE_CONNECTING,
	TRADELOGCLIENTPROCESS_STATE_ESTABLISH,
	TRADELOGCLIENTPROCESS_STATE_WAITLOG,
	TRADELOGCLIENTPROCESS_STATE_FINISHLOG,
	TRADELOGCLIENTPROCESS_STATE_WRONGID,
	TRADELOGCLIENTPROCESS_STATE_WRONGPASS,
	TRADELOGCLIENTPROCESS_STATE_DONOTINPUTID,
};

#endif
