#ifndef _PRIVATETRADEORDERBASEINFO_H_
#define _PRIVATETRADEORDERBASEINFO_H_

#define MAX_PRIVATETRADEORDER_ITEM_NUM			5			// 거래 가능한 최대 아이템 개수
#define MAX_PRIVATETRADEORDER_PRICE				1000000000	// 거래 가능한 최대 금액 : 10억
#define MAX_PRIVATETRADEORDER_STOCK_NUM			1000		// 최대 1000주 까지 동시에 거래가 가능하다.

#define MAX_PRIVATETRADEOBJ_NUM					200			// 최대 200개까지 동시에 거래가 가능하다.

//#define PRIVATETRADE_TRADE_MODE_REJECT_ACCEPT 0x999999		// 거래 수락 거부용 메시지

enum { PRIVATETRADE_TRADE_MODE, PRIVATETRADE_ENCHANT_MODE,PRIVATETRADE_TRADE_MODE_REJECT_ACCEPT,PRIVATETRADE_TRADE_MODE_ALREADYTRADE,PRIVATE_ENCHANT_MODE_AGREE_ACCEPT, PRIVATE_ENCHANT_MODE_REJECT_ACCEPT, PRIVATE_ENCHANT_MODE_ALREADYTRADE };

enum { PRIVATETRADE_TYPE_MONEY, PRIVATETRADE_TYPE_ITEM, PRIVATETRADE_TYPE_STOCK, PRIVATETRADE_TYPE_HOUSEUNIT, PRIVATETRADE_TYPE_HORSE, PRIVATETRADE_TYPE_END };

#endif