//---------------------------------
// 2003/6/2 김태곤
//---------------------------------
#include <CommonLogic.h>
#include "Char/CharCommon/Char-Common.h"

#include "StructureClass.h"
#include "../StructureRepair/StructureRepairDlg.h"

#include "../../DBManager/GameDBManager_World/DBMsg-Structure.h"

#include "../../Client/Music/Music.h"
#include "../../Server/Server.h"

#include "../../Resource.h"

#include "MsgRval-Define.h"
#include "MsgType-Structure.h"
#include "../../lib/WebHTML/WebHTML.h"
#include "../../Client/NStructureDlg/StrBaseDlg/StrBaseDlg.h"

#include "../../Client/NStructureDlg/PostOffice/NPostOfficeDlg.h"


//-----------------------------------
// Common
//-----------------------------------
#include "Quest/Quest.h"
#include "Char/CharManager/CharManager.h"
#include "Map/FieldObject/FieldObject.h"

extern cltCommonLogic* pclClient;

class cltStrTrnMsg{
public:
	SI32 siMsg;
	//SI32 siEffect;
	TCHAR szEffect[128];

	//TCHAR szMsg[128];
	SI32 siMsgIndex;
};


cltStrTrnMsg clStrTrnMsg[] ={

{SRVAL_ALREADYMAYOR,	"SOUND_EFFECT_FAILURE",										1		},
{SRVAL_INVALIDCANDIDATE,"SOUND_EFFECT_FAILURE",										2		},
{SRVAL_NOCANDIDATE,		"SOUND_EFFECT_FAILURE",										3		},
{SRVAL_NOMAYOR,			"SOUND_EFFECT_FAILURE",										4		},
{SRVAL_NOBANKCHIEF,		"SOUND_EFFECT_FAILURE",										5		},
{SRVAL_SUCCESSRESIGNMAYOR,"SOUND_EFFECT_SUCCESS",									6		},
{SRVAL_SUCCESSSETFEE,	"SOUND_EFFECT_SUCCESS",										7		},
{SRVAL_NOSELLPRODUCT,	"SOUND_EFFECT_FAILURE",										8		},
{SRVAL_NOSELLBANKACCOUNT,"SOUND_EFFECT_FAILURE",									9		},
{SRVAL_NOTENOUGHBANKMONEY,"SOUND_EFFECT_FAILURE",									10		},
{SRVAL_NOBUYBANKACCOUNT, "SOUND_EFFECT_FAILURE",									11		},
{SRVAL_CANNOTINPUTTOBUYER, "SOUND_EFFECT_FAILURE",									12		},
{SRVAL_SUCCESSTOBUYMARKET, "SOUND_EFFECT_SUCCESS",									13		},
{SRVAL_SUCCESSTOSELLMARKET, "SOUND_EFFECT_SUCCESS",									14		},
{SRVAL_NOMARKETACCOUNT, "SOUND_EFFECT_FAILURE",										15		},
{SRVAL_NOMATCHINGITEMININV, "SOUND_EFFECT_FAILURE",									16		},
{SRVAL_NOTMATCHMARKETACCOUNT, "SOUND_EFFECT_FAILURE",								17		},
{SRVAL_NOMATCHINGITEMINSTG, "SOUND_EFFECT_FAILURE",									18		},
{SRVAL_CANNOTINPUTTOINV, "SOUND_EFFECT_FAILURE",									19		},
{SRVAL_SUCCESSTOGETFROMSTG, "SOUND_EFFECT_SUCCESS",									20		},
{SRVAL_NOEMPTYHOUSE,	"SOUND_EFFECT_FAILURE",										21		},
{SRVAL_INVALIDHOUSEAPPLYER, "SOUND_EFFECT_FAILURE",									22		},
{SRVAL_INVALIDBANKACCOUNT, "SOUND_EFFECT_FAILURE",									23		},

//-----------------------------------------
// 전장 관련 
//-----------------------------------------
{SRVAL_BANK_SUCCESSINPUTMONEY, "SOUND_EFFECT_SUCCESS",								50		},
{SRVAL_BANK_FAILINPUTMONEY_OUTOFMONEY, "SOUND_EFFECT_FAILURE",						51		},
{SRVAL_BANK_FAILINPUTMONEY_NOACCOUNT, "SOUND_EFFECT_FAILURE",						52		},
{SRVAL_BANK_FAILINPUTMONEY_NOTENOUGHFEE, "SOUND_EFFECT_FAILURE",					53		},
{SRVAL_BANK_SUCCESSOUTPUTMONEY, "SOUND_EFFECT_SUCCESS",								54		},
{SRVAL_BANK_SUCCESSOUTPUTMONEY_DELACCOUNT, "SOUND_EFFECT_SUCCESS",					55		},
{SRVAL_BANK_FAILOUTPUTMONEY_NOACCOUNT, "SOUND_EFFECT_FAILURE",						56		},
{SRVAL_BANK_FAILOUTPUTMONEY_NOTENOUGHMONEYINACCOUNT, "SOUND_EFFECT_FAILURE",		57		},
{SRVAL_BANK_FAILOUTPUTMONEY_NOTENOUGHFEE, "SOUND_EFFECT_FAILURE",					58		},
{SRVAL_BANK_FAILSETFEE_NOTCHIEF, "SOUND_EFFECT_FAILURE",							59		},
{SRVAL_BANK_SUCCESSSETFEE, "SOUND_EFFECT_FAILURE",									60		},
{SRVAL_BANK_FAILCREATEACCOUNT, "SOUND_EFFECT_FAILURE",								61		},
{SRVAL_BANK_SUCCESSCREATEACCOUNT, "SOUND_EFFECT_SUCCESS",							62		},
{SRVAL_BANK_FAILCREATEACCOUNT_ALREADY, "SOUND_EFFECT_FAILURE",						63		},
{SRVAL_BANK_FAILCLOSEACCOUNT, "SOUND_EFFECT_FAILURE",								64		},
{SRVAL_BANK_SUCCESSCLOSEACCOUNT, "SOUND_EFFECT_SUCCESS",							65		},
{SRBAL_BANK_FAILCLOSEACCOUNT_OTHERVILLAGE, "SOUND_EFFECT_FAILURE",					66		},
{SRBAL_BANK_FAILCLOSEACCOUNT_CHECKMARKET, "SOUND_EFFECT_FAILURE",					67		},

//-----------------------------------------
// 여각 관련 
//-----------------------------------------
{SRVAL_STOCK_BUY_SUCCESSTRADE,		"SOUND_EFFECT_SUCCESS",							100		},
{SRVAL_STOCK_SELL_SUCCESSTRADE,		"SOUND_EFFECT_SUCCESS",							101		},
{SRVAL_STOCK_BUY_FAILNOACCOUNT,		"SOUND_EFFECT_FAILURE",							102		},
{SRVAL_STOCK_SELL_FAILNOACCOUNT,	"SOUND_EFFECT_FAILURE",							103		},
{SRVAL_STOCK_DSTSELLERNOACCOUNT,	"SOUND_EFFECT_FAILURE",							104		},
{SRVAL_STOCK_DSTBUYERNOACCOUNT,		"SOUND_EFFECT_FAILURE",							105		},
{SRVAL_STOCK_BUY_FAILNOTENOUGHMONEY,"SOUND_EFFECT_FAILURE",							106		},
{SRVAL_STOCK_SELL_FAILNOTENOUGHMONEY,"SOUND_EFFECT_FAILURE",						107		},
{SRVAL_STOCK_BUY_FAILLIMITSTOCKKIND, "SOUND_EFFECT_FAILURE",						108		},
{SRVAL_STOCK_SELL_FAILLIMITSTOCKKIND,"SOUND_EFFECT_FAILURE",						109		},
{SRVAL_STOCK_BUY_HALFSUCCESS,		"SOUND_EFFECT_FAILURE",							110		},
{SRVAL_STOCK_SELL_HALFSUCCESS,		"SOUND_EFFECT_FAILURE",							111		},
{SRVAL_STOCK_BUY_FAILLIAR,			"SOUND_EFFECT_FAILURE",							112		},
{SRVAL_STOCK_SELL_FAILLIAR,			"SOUND_EFFECT_FAILURE",							113		},
{SRVAL_STOCK_BUY_SUCCESSORDER,		"SOUND_EFFECT_SUCCESS",							114		},
{SRVAL_STOCK_SELL_SUCCESSORDER,		"SOUND_EFFECT_SUCCESS",							115		},
{SRVAL_STOCK_FAILSETFEE,		    "SOUND_EFFECT_FAILURE",							116		},
{SRVAL_STOCK_SUCCESSSETFEE,			"SOUND_EFFECT_FAILURE",							117		},
{SRVAL_STOCK_SUCCESS_BIDDING,				"SOUND_EFFECT_SUCCESS",					118		},
{SRVAL_STOCK_FAIL_BIDDING,					"SOUND_EFFECT_FAILURE",					119		},
{SRVAL_STOCK_SUCCESS_BUY_BIDSTOCK,				"SOUND_EFFECT_SUCCESS",					120		},
{SRVAL_STOCK_FAIL_BUY_BIDSTOCK,					"SOUND_EFFECT_FAILURE",					121		},
{SRVAL_STOCK_FAIL_BUY_BIDSTOCK_NOTENOUGHMONEY,	"SOUND_EFFECT_FAILURE",					122		},
{SRVAL_STOCK_FAIL_BUY_BIDSTOCK_ALREADY,			"SOUND_EFFECT_FAILURE",					123		},
{SRVAL_STOCK_FAIL_BUY_BIDSTOCK_EXCEEDAMOUNT,			"SOUND_EFFECT_FAILURE",					124		},
{SRVAL_STOCK_FAIL_BUY_BIDSTOCK_NOTBUYER,			"SOUND_EFFECT_FAILURE",					125		},

//{SRVAL_STOCK_FAIL_BIDDING_NOBANKACCOUNT,	"SOUND_EFFECT_FAILURE",					120		},
//{SRVAL_STOCK_FAIL_BIDDING_NOTENOUGHMONEY,	"SOUND_EFFECT_FAILURE",					121		},
//{SRVAL_STOCK_FAIL_BIDDING_EXCEEDAMOUNT,		"SOUND_EFFECT_FAILURE",					122		},
//{SRVAL_STOCK_FAIL_BIDDING_EXCEEDBIDDER,		"SOUND_EFFECT_FAILURE",					123		},
//{SRVAL_STOCK_FAIL_BIDDING_WRONGVALUE,		"SOUND_EFFECT_FAILURE",					124		},
//{SRVAL_STOCK_FAIL_BIDDING_WRONGVALUE10,		"SOUND_EFFECT_FAILURE",					125		},

//----------------------------------
// 상단 
//----------------------------------
{SRVAL_CITYHALL_SUCCESSCANDIDATE,	"SOUND_EFFECT_SUCCESS",							130		},
{SRVAL_CITYHALL_FAILCANDIDATE,		"SOUND_EFFECT_FAILURE",							131		},
{SRVAL_CITYHALL_FAILCANDIDATE_LEVELERROR, "SOUND_EFFECT_FAILURE",					132		},
{SRVAL_CITYHALL_FAILCANDIDATE_ALREADY,"SOUND_EFFECT_FAILURE",						133		},
{SRVAL_CITYHALL_FAILCANDIDATE_OVERFLOW,"SOUND_EFFECT_FAILURE",						134		},
{SRVAL_CITYHALL_SUCCESSCANCELCANDIDATE,"SOUND_EFFECT_SUCCESS",						135		},
{SRVAL_CITYHALL_FAILCANCELCANDIDATE, "SOUND_EFFECT_FAILURE",						136		},
{SRVAL_CITYHALL_SUCCESSBERANK,		"SOUND_EFFECT_SUCCESS",							137		},
{SRVAL_CITYHALL_FAIL_BERANK_NOTHOME,"SOUND_EFFECT_FAILURE",							138		},
{SRVAL_CITYHALL_FAILCANDIDATE_ALREADYRANK, "SOUND_EFFECT_FAILURE",					139		},
{SRVAL_CITYHALL_NOTBESTBEHOLDER,	"SOUND_EFFECT_FAILURE",							140		},
{SRVAL_CITYHALL_NOTMAYOR,			"SOUND_EFFECT_FAILURE",							141		},
{SRVAL_CITYHALL_SUCCESSDELCANDIDATE, "SOUND_EFFECT_SUCCESS",						142		},

{SRVAL_CITYHALL_FAIL_SYMBOLSTATUS_MONEY, "SOUND_EFFECT_FAILURE",					150		},
{SRVAL_CITYHALL_FAIL_SYMBOLSTATUS_DATE, "SOUND_EFFECT_FAILURE",						151		},
{SRVAL_CITYHALL_FAIL_SYMBOLSTATUS_RESIDENT, "SOUND_EFFECT_FAILURE",					152		},
{SRVAL_CITYHALL_FAIL_SYMBOLSTATUS_WARTIME, "SOUND_EFFECT_FAILURE",					153		},
{SRVAL_CITYHALL_FAIL_SYMBOLSTATUS_NOTEXIST, "SOUND_EFFECT_FAILURE",					154		},
{SRVAL_CITYHALL_FAIL_SYMBOLSTATUS_LOWERLEVEL, "SOUND_EFFECT_FAILURE",				155		},
{SRVAL_CITYHALL_FAIL_SYMBOLSTATUS_MAXLEVEL, "SOUND_EFFECT_FAILURE",					156		},

{SRVAL_CITYHALL_FAIL_CASTLESTATUS_MAXLEVEL, "SOUND_EFFECT_FAILURE",					157		},
{SRVAL_CITYHALL_FAIL_CASTLESTATUS_MONEY, "SOUND_EFFECT_FAILURE",					160		},
{SRVAL_CITYHALL_FAIL_CASTLESTATUS_DATE, "SOUND_EFFECT_FAILURE",						161		},
{SRVAL_CITYHALL_FAIL_CASTLESTATUS_RESIDENT, "SOUND_EFFECT_FAILURE",					162		},
{SRVAL_CITYHALL_FAIL_CASTLESTATUS_WARTIME, "SOUND_EFFECT_FAILURE",					163		},
{SRVAL_CITYHALL_FAIL_CASTLESTATUS_NOTEXIST, "SOUND_EFFECT_FAILURE",					164		},

{SRVAL_CITYHALL_FAIL_RESIDENTSHARE_WRONGCOUNT, "SOUND_EFFECT_FAILURE",				165		},
{SRVAL_CITYHALL_FAIL_RESIDENTSHARE_WRONGMONEY, "SOUND_EFFECT_FAILURE",				166		},
{SRVAL_CITYHALL_FAIL_RESIDENTSHARE_NOTENOUGHMONEY, "SOUND_EFFECT_FAILURE",			167		},
{SRVAL_CITYHALL_FAIL_RESIDENTSHARE_WRONGTIME, "SOUND_EFFECT_FAILURE",				168		},
{SRVAL_CITYHALL_FAIL_RESIDENTSHARE_DATE, "SOUND_EFFECT_FAILURE",					169		},

{SRVAL_CITYHALL_SUCCESS_HIRENPC, "SOUND_EFFECT_SUCCESS",							170		},
{SRVAL_CITYHALL_FAIL_HIRENPC_NOTENOUGHMONEY, "SOUND_EFFECT_FAILURE",				171		},
{SRVAL_CITYHALL_FAIL_HIRENPC_VILLAGELEVEL, "SOUND_EFFECT_FAILURE",					172		},
{SRVAL_CITYHALL_FAIL_HIRENPC_BUILDSTRUCTURE, "SOUND_EFFECT_FAILURE",				173		},

{SRVAL_CITYHALL_FAIL_CONSTRUCT_NPCZONE, "SOUND_EFFECT_FAILURE",						174		},
{SRVAL_CITYHALL_FAIL_CONSTRUCT_VILLAGELEVEL, "SOUND_EFFECT_FAILURE",				175		},
{SRVAL_CITYHALL_FAIL_CONSTRUCT_NOTFARM, "SOUND_EFFECT_FAILURE",						176		},

{SRVAL_CITYHALL_FAILDESTROYSTR_NOLAST,		"SOUND_EFFECT_FAILURE",					177		},
{SRVAL_CITYHALL_FAIL_DESTROYSTR_MEETING,	"SOUND_EFFECT_FAILURE",					178		},

{SRVAL_CITYHALL_SUCCESS_PROFITTOCAPITALFUND, "SOUND_EFFECT_SUCCESS",				179		},
{SRVAL_CITYHALL_FAIL_PROFITTOCAPITALFUND,	"SOUND_EFFECT_FAILURE",					180		},

{SRVAL_CITYHALL_FAIL_EVENT_NOTENOUGHMONEY,	"SOUND_EFFECT_FAILURE",					181		},
{SRVAL_CITYHALL_FAIL_EVENT_ALREADYSTARTED,	"SOUND_EFFECT_FAILURE",					182		},
{SRVAL_CITYHALL_FAIL_EVENT_JAPANWAR,		"SOUND_EFFECT_FAILURE",					183		},

{SRVAL_CITYHALL_SUCCESS_VILLAGEMARK,		"SOUND_EFFECT_SUCCESS",					184		},
{SRVAL_CITYHALL_FAIL_VILLAGEMARK_NOTENOUGHMONEY,	"SOUND_EFFECT_FAILURE",			185		},
{SRVAL_CITYHALL_FAIL_VILLAGEMARK_ALREADYUSED,		"SOUND_EFFECT_FAILURE",			186		},
{SRVAL_CITYHALL_FAIL_VILLAGEMARK_DATE,				"SOUND_EFFECT_FAILURE",			187		},

{SRVAL_CITYHALL_SUCCESS_VILLAGEMAP,		"SOUND_EFFECT_SUCCESS",						188		},
{SRVAL_CITYHALL_FAIL_VILLAGEMAP_NOTENOUGHMONEY,	"SOUND_EFFECT_FAILURE",				189		},
{SRVAL_CITYHALL_FAIL_VILLAGEMAP_LEVEL,			"SOUND_EFFECT_FAILURE",				190		},
{SRVAL_CITYHALL_SUCCESS_SETBASEMONEY,			"SOUND_EFFECT_SUCCESS",				191		},
{SRVAL_CITYHALL_FAIL_HIRECHRISTMAS_NOTENOUGHMONEY,	"SOUND_EFFECT_SUCCESS",			192		},


// 주민등록
{SRVAL_CITYHALL_FAIL_DECLAREWAR_TARGET_AFTERLOSE, "SOUND_EFFECT_FAILURE",			197		},
{SRVAL_CITYHALL_FAIL_DECLAREWAR_AFTERLOSE, "SOUND_EFFECT_FAILURE",					198		},
{SRVAL_CITYHALL_FAIL_DECLAREWAR_LOWERRANK, "SOUND_EFFECT_FAILURE",					199		},
{SRVAL_CITYHALL_SUCCESSAPPLYRESIDENT,"SOUND_EFFECT_SUCCESS",						200		},
{SRVAL_CITYHALL_FAILALREADYAPPLY,   "SOUND_EFFECT_FAILURE",							201		},
{SRVAL_CITYHALL_FAILALREADYRESIDENT,"SOUND_EFFECT_FAILURE",							202		},
{SRVAL_CITYHALL_FAILEXCEEDAPPLYER, "SOUND_EFFECT_FAILURE",							203		},
{SRVAL_CITYHALL_SUCCESSCANCELRESIDENT,"SOUND_EFFECT_SUCCESS",						204		},
{SRVAL_CITYHALL_FAILCANCELRESIDENT, "SOUND_EFFECT_FAILURE",							205		},
{SRVAL_CITYHALL_SUCCESS_GETRESIDENTINFO, "SOUND_EFFECT_SUCCESS",					206		},
{SRVAL_CITYHALL_FAIL_GETRESIDENTINFO, "SOUND_EFFECT_FAILURE",						207		},
{SRVAL_CITYHALL_FAIL_EXCEEDMAXRESIDENT, "SOUND_EFFECT_FAILURE",						208		},
{SRVAL_CITYHALL_FAIL_BERESIDENT_WRONGRANK, "SOUND_EFFECT_FAILURE",					209		},


// 전쟁 선포
{SRVAL_CITYHALL_SUCCESS_DECLAREWAR, "SOUND_EFFECT_SUCCESS",							210		},
{SRVAL_CITYHALL_FAIL_DECLAREWAR_ALREADYACT, "SOUND_EFFECT_FAILURE",					211		},
{SRVAL_CITYHALL_FAIL_DECLAREWAR_ALREADY, "SOUND_EFFECT_FAILURE",					212		},
{SRVAL_CITYHALL_FAIL_DECLAREWAR_NOTPROPER, "SOUND_EFFECT_FAILURE",					213		},
{SRVAL_CITYHALL_FAIL_DECLAREWAR_GAP, "SOUND_EFFECT_FAILURE",						214		},

{SRVAL_CITYHALL_SUCCESS_CANCELDECLAREWAR, "SOUND_EFFECT_SUCCESS",					215		},
{SRVAL_CITYHALL_FAIL_CANCELDECLAREWAR, "SOUND_EFFECT_FAILURE",						216		},
{SRVAL_CITYHALL_FAIL_DECLAREWAR_WARTIME, "SOUND_EFFECT_FAILURE",					217		},
{SRVAL_CITYHALL_FAIL_DECLAREWAR_DATE, "SOUND_EFFECT_FAILURE",						218		},
{SRVAL_CITYHALL_FAIL_DECLAREWAR_NOTMAYOR, "SOUND_EFFECT_FAILURE",					219		},


{SRVAL_CITYHALL_FAIL_DECLAREWAR_NOMASTER, "SOUND_EFFECT_FAILURE",					564		},

{SRVAL_GENERALMEETING_SUCCESS_SUGGEST, "SOUND_EFFECT_SUCCESS",						220		},
{SRVAL_GENERALMEETING_FAIL_SUGGEST, "SOUND_EFFECT_FAILURE",							221		},
{SRVAL_GENERALMEETING_FAIL_SUGGEST_ALEADY, "SOUND_EFFECT_FAILURE",					222		},	
{SRVAL_GENERALMEETING_FAIL_SUGGEST_NOTENOUGHSTOCK, "SOUND_EFFECT_FAILURE",			223		},
{SRVAL_GENERALMEETING_FAIL_SUGGEST_WRONGCANDIDATE, "SOUND_EFFECT_FAILURE",			224		},
{SRVAL_GENERALMEETING_FAIL_SUGGEST_ALREDYCANDIDATE, "SOUND_EFFECT_FAILURE",			225		},
{SRVAL_GENERALMEETING_FAIL_SUGGEST_CHIEFLEVEL, "SOUND_EFFECT_FAILURE",				226		},
{SRVAL_CITYHALL_FAIL_VILLAGEATWAR, "SOUND_EFFECT_FAILURE",							227		},
{SRVAL_CITYHALL_FAILTIMELIMIT, "SOUND_EFFECT_FAILURE",								228		},

{SRVAL_GENERALMEETING_SUCCESS_VOTE, "SOUND_EFFECT_SUCCESS",							230		},
{SRVAL_GENERALMEETING_FAIL_VOTE, "SOUND_EFFECT_FAILURE",							231		},	
{SRVAL_GENERALMEETING_FAIL_VOTE_ALREADY, "SOUND_EFFECT_FAILURE",					232		},
{SRVAL_GENERALMEETING_FAIL_VOTE_NOTVOTER, "SOUND_EFFECT_FAILURE",					233		},

{SRVAL_GENERALMEETING_SUCCESS_ACCEPTCANDIDATE, "SOUND_EFFECT_SUCCESS",				234		},
{SRVAL_GENERALMEETING_FAIL_ACCEPTCANDIDATE, "SOUND_EFFECT_FAILURE",					235		},
//----------------------------------
// 기부
//----------------------------------
{SRVAL_CITYHALL_DONATE_OVERMONEY, "SOUND_EFFECT_FAILURE",							236		},


//----------------------------------
// 시전 
//----------------------------------
{SRVAL_HOUSE_FAILAPPLY,						"SOUND_EFFECT_FAILURE",					240		},
{SRVAL_HOUSE_FAILAPPLY_NOACCOUNT,			"SOUND_EFFECT_FAILURE",					241		},
{SRVAL_HOUSE_FAILAPPLY_ALREADYAPPLY,		"SOUND_EFFECT_FAILURE",					242		},
{SRVAL_HOUSE_SUCCESSAPPLY,					"SOUND_EFFECT_SUCCESS",					243		},
{SRVAL_HOUSE_SUCCESSAPPLYCANCEL,			"SOUND_EFFECT_SUCCESS",					244		},
{SRVAL_HOUSE_FAILSETCONTRACT_NOTCHIEF,		"SOUND_EFFECT_FAILURE",					245		},
{SRVAL_HOUSE_FAILSETCONTRACT_WRONGFEE,		"SOUND_EFFECT_FAILURE",					246		}, 
{SRVAL_HOUSE_FAILSETCONTRACT_DATE,			"SOUND_EFFECT_FAILURE",					247		},
{SRVAL_HOUSE_SUCCESSSETCONTRACT,			"SOUND_EFFECT_SUCCESS",					248		},
{SRVAL_HOUSE_FAILNOTSAMECONTRACT,			"SOUND_EFFECT_FAILURE",					249		},
{SRVAL_HOUSE_FAILNOMOREREALESTATE,			"SOUND_EFFECT_FAILURE",					250		},
{SRVAL_HOUSE_SUCCESSDELHOUSEAPPLYER,		"SOUND_EFFECT_SUCCESS",					251		},
{SRVAL_HOUSE_FAILDELHOUSEAPPLYER_NOTCHIEF,	"SOUND_EFFECT_FAILURE",					252		},
{SRVAL_HOUSE_FAILEXTENDCONTRAC_NOMONEY,		"SOUND_EFFECT_FAILURE",					253		},
{SRVAL_HOUSE_SUCCESSHOUSERENT,				"SOUND_EFFECT_SUCCESS",					254		},
{SRVAL_HOUSE_SUCCESSEXTENDCONTRACT,			"SOUND_EFFECT_SUCCESS",					255		},
{SRVAL_HOUSE_FAILNOTENOUGHMONEY,			"SOUND_EFFECT_FAILURE",					256		},
{SRVAL_HOUSE_FAILREMAINDITEM,				"SOUND_EFFECT_FAILURE",					257		},
{SRVAL_HOUSE_SUCCESSCANCELLATION,			"SOUND_EFFECT_SUCCESS",					258		},
{SRVAL_HOUSE_FAILINPUT_NOTRADEITEM,			"SOUND_EFFECT_FAILURE",					259		},
{SRVAL_HOUSE_FAILINPUT_FULLSTG,				"SOUND_EFFECT_FAILURE",					602		},

//----------------------------------
// 객주 
//----------------------------------
{SRVAL_MARKET_SUCCESS_ORDERSELL,		"SOUND_EFFECT_SUCCESS",						260		},
{SRVAL_MARKET_FAIL_ORDERSELL_OVERFLOW,	"SOUND_EFFECT_FAILURE",						261		},
{SRVAL_MARKET_SUCCESS_GETFROMMARKET,	"SOUND_EFFECT_SUCCESS",						262		},
{SRVAL_MARKET_FAIL_GETFROMMARKET,		"SOUND_EFFECT_FAILURE",						263		},
{SRVAL_MARKET_SUCCESS_TRADE,			"SOUND_EFFECT_SUCCESS",						264		},
{SRVAL_MARKET_FAILSETFEE,				"SOUND_EFFECT_FAILURE",						265		},
{SRVAL_MARKET_SUCCESSSETFEE,			"SOUND_EFFECT_SUCCESS",						266		},
{SRVAL_MARKET_FAIL_NOTRADEITEM,			"SOUND_EFFECT_FAILURE",						267		},

{SRVAL_NEWMARKET_SUCCESS_ORDERSELL,					"SOUND_EFFECT_SUCCESS",			260		},
{SRVAL_NEWMARKET_FAIL_ORDERSELL_OVERFLOW,			"SOUND_EFFECT_FAILURE",			261		},
{SRVAL_NEWMARKET_SUCCESS_GETFROMMARKET,				"SOUND_EFFECT_SUCCESS",			262		},
{SRVAL_NEWMARKET_FAIL_GETFROMMARKET,				"SOUND_EFFECT_FAILURE",			263		},
{SRVAL_NEWMARKET_SUCCESS_TRADE,						"SOUND_EFFECT_SUCCESS",			264		},
{SRVAL_NEWMARKET_FAILSETFEE,						"SOUND_EFFECT_FAILURE",			606		},
{SRVAL_NEWMARKET_SUCCESSSETFEE,						"SOUND_EFFECT_SUCCESS",			266		},
{SRVAL_NEWMARKET_FAIL_NOTRADEITEM,					"SOUND_EFFECT_FAILURE",			267		},
{SRVAL_NEWMARKET_DONOT_TRADETIME,					"SOUND_EFFECT_FAILURE",			267		},
{SRVAL_NEWMARKET_FAIL_ORDERSELL_ALREADY_ORDERED,	"SOUND_EFFECT_FAILURE",			267		},


//----------------------------------
// 수렵장 
//----------------------------------
{SRVAL_HUNT_NOPARTMEMBER,				"SOUND_EFFECT_FAILURE",						270		},
{SRVAL_HUNT_ALREADYPARTYUSE,			"SOUND_EFFECT_FAILURE",						271		},
{SRVAL_HUNT_ALREADYPARTYUSE,			"SOUND_EFFECT_FAILURE",						272		},
{SRVAL_HUNT_FAIL_HUNTMAP_NOTENOUGHMONEY,		"SOUND_EFFECT_FAILURE",				273		},
{SRVAL_HUNT_SUCCESS_HUNTMAP,			"SOUND_EFFECT_SUCCESS",						274		},


//----------------------------------
// 역참
//----------------------------------
{SRVAL_POSTOFFICE_SUCCESS_SENDITEM,			"SOUND_EFFECT_SUCCESS",					280		},
{SRVAL_POSTOFFICE_SUCCESS_SENDMSG,			"SOUND_EFFECT_SUCCESS",					281		},
{SRVAL_POSTOFFICE_SUCCESS_SENDMONEY,		"SOUND_EFFECT_SUCCESS",					282		},

{SRVAL_POSTOFFICE_FAIL_SEND_NOTENOUGHMONEY, "SOUND_EFFECT_FAILURE",					283		},
{SRVAL_POSTOFFICE_FAIL_SEND_NOTENOUGHFEE,	"SOUND_EFFECT_FAILURE",					284		},
{SRVAL_POSTOFFICE_FAIL_SEND_WRONGNAME,		"SOUND_EFFECT_FAILURE",					285		},
{SRVAL_POSTOFFICE_FAIL_SEND_FULLRECVBOX,	"SOUND_EFFECT_FAILURE",					286		},
//KHY - 0614 - 가차 아이템은 같은 계정간 캐릭터에 한하여 우편으로 주고 받을 수 있다. 
{SRVAL_POSTOFFICE_FAIL_SEND_ANOTHERPERSON,	"SOUND_EFFECT_FAILURE",					286		},
{SRVAL_POSTOFFICE_FAIL_SEND_SAMEPERSON,		"SOUND_EFFECT_FAILURE",					287		},
{SRVAL_POSTOFFICE_FAIL_SEND_USEDATEOVER,	"SOUND_EFFECT_FAILURE",					565		},
{SRVAL_POSTOFFICE_FAIL_SEND_NOTRADEITEM,	"SOUND_EFFECT_FAILURE",					567		},


{SRVAL_POSTOFFICE_SUCCESS_GETITEM,			"SOUND_EFFECT_SUCCESS",					288		},
{SRVAL_POSTOFFICE_FAIL_GETITEM_FULLINVEN,   "SOUND_EFFECT_FAILURE",					289		},
{SRVAL_POSTOFFICE_FAIL_GETITEM_USEDATEOVER,	"SOUND_EFFECT_FAILURE",					565		},
{SRVAL_POSTOFFICE_SUCCESS_GETMONEY,			"SOUND_EFFECT_SUCCESS",					290		},
{SRVAL_POSTOFFICE_FAIL_GETMONEY,			"SOUND_EFFECT_FAILURE",					291		},

{SRVAL_POSTOFFICE_SUCCESS_SETFEE,			"SOUND_EFFECT_SUCCESS",					292		},
{SRVAL_POSTOFFICE_FAIL_SETFEE,				"SOUND_EFFECT_FAILURE",					293		},


//----------------------------------
// 사복시
//----------------------------------
{SRVAL_HORSEMARKET_SUCCESS_SELLHORSE,		"SOUND_EFFECT_SUCCESS",					300		},
{SRVAL_HORSEMARKET_FAIL_SELL,				"SOUND_EFFECT_FAILURE",					301		},
{SRVAL_HORSEMARKET_FAIL_SELL_ALREADY,		"SOUND_EFFECT_FAILURE",					302		},
{SRVAL_HORSEMARKET_FAIL_SELL_NOTEMPTYINVEN,	"SOUND_EFFECT_FAILURE",					303		},
{SRVAL_HORSEMARKET_FAIL_SELL_NOTHAVE,		"SOUND_EFFECT_FAILURE",					304		},
{SRVAL_HORSEMARKET_FAIL_SELL_NOTENOUGHMONEY,"SOUND_EFFECT_FAILURE",					305		},

{SRVAL_HORSEMARKET_SUCCESS_GETBACK,			"SOUND_EFFECT_SUCCESS",					306		},
{SRVAL_HORSEMARKET_FAIL_GETBACK,			"SOUND_EFFECT_FAILURE",					307		},
{SRVAL_HORSEMARKET_FAIL_GETBACK_HAVEANOTHER,"SOUND_EFFECT_FAILURE",					308		},
{SRVAL_HORSEMARKET_FAIL_GETBACK_NOORDER,	"SOUND_EFFECT_FAILURE",					309		},

{SRVAL_HORSEMARKET_SUCCESS_BUYHORSE,		"SOUND_EFFECT_SUCCESS",					310		},
{SRVAL_HORSEMARKET_FAIL_BUY,				"SOUND_EFFECT_FAILURE",					311		},
{SRVAL_HORSEMARKET_FAIL_BUY_NOTENOUGHMONEY,	"SOUND_EFFECT_FAILURE",					312		},
{SRVAL_HORSEMARKET_FAIL_BUY_HAVEANOTHER,	"SOUND_EFFECT_FAILURE",					313		},
{SRVAL_HORSEMARKET_FAIL_BUY_NOTSELF,		"SOUND_EFFECT_FAILURE",					314		},
{SRVAL_HORSEMARKET_FAIL_BUY_NOTVALID,		"SOUND_EFFECT_FAILURE",					315		},

{SRVAL_HORSEMARKET_SUCCESS_SETFEE,			"SOUND_EFFECT_SUCCESS",					316		},
{SRVAL_HORSEMARKET_FAIL_SETFEE,				"SOUND_EFFECT_FAILURE",					317		},
{SRVAL_HORSEMARKET_FAIL_SELL_CANNOTTRADE,	"SOUND_EFFECT_FAILURE",					318		},

//----------------------------------
// 거간
//----------------------------------
{SRVAL_REALESTATEMARKET_SUCCESS_SELL,				"SOUND_EFFECT_SUCCESS",			330		},
{SRVAL_REALESTATEMARKET_FAIL_SELL,					"SOUND_EFFECT_FAILURE",			331		},
{SRVAL_REALESTATEMARKET_FAIL_SELL_NOTENOUGHMONEY,	"SOUND_EFFECT_FAILURE",			332		},
{SRVAL_REALESTATEMARKET_FAIL_SELL_NOTVALID,			"SOUND_EFFECT_FAILURE",			333		},

{SRVAL_REALESTATEMARKET_SUCCESS_CANCELORDER,		"SOUND_EFFECT_SUCCESS",			334		},
{SRVAL_REALESTATEMARKET_FAIL_CANCELORDER,			"SOUND_EFFECT_FAILURE",			335		},

{SRVAL_REALESTATEMARKET_SUCCESS_BUY,				"SOUND_EFFECT_SUCCESS",			336		},
{SRVAL_REALESTATEMARKET_FAIL_BUY,					"SOUND_EFFECT_FAILURE",			337		},
{SRVAL_REALESTATEMARKET_FAIL_BUY_NOTENOUGHMONEY,	"SOUND_EFFECT_FAILURE",			338		},
{SRVAL_REALESTATEMARKET_FAIL_BUY_NOMORE,			"SOUND_EFFECT_FAILURE",			339		},
{SRVAL_REALESTATEMARKET_FAIL_BUY_NOTVALID,			"SOUND_EFFECT_FAILURE",			340		},
{SRVAL_REALESTATEMARKET_FAIL_BUY_NOTSELF,			"SOUND_EFFECT_FAILURE",			341		},

{SRVAL_REALESTATEMARKET_SUCCESS_SETFEE,				"SOUND_EFFECT_SUCCESS",			342		},
{SRVAL_REALESTATEMARKET_FAIL_SETFEE,				"SOUND_EFFECT_FAILURE",			343		},
{SRVAL_REALESTATEMARKET_FAIL_SELL_HAVENOTRADE,		"SOUND_EFFECT_FAILURE",			344		},
{SRVAL_REALESTATEMARKET_FAIL_SELL_HAVENOTRADEHORSE,	"SOUND_EFFECT_FAILURE",			345		},



//----------------------------------
// 장예원 
//----------------------------------
{SRVAL_SUMMONMARKET_SUCCESS_SELL,					"SOUND_EFFECT_SUCCESS",			350		},
{SRVAL_SUMMONMARKET_FAIL_SELL,						"SOUND_EFFECT_FAILURE",			351		},									
{SRVAL_SUMMONMARKET_FAIL_SELL_NOMORE,				"SOUND_EFFECT_FAILURE",			352		},			
{SRVAL_SUMMONMARKET_FAIL_SELL_NOTHAVE,				"SOUND_EFFECT_FAILURE",			353		},			
{SRVAL_SUMMONMARKET_FAIL_SELL_NOTENOUGHMONEY,		"SOUND_EFFECT_FAILURE",			354		},									
{SRVAL_SUMMONMARKET_FAIL_SELL_HAVEITEM,				"SOUND_EFFECT_FAILURE",			355		},

{SRVAL_SUMMONMARKET_SUCCESS_CANCELORDER,			"SOUND_EFFECT_SUCCESS",			356		},									
{SRVAL_SUMMONMARKET_FAIL_CANCELORDER,				"SOUND_EFFECT_FAILURE",			357		},									
{SRVAL_SUMMONMARKET_FAIL_CANCELORDER_NOMORE,		"SOUND_EFFECT_FAILURE",			358		},
{SRVAL_SUMMONMARKET_FAIL_CANCELORDER_NOTVALID,		"SOUND_EFFECT_FAILURE",			359		},

{SRVAL_SUMMONMARKET_SUCCESS_BUY,					"SOUND_EFFECT_SUCCESS",			360		},								
{SRVAL_SUMMONMARKET_FAIL_BUY,						"SOUND_EFFECT_FAILURE",			361		},										
{SRVAL_SUMMONMARKET_FAIL_BUY_NOTENOUGHMONEY,		"SOUND_EFFECT_FAILURE",			362		},						
{SRVAL_SUMMONMARKET_FAIL_BUY_NOMORE,				"SOUND_EFFECT_FAILURE",			363		},								
{SRVAL_SUMMONMARKET_FAIL_BUY_NOTSELF,				"SOUND_EFFECT_FAILURE",			364		},
{SRVAL_SUMMONMARKET_FAIL_BUY_NOTVALID,				"SOUND_EFFECT_FAILURE",			365		},

{SRVAL_SUMMONMARKET_SUCCESS_SETFEE,					"SOUND_EFFECT_SUCCESS",			366		},						
{SRVAL_SUMMONMARKET_FAIL_SETFEE,					"SOUND_EFFECT_FAILURE",			367		},	

{SRVAL_SUMMONMARKET_FAIL_SELECTSELL_WRONGNAME,		"SOUND_EFFECT_FAILURE",			368		},
{SRVAL_SUMMONMARKET_FAIL_BUY_NOTSELECTPERSON,		"SOUND_EFFECT_FAILURE",			369		},
{SRVAL_SUMMONMARKET_FAIL_SELECTSELL_NOTHAVETICKET,	"SOUND_EFFECT_FAILURE",			370		},
{SRVAL_SUMMONMARKET_FAIL_SELECTSELL_WRONGPRICE,		"SOUND_EFFECT_FAILURE",			371		},

//----------------------------------
// 농장
//----------------------------------
{SRVAL_LAND_SUCCESS_APPLY,						"SOUND_EFFECT_SUCCESS",				400		},
{SRVAL_LAND_FAIL_APPLY,							"SOUND_EFFECT_FAILURE",				401		},
{SRVAL_LAND_FAIL_APPLY_NOACCOUNT,				"SOUND_EFFECT_FAILURE",				402		},
{SRVAL_LAND_FAIL_APPLY_ALREADYAPPLY,			"SOUND_EFFECT_FAILURE",				403		},

{SRVAL_LAND_SUCCESS_CANCELAPPLY,				"SOUND_EFFECT_SUCCESS",				404		},
{SRVAL_LAND_FAIL_CANCELAPPLY,					"SOUND_EFFECT_FAILURE",				405		},

{SRVAL_LAND_SUCCESS_SETCONTRACT,				"SOUND_EFFECT_SUCCESS",				406		},
{SRVAL_LAND_FAIL_SETCONTRACT,					"SOUND_EFFECT_FAILURE",				407		},
{SRVAL_LAND_FAIL_SETCONTRACT_WRONGFEE,			"SOUND_EFFECT_FAILURE",				408		},
{SRVAL_LAND_FAIL_SETCONTRACT_DATE,				"SOUND_EFFECT_FAILURE",				409		},

{SRVAL_LAND_SUCCESS_RENT,						"SOUND_EFFECT_SUCCESS",				410		},
{SRVAL_LAND_FAIL_RENT,							"SOUND_EFFECT_FAILURE",				411		},
{SRVAL_LAND_FAIL_NOTSAMECONTRACT,				"SOUND_EFFECT_FAILURE",				412		},
{SRVAL_LAND_FAIL_NOMOREREALESTATE,				"SOUND_EFFECT_FAILURE",				413		},
{SRVAL_LAND_FAIL_RENT_NOTEMPTY,					"SOUND_EFFECT_FAILURE",				414		},
{SRVAL_LAND_FAIL_RENT_INVALIDPERSONID,			"SOUND_EFFECT_FAILURE",				415		},

{SRVAL_LAND_SUCCESS_DELLANDAPPLYER,				"SOUND_EFFECT_SUCCESS",				416		},

{SRVAL_FEAST_SUCCESS_RESERVE,					"SOUND_EFFECT_SUCCESS",				417		},
{SRVAL_FEAST_FAIL_RESERVE,						"SOUND_EFFECT_FAILURE",				418		}, 
{SRVAL_FEAST_FAIL_RESERVE_NOTENOUGHMONEY,       "SOUND_EFFECT_FAILURE",				419		}, 
{SRVAL_FEAST_FAIL_RESERVE_ALREADY,				"SOUND_EFFECT_FAILURE",				420		},
{SRVAL_FEAST_FAIL_RESERVE_DATE,					"SOUND_EFFECT_FAILURE",				421		}, 

{SRVAL_TAX_SUCCESS_SETTAX,				"SOUND_EFFECT_SUCCESS",						422		},
{SRVAL_TAX_SUCCESS_PAYTAX,				"SOUND_EFFECT_SUCCESS",						423		},
{SRVAL_TAX_FAIL_PAYTAX_NOTENOUGHMONEY,	"SOUND_EFFECT_FAILURE",						424		},
{SRVAL_TAX_FAIL_PAYTAX_NODURA,			"SOUND_EFFECT_FAILURE",						425		},
{SRVAL_TAX_FAIL_WRONGMONEY,				"SOUND_EFFECT_FAILURE",						426		},
{SRVAL_TAX_FAIL_DATE,					"SOUND_EFFECT_FAILURE",						427		},

{SRVAL_DIVIDEND_SUCCESS_PAYDIVIDEND,	"SOUND_EFFECT_SUCCESS",						428		},
{SRVAL_DIVIDEND_FAIL_WRONGMONEY,		"SOUND_EFFECT_FAILURE",						429		},
{SRVAL_DIVIDEND_FAIL_NOTENOUGHMONEY,	"SOUND_EFFECT_FAILURE",						430		},
{SRVAL_DIVIDEND_FAIL_DATEERROR,			"SOUND_EFFECT_FAILURE",						431		},

{SRVAL_PAYFEE_SUCCESS,					"SOUND_EFFECT_SUCCESS",						432		},
{SRVAL_PAYFEE_FAIL_NOTENOUGHMONEY,		"SOUND_EFFECT_FAILURE",						433		},

{SRVAL_STRMSG_SUCCESS,					"SOUND_EFFECT_SUCCESS",						434		},

{SRVAL_FEAST_FAIL_RESERVE_OPEN,			"SOUND_EFFECT_FAILURE",						435		},
{SRVAL_FEAST_FAIL_RESERVE_ITEM,			"SOUND_EFFECT_FAILURE",						436		},
{SRVAL_FEAST_FAIL_NOCHANGE,				"SOUND_EFFECT_FAILURE",						437		},
{SRVAL_FEAST_SUCCESS_SETCOST,			"SOUND_EFFECT_SUCCESS",						438		},
{SRVAL_FEAST_FAIL_SETCOST,				"SOUND_EFFECT_FAILURE",						439		},
{SRVAL_FEAST_SUCCESS_GIVEITEM,			"SOUND_EFFECT_SUCCESS",						440		},
{SRVAL_FEAST_FAIL_GIVEITEM,				"SOUND_EFFECT_FAILURE",						441		},
{SRVAL_FEAST_FAIL_GIVEITEM_WRONGPERSON, "SOUND_EFFECT_FAILURE",						442		},
{SRVAL_FEAST_FAIL_GIVEITEM_NOTOPEN,		"SOUND_EFFECT_FAILURE",						443		},
{SRVAL_FEAST_FAIL_GIVEITEM_ALREADY,		"SOUND_EFFECT_FAILURE",						444		},
{SRVAL_FEAST_FAIL_ITEM_WRONG,			"SOUND_EFFECT_FAILURE",						445		},
{SRVAL_FEAST_FAIL_ITEM_ALREADY,			"SOUND_EFFECT_FAILURE",						446		},

//#if defined(_LEON_FEAST_EFFECT)
	{SRVAL_FEAST_FAIL_USEEFFECT_NOTHAVETICKET,			"SOUND_EFFECT_FAILURE",						447		},
	{SRVAL_FEAST_SUCCESS_USEEFFECT,						"SOUND_EFFECT_SUCCESS",						448		},
//#endif
{SRVAL_FEAST_FAIL_ITEM_TOOMANY,			"SOUND_EFFECT_FAILURE",						449		},

//----------------------------------
// 포구
//----------------------------------
{SRVAL_PORT_FAILAPPLY_NOACCOUNT,			"SOUND_EFFECT_FAILURE",					450		},
{SRVAL_PORT_FAILSETCONTRACT_NOTCHIEF,		"SOUND_EFFECT_FAILURE",					451		},
{SRVAL_PORT_SUCCESSSETCONTRACT,				"SOUND_EFFECT_SUCCESS",					452		},
{SRVAL_PORT_FAILNOTSAMECONTRACT,			"SOUND_EFFECT_FAILURE",					453		},
{SRVAL_PORT_FAILEXTENDCONTRACT_NOMONEY,		"SOUND_EFFECT_FAILURE",					454		},
{SRVAL_PORT_SUCCESSPORTRENT,				"SOUND_EFFECT_SUCCESS",					455		},

//----------------------------------
// 비변사 => 아래에 추가부분 있음
//----------------------------------
{SRVAL_SUMMONHEROMARKET_SUCCESS_SELL,					"SOUND_EFFECT_SUCCESS",			460		},
{SRVAL_SUMMONHEROMARKET_FAIL_SELL,						"SOUND_EFFECT_FAILURE",			461		},									
{SRVAL_SUMMONHEROMARKET_FAIL_SELL_NOMORE,				"SOUND_EFFECT_FAILURE",			462		},			
{SRVAL_SUMMONHEROMARKET_FAIL_SELL_NOTHAVE,				"SOUND_EFFECT_FAILURE",			463		},			
{SRVAL_SUMMONHEROMARKET_FAIL_SELL_NOTENOUGHMONEY,		"SOUND_EFFECT_FAILURE",			464		},									
{SRVAL_SUMMONHEROMARKET_FAIL_SELL_HAVEITEM,				"SOUND_EFFECT_FAILURE",			465		},

{SRVAL_SUMMONHEROMARKET_SUCCESS_CANCELORDER,			"SOUND_EFFECT_SUCCESS",			466		},									
{SRVAL_SUMMONHEROMARKET_FAIL_CANCELORDER,				"SOUND_EFFECT_FAILURE",			467		},									
{SRVAL_SUMMONHEROMARKET_FAIL_CANCELORDER_NOMORE,		"SOUND_EFFECT_FAILURE",			468		},
{SRVAL_SUMMONHEROMARKET_FAIL_CANCELORDER_NOTVALID,		"SOUND_EFFECT_FAILURE",			469		},

{SRVAL_SUMMONHEROMARKET_SUCCESS_BUY,					"SOUND_EFFECT_SUCCESS",			470		},								
{SRVAL_SUMMONHEROMARKET_FAIL_BUY,						"SOUND_EFFECT_FAILURE",			471		},										
{SRVAL_SUMMONHEROMARKET_FAIL_BUY_NOTENOUGHMONEY,		"SOUND_EFFECT_FAILURE",			472		},						
{SRVAL_SUMMONHEROMARKET_FAIL_BUY_NOMORE,				"SOUND_EFFECT_FAILURE",			473		},								
{SRVAL_SUMMONHEROMARKET_FAIL_BUY_NOTSELF,				"SOUND_EFFECT_FAILURE",			474		},
{SRVAL_SUMMONHEROMARKET_FAIL_BUY_NOTVALID,				"SOUND_EFFECT_FAILURE",			475		},

{SRVAL_SUMMONHEROMARKET_SUCCESS_SETFEE,					"SOUND_EFFECT_SUCCESS",			476		},						
{SRVAL_SUMMONHEROMARKET_FAIL_SETFEE,					"SOUND_EFFECT_FAILURE",			477		},	

//----------------------------------
// 광산
//----------------------------------
{SRVAL_MINE_SUCCESS_APPLY,						"SOUND_EFFECT_SUCCESS",				478		},
{SRVAL_MINE_FAIL_APPLY,							"SOUND_EFFECT_FAILURE",				479		},
{SRVAL_MINE_FAIL_APPLY_NOACCOUNT,				"SOUND_EFFECT_FAILURE",				480		},
{SRVAL_MINE_FAIL_APPLY_ALREADYAPPLY,			"SOUND_EFFECT_FAILURE",				481		},

{SRVAL_MINE_SUCCESS_CANCELAPPLY,				"SOUND_EFFECT_SUCCESS",				482		},
{SRVAL_MINE_FAIL_CANCELAPPLY,					"SOUND_EFFECT_FAILURE",				483		},

{SRVAL_MINE_SUCCESS_SETCONTRACT,				"SOUND_EFFECT_SUCCESS",				484		},
{SRVAL_MINE_FAIL_SETCONTRACT,					"SOUND_EFFECT_FAILURE",				485		},
{SRVAL_MINE_FAIL_SETCONTRACT_WRONGFEE,			"SOUND_EFFECT_FAILURE",				486		},
{SRVAL_MINE_FAIL_SETCONTRACT_DATE,				"SOUND_EFFECT_FAILURE",				487		},

{SRVAL_MINE_SUCCESS_RENT,						"SOUND_EFFECT_SUCCESS",				488		},
{SRVAL_MINE_FAIL_RENT,							"SOUND_EFFECT_FAILURE",				489		},
{SRVAL_MINE_FAIL_NOTSAMECONTRACT,				"SOUND_EFFECT_FAILURE",				490		},
{SRVAL_MINE_FAIL_NOMOREREALESTATE,				"SOUND_EFFECT_FAILURE",				491		},
{SRVAL_MINE_FAIL_RENT_NOTEMPTY,					"SOUND_EFFECT_FAILURE",				492		},
{SRVAL_MINE_FAIL_RENT_INVALIDPERSONID,			"SOUND_EFFECT_FAILURE",				493		},

{SRVAL_MINE_SUCCESS_DELMINEAPPLYER,				"SOUND_EFFECT_SUCCESS",				494		},
{SRVAL_CITYHALL_FAIL_CONSTRUCT_NOTMINE,			"SOUND_EFFECT_FAILURE",				495		},

{SRVAL_CITYHALL_FAIL_CONSTRUCT_NOTENOUGHMONEY,	"SOUND_EFFECT_FAILURE",				496		},

//----------------------------------
// 비변사 추가부분
//----------------------------------
{SRVAL_SUMMONHEROMARKET_FAIL_SELECTSELL_WRONGNAME,		"SOUND_EFFECT_FAILURE",			510		},
{SRVAL_SUMMONHEROMARKET_FAIL_BUY_NOTSELECTPERSON,		"SOUND_EFFECT_FAILURE",			511		},
{SRVAL_SUMMONHEROMARKET_FAIL_SELECTSELL_NOTHAVETICKET,	"SOUND_EFFECT_FAILURE",			512		},
{SRVAL_SUMMONHEROMARKET_FAIL_SELECTSELL_WRONGPRICE,		"SOUND_EFFECT_FAILURE",			513		},

//----------------------------------
// 길드
//----------------------------------
{SRVAL_GUILD_SUCCESS_CREATE,		"SOUND_EFFECT_SUCCESS",			550		},
{SRVAL_GUILD_FAIL_CREATE,			"SOUND_EFFECT_FAILURE",			551		},
{SRVAL_GUILD_FAIL_WRONG_NAME,		"SOUND_EFFECT_FAILURE",			552		},
{SRVAL_GUILD_FAIL_FULLSLOT,			"SOUND_EFFECT_FAILURE",			553		},
{SRVAL_GUILD_FAIL_ALREADYMEMBER,	"SOUND_EFFECT_FAILURE",			554		},
{SRVAL_GUILD_FAILSETFEE,			"SOUND_EFFECT_FAILURE",			555		},
{SRVAL_GUILD_FAILSETFEERATE,		"SOUND_EFFECT_FAILURE",			556		},
{SRVAL_GUILD_SUCCESSSETCONTRACT,			"SOUND_EFFECT_SUCCESS",			557		},
{SRVAL_GUILD_FAILSETCONTRACT_NOTCHIEF,		"SOUND_EFFECT_FAILURE",			558		},
{SRVAL_GUILD_FAILSETCONTRACT_WRONGFEE,		"SOUND_EFFECT_FAILURE",			559		},
{SRVAL_GUILD_FAILSETCONTRACT_DATE,			"SOUND_EFFECT_FAILURE",					560		},
{SRVAL_GUILD_FAILSETCONTRACT,			"SOUND_EFFECT_FAILURE",			561		},
{SRVAL_GUILD_FAIL_GETGUILDRANKLIST,			"SOUND_EFFECT_FAILURE",			562		},
{SRVAL_GUILD_FAIL_NOTENOUGHMONEY,			"SOUND_EFFECT_FAILURE",			563		},

{SRVAL_STOCKOFFERING_SUCCESS_ORDER,		"SOUND_EFFECT_SUCCESS",		569 },
{SRVAL_STOCKOFFERING_FAIL_ORDERALREADY,	"SOUND_EFFECT_FAILURE",		568 },
{SRVAL_STOCKOFFERING_FAIL_ORDER,		"SOUND_EFFECT_FAILURE",		570 },
{SRVAL_STOCKOFFERING_FAIL_ORDERMONEY,	"SOUND_EFFECT_FAILURE",		571 },
{SRVAL_STOCKOFFERING_FAIL_ORDERLIMIT,	"SOUND_EFFECT_FAILURE",		572 },

//----------------------------------
// 이벤트
//----------------------------------
{SRVAL_MOFUMOFUEVENT_FAIL_RESERVE,		"SOUND_EFFECT_FAILURE",		573 },
{SRVAL_MOFUMOFUEVENT_FAIL_ALREADY_RESERVE,		"SOUND_EFFECT_FAILURE",		574 },
{0,						"",					0		}, 		

};

cltStructureBasic::cltStructureBasic(SI32 villageunique)
{
	siVillageUnique			= villageunique;
}


cltStructureBasic::~cltStructureBasic()
{
}


cltStrInfo* cltStructureBasic::GetStrInfo()
{
	return &clStrInfo;
}

void cltStructureBasic::SetStrInfo(cltStrInfo* pclinfo)
{
	if(pclinfo == NULL)return ;
	clStrInfo.Set(pclinfo);
}


//-------------------------------------------------------------
// cltStructureMngBasic
//-------------------------------------------------------------

cltStructureMngBasic::cltStructureMngBasic(SI32 sitabctrlnum, cltCharManager* pclcm, SI32 ranktype,  TCHAR *strFileName )
{
	SI32 i;

	siTabCtrlNum	= sitabctrlnum;
	CharUnique		= 0;					// 대상이 되는 캐릭터. 

	pclCM			= pclcm;

	DlgRectInitSwitch	= FALSE;

	siVillageUnique	= 0;
	siRankType		= ranktype;
	
	if ( strFileName )			// strFileName 이 NULL 일 수가 있음으로.
	{
		StringCchCopy( m_strFileName, 128, strFileName );
	}
	else
	{
		memset( m_strFileName, 0, _MAX_PATH );
	}


	StringCchCopy(szTitle, 128, TEXT(""));

	siServerResponseValue	= 0;

	for(i = 0;i < MAX_VILLAGE_NUMBER;i++)
	{
		pclStruct[i] = NULL;
	}

	UpdateChiefSwitch	= false;
	bDrawPortraitSwitch	= false;

	szMainExplain[ 0 ] = NULL;

	pclStructureRepairDlg = new cltStructureRepairDlg;

	bSetNeedItem = FALSE;
	tickTemp = GetTickCount();

	pStrBaseDlg = NULL;

}

cltStructureMngBasic::~cltStructureMngBasic()
{
	SI32 i;

	for(i = 0;i < MAX_VILLAGE_NUMBER;i++)
	{
		if(pclStruct[i])
		{
			delete pclStruct[i];
			pclStruct[i] = NULL;
		}
	}

	delete pclStructureRepairDlg;

}

void cltStructureMngBasic::Do_WM_INITDIALOG(SI32 charunique)
{
	SI32 id = 1;

	// 마을의 Unique를 구한다. 
	siVillageUnique = pclCM->CR[id]->GetCurrentVillageUnique();
	if(0 >= siVillageUnique)
		return;


	GetTitleText(siVillageUnique);

	// 건물 이름을 표시한다. 
	if( pStrBaseDlg ) {
		pStrBaseDlg->SetTitle( szTitle );

		pStrBaseDlg->GreetingMsg();
	}

	UpdateChiefSwitch	= false;
	bDrawPortraitSwitch	= false;
	
	// 건물에 대한 정보를 서버에 요청한다. 
	{
		cltGameMsgRequest_StrInfo clInfo(siVillageUnique, siRankType);
		cltMsg clMsg(GAMEMSG_REQUEST_STRINFO, sizeof(clInfo), (BYTE*)&clInfo);
		pclClient->pclCM->CR[id]->SendNetMsg((sPacketHeader*)&clMsg);
	}

	{
		cltSimpleRank clrank(siRankType, siVillageUnique);
		cltMsg clMsg(GAMEMSG_REQUEST_CHIEFINFO, sizeof(cltSimpleRank), (BYTE*)&clrank);
		pclClient->pclCM->CR[id]->SendNetMsg((sPacketHeader*)&clMsg);
	}

	//-----------------------------------------------------------
	// 건물 방문 퀘스트 중이라면, 
	//-----------------------------------------------------------
	
	if(siRankType == RANKTYPE_CITYHALL)
	{
		
		pclCM->CR[1]->DoQuestCheckAndAction(QUEST_CLEAR_COND_OPENCITYHALL);
	}
	else if(siRankType == RANKTYPE_STOCK)
	{
		// [영훈] 초보자 마을 : 초보자 퀘스트 수행시 앙카란 마을의 주식을 자동적으로 받는다
		if ( pclClient->IsCountrySwitch(Switch_TutorialVillage) )
		{
			SI16 siQuestType, siQuestUnique, siPara1, siPara2;
			SI16 siQuestClearCond = QUEST_CLEAR_COND_OPENSTOCKMARKET;

			if ( pclCM->CR[1]->pclCI->clQuestInfo.IsQuestGoing( siQuestClearCond, &siQuestType, &siQuestUnique, &siPara1, &siPara2) == true )
			{
				// 주민으로 있을 수 있는 레벨미만이고 초보자 마을의 주민이어야 한다
				if ( (pclCM->CR[1]->pclCI->clIP.GetLevel() < Const_BV_StockDividend_Level)
					&& (pclCM->CR[1]->pclCI->clBI.siHomeVillage == Const_Beginner_Village)
				)
				{
					cltMsg clMsg( GAMEMSG_REQUEST_GETBEGINNERVILLAGESTOCK, 0, NULL );
					pclClient->pclCM->CR[id]->SendNetMsg((sPacketHeader*)&clMsg);
				}
			}
		}
		
		pclCM->CR[1]->DoQuestCheckAndAction(QUEST_CLEAR_COND_OPENSTOCKMARKET);
	}
	else if(siRankType == RANKTYPE_HUNT)
	{
		pclCM->CR[1]->DoQuestCheckAndAction(QUEST_CLEAR_COND_OPENHUNT);
	}
	else if(siRankType == RANKTYPE_HOUSE)
	{
		pclCM->CR[1]->DoQuestCheckAndAction(QUEST_CLEAR_COND_OPENHOUSE);
	}
	else if(siRankType == RANKTYPE_REALESTATEMARKET)
	{
		pclCM->CR[1]->DoQuestCheckAndAction(QUEST_CLEAR_COND_OPENREALESTATEMARKET);
	}
	else if(siRankType == RANKTYPE_HORSEMARKET)
	{
		pclCM->CR[1]->DoQuestCheckAndAction(QUEST_CLEAR_COND_OPENHORSEMARKET);
	}


}


// 메인 설명창을 설정한다. 
BOOL cltStructureMngBasic::SetMainExplain(HWND hDlg, TCHAR* pstr)
{

	if( pStrBaseDlg ) {
	
		pStrBaseDlg->SetMainExplain( pstr );
	
	} else {

		HWND hwnd = GetDlgItem(hDlg, IDC_EDIT_BANK_EXPLAIN);

		if ( hwnd )
		{
			SetWindowText(hwnd, pstr);
		}
	}

	StringCchCopy( szMainExplain, 1024, pstr );

	dwLastExplainTick = GetTickCount();

	return TRUE;
}


void cltStructureMngBasic::DeleteTabDlg()
{
}

void cltStructureMngBasic::GetTitleText(SI32 villageunique)
{
	TCHAR strname[128]=TEXT("");
	if(pclClient->pclVillageStructureSet->GetStructureNameFromRankType(siRankType, strname, 128) == true)
	{
		StringCchPrintf(szTitle, 128, TEXT("%s - [%s]"), strname, pclClient->pclVillageManager->pclVillageInfo[villageunique]->szName);
	}
	else
	{
		StringCchCopy(szTitle, 128, TEXT(""));
	}
	
}


// 장의 정보를 보여준다. 
BOOL cltStructureMngBasic::ShowChief(HWND hDlg, SI32 dlgitem, cltSimplePerson* pclperson, TCHAR *paccountid)
{
	TCHAR buffer[256];
	HWND hwnd = GetDlgItem(hDlg, dlgitem);
	
	if(pclperson->GetPersonID())
	{
		StringCchPrintf(buffer, 256, TEXT("%s"), pclperson->GetName());
	}
	else
	{
		TCHAR* pText = GetTxtFromMgr(1287);
		StringCchPrintf(buffer, 256, pText);
	}

	SetWindowText(hwnd, buffer);

	/*DrawPortrait(paccountid);*/
	
	return TRUE;
}

// 초상화를 그려준다. 
void cltStructureMngBasic::DrawPortrait(TCHAR *paccountid)
{
	//TCHAR URL[MAX_PATH];

	//pclClient->GetCZProfileUrl( URL, paccountid );
}


// 서버 리턴값 처리 함수. 
void cltStructureMngBasic::ServerRtnValOperate()
{
	if(siServerResponseValue == 0)return ;

	SI32 index = 0;
	while(clStrTrnMsg[index].siMsg != 0)
	{
		if(clStrTrnMsg[index].siMsg == siServerResponseValue)
		{
			//SetMainExplain(m_hStrDlg, clStrTrnMsg[index].szMsg);

			TCHAR * ptext = GetTxtFromMgr(clStrTrnMsg[index].siMsgIndex,true);
			if ( ptext == NULL ) return ;

			if( pStrBaseDlg ) {
			
				//cyj 행수 입후보 등록메세지는 메세지 창 띄우도록 수정
				if (clStrTrnMsg[index].siMsg == SRVAL_CITYHALL_SUCCESSCANDIDATE)
				{
					if (((cltClient*)pclClient)->m_pDialog[ NOTIFYMSG_DLG ] != NULL)
					{
						ptext = GetTxtFromMgr(5739);
						TCHAR *pTitle = GetTxtFromMgr(4029);
						((cltClient*)pclClient)->m_pDialog[ NOTIFYMSG_DLG ]->SetText(pTitle, ptext);
					}
				}

				if (clStrTrnMsg[index].siMsg == SRVAL_POSTOFFICE_FAIL_SEND_FULLRECVBOX)
				{
					if (((cltClient*)pclClient)->m_pDialog[ NPOSTOFFICE_DLG ] != NULL)
					{
						TCHAR buf[256];
						TCHAR *pName = TEXT("");
						NPostOfficeDlg *officeDlg = (NPostOfficeDlg*)(((cltClient*)pclClient)->m_pDialog[ NPOSTOFFICE_DLG ]);

						if (officeDlg->m_pUserChildDlg[ 0 ]->IsShow())
						{
							pName = ((NPostOfficeSendItemDlg*)officeDlg->m_pUserChildDlg[ 0 ])->GetEditText( 0 );
						}
						
						StringCchPrintf(buf, 256, ptext, pName);
						_tcscpy(ptext, buf);
					}
				}
				//KHY - 0614 - 가차 아이템은 같은 계정간 캐릭터에 한하여 우편으로 주고 받을 수 있다.
				if (clStrTrnMsg[index].siMsg == SRVAL_POSTOFFICE_FAIL_SEND_ANOTHERPERSON)
				{
					if (((cltClient*)pclClient)->m_pDialog[ NPOSTOFFICE_DLG ] != NULL)
					{
						TCHAR buf[256];
						TCHAR *pName = TEXT("");
						NPostOfficeDlg *officeDlg = (NPostOfficeDlg*)(((cltClient*)pclClient)->m_pDialog[ NPOSTOFFICE_DLG ]);

						if (officeDlg->m_pUserChildDlg[ 0 ]->IsShow())
						{
							pName = ((NPostOfficeSendItemDlg*)officeDlg->m_pUserChildDlg[ 0 ])->GetEditText( 0 );
						}

						ptext = GetTxtFromMgr(20083);						
						StringCchPrintf(buf, 256, ptext, pName);
						_tcscpy(ptext, buf);
					}
				}
				

				if (clStrTrnMsg[index].siMsg == SRVAL_MOFUMOFUEVENT_FAIL_RESERVE || clStrTrnMsg[index].siMsg == SRVAL_MOFUMOFUEVENT_FAIL_ALREADY_RESERVE)
				{
					if (((cltClient*)pclClient)->m_pDialog[ NOTIFYMSG_DLG ] != NULL)
					{
						ptext = GetTxtFromMgr(7073);
						TCHAR *pTitle = GetTxtFromMgr(6694);
						((cltClient*)pclClient)->m_pDialog[ NOTIFYMSG_DLG ]->SetText(pTitle, ptext);
					}
				}

				pStrBaseDlg->SetMainExplain( ptext );

			}

			siServerResponseValue = 0;

			if( _tcscmp( clStrTrnMsg[index].szEffect , "" ) != 0  )
			{
				pclClient->PushEffect( pclClient->GetUniqueFromHash(clStrTrnMsg[index].szEffect), 0, 0);
			}
			return ;
		}

		index++;
	}

	MsgBox(TEXT("ServerRtnValOperate()"), TEXT("fd972:%d"), siServerResponseValue);
	
	return ;
}


// 서버로부터 받은 건물 정보를 가지고 클라이언트의 건물을  설정한다. 
void cltStructureMngBasic::SetClientStrInfo(cltStrInfo* pclinfo)
{
	 clClientStrInfo.Set(pclinfo);
}


cltStrInfo* cltStructureMngBasic::GetStrInfo(SI32 villageunique)
{
	if(villageunique <= 0 || villageunique >= MAX_VILLAGE_NUMBER)return NULL;
	if(pclStruct[villageunique] == NULL)return NULL;

	return pclStruct[villageunique]->GetStrInfo();
}

bool cltStructureMngBasic::GetHighestLevelVillage(SI32* villageunique,SI32* level)
{
	SI32 siLevel = 0 , siUnique = 1 ;

	for ( int i = 1 ; i < MAX_VILLAGE_NUMBER ; i ++ )
	{
		if(pclStruct[i] == NULL) continue;

		cltCityhallStrInfo* pclCityHall = &pclStruct[i]->GetStrInfo()->clCityhallStrInfo ;

		if ( siLevel < pclCityHall->siVillageLevel )
		{
			siLevel = pclCityHall->siVillageLevel ;
			siUnique = i ;
		}
	}

	if ( siUnique <= 0 || siUnique >= MAX_VILLAGE_NUMBER )
		return false ;

	*villageunique = siUnique ;
	*level = siLevel ;

	return true ;
}

void cltStructureMngBasic::SetStrInfo(SI32 villageunique, cltStrInfo* pclinfo)
{
	if(villageunique <= 0 || villageunique >= MAX_VILLAGE_NUMBER)return;
	if(pclStruct[villageunique] == NULL)return ;

	pclStruct[villageunique]->SetStrInfo(pclinfo);

}

// 특정 건물의 보유 자금을 설정한다. 
void cltStructureMngBasic::SetMoney(SI32 villageunique, cltMoney* pclmoney)
{
	cltStrInfo* pclinfo = GetStrInfo(villageunique);
	if(pclinfo == NULL)return ;

	pclinfo->clCommonInfo.clMoney.Set(pclmoney);
	
}

// 특정 건물의 보유 자본금을 업데이트 한다.
void cltStructureMngBasic::SetBaseMoney(SI32 villageunique, cltMoney* pclmoney)
{
	cltStrInfo* pclinfo = GetStrInfo(villageunique);
	if(pclinfo == NULL)return ;

	pclinfo->clCommonInfo.clBaseMoney.Set(pclmoney);

}

void cltStructureMngBasic::SetTax( SI32 villageunique, UI16 year, cltMoney* pclTax )
{
	cltStrInfo* pclinfo = GetStrInfo(villageunique);
	if(pclinfo == NULL)return ;

	pclinfo->clCommonInfo.clTaxInfo.SetTax( year, pclTax );

}

void cltStructureMngBasic::SetPaidTax( SI32 villageunique, UI16 year, cltMoney* pclPaidTax )
{
	cltStrInfo* pclinfo = GetStrInfo(villageunique);
	if(pclinfo == NULL)return ;

	pclinfo->clCommonInfo.clTaxInfo.SetPaidTax( year, pclPaidTax );

}

void cltStructureMngBasic::RequestStrInfo( SI32 strType )
{
	// 건물에 대한 정보를 서버에 요청한다. 

	SI32 id = 1;

	if(id)
	{
		cltGameMsgRequest_StrInfo clInfo(siVillageUnique, strType );
		cltMsg clMsg(GAMEMSG_REQUEST_STRINFO, sizeof(clInfo), (BYTE*)&clInfo);
		pclClient->pclCM->CR[id]->SendNetMsg((sPacketHeader*)&clMsg);
	}
}

void cltStructureMngBasic::CreateStructureRepairDlg( HINSTANCE hInst, HWND hParent )
{
	pclStructureRepairDlg->Create( hInst, hParent, this );
}

void cltStructureMngBasic::CommonAction(cltTime *pcltime)
{
	if(pcltime == NULL) return ;

	if( ((cltServer *)pclClient)->bCompleteDBInitAll == FALSE ) return;

	SI32 ref =	pclClient->pclVillageStructureSet->FindRefFromRankType( siRankType );

	if( ref == -1 ) return;

	SI64 siTotalItemMoney = 0;
	if( ((cltServer*)pclClient)->pclTime && ((cltServer*)pclClient)->pclTime->clDate.uiYear > 5 )
		siTotalItemMoney = pclClient->pclVillageStructureSet->pclVillageStructureInfo[ ref ]->siNeedMoney;
	else
		siTotalItemMoney = pclClient->pclVillageStructureSet->pclVillageStructureInfo[ ref ]->siNeedMoney / 10;

	bool bdaychangedswitch = pcltime->IsDayChanged();

	if( bdaychangedswitch )
	{
		if( pcltime->clDate.uiDay == 1 )
		{
			// 건물 내구도 소모
			for( int i = 1; i < MAX_VILLAGE_NUMBER; ++i )
			{
				if( pclClient->pclVillageManager->pclVillageInfo[ i ] )
				{
					// 주주가 한명도 없다면,
					if ( pclClient->pclVillageManager->pclVillageInfo[ i ]->clVillageVary.clInvestInfo.clInvestInfo[ 0 ].clPerson.GetPersonID() == 0 )
						continue;
					// 실제로 마을에 있는가?
					if ( pclClient->pclVillageManager->pclVillageInfo[ i ]->clVillageVary.clStructureInfo.IsThereStructure(siRankType) == FALSE ) 
						continue;

					// 초보자 마을 : 건물 내구도가 줄지 않는다
					if ( pclClient->IsCountrySwitch(Switch_TutorialVillage) )
					{
						//앙카란은 건물 내구도가 줄지 않는다.
						if( pclClient->pclVillageManager->pclVillageInfo[ i ]->siVillageUnique == Const_Beginner_Village ) 
						{
							continue;
						}
					}					

					SI32 tempRepairStrDura = pclStruct[ i ]->clStrInfo.clCommonInfo.siRepairStrDura;

					// 마을 안정기 이므로 건물 내구도가 닳지 않는다
					if( pclStruct[ i ]->clStrInfo.clCityhallStrInfo.usCurStatus == CITYHALL_BEING_STABLE )
						continue;

					// 수리를 완료하지 못했다면,(한달에 수리 목표량은 1000이다.)
					if( tempRepairStrDura < 1000 )
					{
						// kkm 
						// 주주총회일때도 수리를 한다
						SI32 siChangeDura = 1000 - tempRepairStrDura;
						if ( pclStruct[i]->clStrInfo.clCommonInfo.siStrDura <= 0 )
							siChangeDura = 0 ;

						sDBRequest_ChangeStrDura sendMsg( i, siRankType, -siChangeDura );
						pclClient->SendDBMsg(DBSELECT_BASE,  (sPacketHeader *)&sendMsg );
					}
					else
					{
						SI32 siChangeDura = 10000 - pclStruct[ i ]->clStrInfo.clCommonInfo.siStrDura;

						if( siChangeDura > 0 )
						{
							if( siChangeDura > 1000 )
								siChangeDura = 1000;

							sDBRequest_ChangeStrDura sendMsg( i, siRankType, siChangeDura );
							pclClient->SendDBMsg(DBSELECT_BASE,  (sPacketHeader *)&sendMsg );
						}
					}

					// 새로운 아이템을 설정한다
					{
						sDBRequest_SetStrRepairAmount sendMsg( i, siRankType );
						pclClient->SendDBMsg(DBSELECT_BASE,  (sPacketHeader *)&sendMsg );

					}
				}
			}
		}
	}
}

//void cltStructureMngBasic::CommonAction(cltTime *pcltime)
//{
//	
//	int i;
//
//	if(pcltime == NULL) return ;
//
//	if( ((cltServer *)pclClient)->bCompleteDBInitAll == FALSE ) return;
//
//	bool bdaychangedswitch = pcltime->IsDayChanged();
//
//	SI32 siRepairItemUnique;
//	SI32 siRepairItemNum;
//
//	SI32 siChiefPersonID;
//
//	SI32 ref =	pclClient->pclVillageStructureSet->FindRefFromRankType( siRankType );
//
//	if( ref == -1 ) return;
//
//	SI32 siTotalItemMoney = pclClient->pclVillageStructureSet->pclVillageStructureInfo[ ref ]->siNeedMoney;
//
//	if( bSetNeedItem == FALSE ) {
//
//		// 새로운 아이템 설정
//		for( i = 1; i < MAX_VILLAGE_NUMBER; ++i ) {
//
//			if( pclClient->pclVillageManager->pclVillageInfo[ i ] ) {
//
//				if( pclStruct[ i ]->clStrInfo.clCommonInfo.siNeedItemUnique == 0 ) {
//
//					pclClient->pclItemManager->GetItemForStrRepair( siTotalItemMoney, &siRepairItemUnique, &siRepairItemNum );
//
//					sDBRequest_SetStrRepairItem sendMsg( i, siRankType, siRepairItemUnique, siRepairItemNum );
//					pclClient->SendDBMsg(DBSELECT_BASE,  (sPacketHeader *)&sendMsg );
//
//					// 행수에게 쪽지 보냄..
//					siChiefPersonID = pclClient->pclVillageManager->pclVillageInfo[ i ]->clVillageVary.clRankPerson[ siRankType ].GetPersonID();
//
//					cltLetterMsg_StructureRepairItem clletter( i, siRankType, siRepairItemUnique, siRepairItemNum );
//					((cltServer *)pclClient)->SendLetterMsg( siChiefPersonID, (cltLetterHeader*)&clletter);
//
//				}
//				
//			}
//
//		}
//
//		bSetNeedItem = TRUE;
//	}
//	
//	if( bdaychangedswitch )
//	{
//		if( pcltime->clDate.uiDay == 1 ) {
//
//			// 건물 내구도 소모
//			for( i = 1; i < MAX_VILLAGE_NUMBER; ++i ) {
//
//				if( pclClient->pclVillageManager->pclVillageInfo[ i ] ) {
//
//					// 주주가 한명도 없다면,
//					if( pclClient->pclVillageManager->pclVillageInfo[ i ]->clVillageVary.clInvestInfo.clInvestInfo[ 0 ].clPerson.GetPersonID() == 0 ) continue;
//					// 실제로 마을에 있는가?
//					if( pclClient->pclVillageManager->pclVillageInfo[ i ]->clVillageVary.clStructureInfo.IsThereStructure(siRankType) == FALSE ) continue;
//
//					SI32 useitemnum = pclStruct[ i ]->clStrInfo.clCommonInfo.siUseItemNum;
//					SI32 needitemnum = pclStruct[ i ]->clStrInfo.clCommonInfo.siNeedItemNum;
//
//					if( needitemnum == 0 ) continue;
//
//					// 마을 안정기 이므로 건물 내구도가 닳지 않는다
//					if( pclStruct[ i ]->clStrInfo.clCityhallStrInfo.usCurStatus == CITYHALL_BEING_STABLE )
//						continue;
//
//					// 수리를 완료하지 못했다면,
//					if( useitemnum < needitemnum )
//					{
//
//						// 주주총회가 아닐때만,
//						cltCityHall *pclCityHall = (cltCityHall *)pclClient->pclCityHallManager->pclStruct[ i ];
//						if( pclCityHall->clGeneralMeetingInfo.siMatterType == 0 ) {
//
//							SI32 siChangeDura = 1000 - (SI32)(1000. * ( (float)useitemnum / (float)needitemnum ) );
//							if ( pclStruct[i]->clStrInfo.clCommonInfo.siStrDura <= 0 )
//								siChangeDura = 0 ;
///*
//							sDBRequest_ChangeStrDura sendMsg( i, siRankType, -siChangeDura );
//							pclClient->SendDBMsg(DBSELECT_BASE,  (sPacketHeader *)&sendMsg );
//*/
//						}
//
//					} else {
//						SI32 siChangeDura = 10000 - pclStruct[ i ]->clStrInfo.clCommonInfo.siStrDura;
//
//						if( siChangeDura > 0 ) {
//
//							if( siChangeDura > 1000 ) siChangeDura = 1000;
//
//							sDBRequest_ChangeStrDura sendMsg( i, siRankType, siChangeDura );
//							pclClient->SendDBMsg(DBSELECT_BASE,  (sPacketHeader *)&sendMsg );
//						}
//					}
//
//					// 새로운 아이템을 설정한다
//					{
//						pclClient->pclItemManager->GetItemForStrRepair( siTotalItemMoney, &siRepairItemUnique, &siRepairItemNum );
//
//						sDBRequest_SetStrRepairItem sendMsg( i, siRankType, siRepairItemUnique, siRepairItemNum );
//						pclClient->SendDBMsg(DBSELECT_BASE,  (sPacketHeader *)&sendMsg );
//					}
//				}
//			}
//		}
//	}
//}



void cltCityHallInOutMoneyInfo::AddInOutMoneyInfo( SI32 strType, SI32 inoutcode, cltDate *pclDate, cltMoney *pclInOutMoney, cltMoney *pclCityhallMoney )
{

	if( siCount == MAX_INOUTMONEY_RECORD ) {
	
		for( int i = 0; i < MAX_INOUTMONEY_RECORD - 1; ++i ) {

			clInOutMoneyUnitInfo[ i ] = clInOutMoneyUnitInfo[ i + 1 ];
		}

		clInOutMoneyUnitInfo[ i ].siStrType = strType;
		clInOutMoneyUnitInfo[ i ].siInOutCode = inoutcode;
		clInOutMoneyUnitInfo[ i ].clDate.Set( pclDate );
		clInOutMoneyUnitInfo[ i ].clInOutMoney.Set( pclInOutMoney );
		clInOutMoneyUnitInfo[ i ].clCityhallMoney.Set( pclCityhallMoney );

	} else {
			
		clInOutMoneyUnitInfo[ siCount ].siStrType = strType;
		clInOutMoneyUnitInfo[ siCount ].siInOutCode = inoutcode;
		clInOutMoneyUnitInfo[ siCount ].clDate.Set( pclDate );
		clInOutMoneyUnitInfo[ siCount ].clInOutMoney.Set( pclInOutMoney );
		clInOutMoneyUnitInfo[ siCount ].clCityhallMoney.Set( pclCityhallMoney );
		
		++siCount;
	}

}

void cltDividendInfo::AddDividendInfo( cltDate *pclDate, SI32 siTotalStock, cltMoney *pclMoney )
{

	if( siCount == 0 ) {

		clDividendUnitInfo[ 0 ].clDate.Set( pclDate );
		clDividendUnitInfo[ 0 ].siTotalStock = siTotalStock;
		clDividendUnitInfo[ 0 ].clDividendPrice.Set( pclMoney );

		siCount = 1;

	} else {
		
		for( int i = siCount - 1; i > 0; --i ) {

			clDividendUnitInfo[ i ] = clDividendUnitInfo[ i - 1 ];

		}

		clDividendUnitInfo[ 0 ].clDate.Set( pclDate );
		clDividendUnitInfo[ 0 ].siTotalStock = siTotalStock;
		clDividendUnitInfo[ 0 ].clDividendPrice.Set( pclMoney );

		if( siCount < MAX_DIVIDEND_RECORD ) siCount++;

	}
}

void cltTaxInfo::SetTax( UI16 year, cltMoney *pclTax )
{
	
	int i, j; 
	for( i = 0; i < siCount; ++i ) {

		if( year > clTaxUnitInfo[ i ].usYear ) {
			
			for( j = siCount - 2; j > i; --j ) {

				clTaxUnitInfo[ j + 1 ] = clTaxUnitInfo[ j ];
			}

			clTaxUnitInfo[ i ].usYear = year;
			clTaxUnitInfo[ i ].clDueTax.Set( pclTax );
			clTaxUnitInfo[ i ].clPaidTax.Init();

			if( siCount < MAX_TAX_RECORD_YEAR ) siCount++;

			return;
		}

		if( year == clTaxUnitInfo[ i ].usYear ) {

			clTaxUnitInfo[ i ].clDueTax.Set( pclTax );

			return;
		}
	}
	
	if( siCount == 0 ) {
		clTaxUnitInfo[ 0 ].usYear = year;
		clTaxUnitInfo[ 0 ].clDueTax.Set( pclTax );
		clTaxUnitInfo[ 0 ].clPaidTax.Init();

		siCount = 1;
	}
}

void cltTaxInfo::SetPaidTax( UI16 year, cltMoney *pclTax )
{

	int i, j; 
	for( i = 0; i < siCount; ++i ) {

		if( year > clTaxUnitInfo[ i ].usYear ) {
			
			for( j = siCount - 2; j > i; --j ) {

				clTaxUnitInfo[ j + 1 ] = clTaxUnitInfo[ j ];
			}

			clTaxUnitInfo[ i ].usYear = year;
			clTaxUnitInfo[ i ].clDueTax.Init();
			clTaxUnitInfo[ i ].clPaidTax.Set( pclTax );

			if( siCount < MAX_TAX_RECORD_YEAR ) siCount++;

			return;
		}

		if( year == clTaxUnitInfo[ i ].usYear ) {

			clTaxUnitInfo[ i ].clPaidTax.Increase( pclTax );

			return;
		}
	}
	
	if( siCount == 0 ) {
		clTaxUnitInfo[ 0 ].usYear = year;
		clTaxUnitInfo[ 0 ].clDueTax.Init();
		clTaxUnitInfo[ 0 ].clPaidTax.Set( pclTax );

		siCount = 1;
	}

}

