enum MISSION_REWARD_TYPE
{
	MISSION_REWARD_TYPE_ITEM,
	MISSION_REWARD_TYPE_EXP,
	MISSION_REWARD_TYPE_SKILLEXP,
	MISSION_REWARD_TYPE_FAMEEXP,
	MISSION_REWARD_TYPE_MONEY,
	MISSION_REWARD_TYPE_INC_SPEED,
	MISSION_REWARD_TYPE_NAMING,
};

enum MISSION_SPECIALVALUE
{
	MISSION_SPECIALVALUE_DAILYQUEST_HIDDEN,
};

#define PERSON_MISSION_COUNT				5
#define MAX_MISSON_DATA_COUNT				200
#define MAX_MISSON_REWARD_COUNT				3
#define MAX_MISSON_UNIQUESTRING_LENGTH		60


