// 파티매칭
#ifndef _DEFINES_PARTYMATCHING_H_
#define _DEFINES_PARTYMATCHING_H_






#define MAX_PARTYMATCHING_LIST_SEND_SIZE		10		// 파티먜칭 리스트를 클라에 보낼때 최대 몇개씩 보낼지에 대한 define
#define MAX_PARTYMATCHING_PARTYNAME_LENGTH		42		// 파티매칭의 파티이름 최대 길이 (최대 64)
#define MAX_PARTYMATCHING_GREETING_LENGTH		122		// 파티매칭의 인사말 최대 길이 (최대 128)




// 클라 쪽의 ui인덱스와 같고, 또한 questmgr의 리소스 저장 배열의 인덱스와도 같다. 퀘스트 매니저와 달라질시 변경 필요
enum PartyMatchingLevelType
{
	PARTYMATCHING_GROUP_01 = 0,
	PARTYMATCHING_GROUP_02,
	PARTYMATCHING_GROUP_03,
	PARTYMATCHING_GROUP_04,
	PARTYMATCHING_GROUP_05,
	PARTYMATCHING_GROUP_06,
	PARTYMATCHING_GROUP_07,
	PARTYMATCHING_GROUP_08,
	PARTYMATCHING_GROUP_09,
	PARTYMATCHING_GROUP_10,

	PARTYMATCHING_GROUP_MAX,
};

enum PartyMatchingResponseException
{
	PARTYMATCHING_NONE_EXCEPTION	= 0x0001,
	PARTYMATCHING_ALREADY_PARTYMEMBER		= 0x0001 << 1,
	PARTYMATCHING_WRONG_LEVELCONDITION		= 0x0001 << 2,
	PARTYMATCHING_WRONG_CHARID				= 0x0001 << 3,

	PARTYMATCHING_MAX_EXCEPTION		= 0xffff,
};



#endif			//_DEFINES_PARTYMATCHING_H_