//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DLGEditorS.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_SPLITTERWNDVIEW             103
#define IDD_DLGPROPERTYDLG              104
#define IDR_MAINFRAME                   128
#define IDR_DLGEditorSTYPE              129
#define IDD_DLGBAR_BASE                 130
#define IDD_DIALOG_SETTINGS             131
#define IDD_DIALOG_BUTTON_PROPERTIES    132
#define IDD_DIALOG_EDIT_PROPERTIES      133
#define IDD_DIALOG_EDITBOX              133
#define IDD_DIALOG_COMBOBOX_PROPERTIES  134
#define IDD_DIALOG_EDITBOX_PROPERTIES   135
#define IDD_DIALOG_STATIC_TEXT_PROPERTIES 136
#define IDD_DIALOG_LISTBOX_PROPERTIES   137
#define IDD_DIALOG_IMAGE_STATIC_PROPERTIES 138
#define IDD_DIALOG_LISTVIEW_PROPERTIES  139
#define IDD_DIALOG_CHECKBOX_PROPERTIES  140
#define IDD_DIALOG1                     141
#define IDD_DIALOG_RADIOBUTTON_PROPERTIES 141
#define IDD_DIALOG_OUTLINE_PROPERTIES   142
#define IDD_DIALOG_CHATEDIT_PROPERTIES  143
#define IDC_EDIT_WIDTH                  1000
#define IDC_EDIT_DLG_WIDTH              1000
#define IDC_EDIT_HEIGHT                 1001
#define IDC_EDIT_KIND_NAME              1001
#define IDC_EDIT_BTN_KIND_NAME          1001
#define IDC_EDIT_DLG_HEIGHT             1001
#define IDC_EDIT_GRID_WIDTH             1002
#define IDC_EDIT_GRID_HEIGHT            1003
#define IDC_EDIT_LEFT                   1004
#define IDC_EDIT_TOP                    1005
#define IDC_EDIT_RIGHT                  1006
#define IDC_EDIT_BOTTOM                 1007
#define IDC_EDIT_DLG_KIND_NAME          1008
#define IDC_EDIT_DEFAULT_PATH           1008
#define IDC_BUTTON_APPLY                1009
#define IDC_EDIT_DEFAULT_PATH2          1009
#define IDC_EDIT_DEFAULT_TEXTMGR_PATH   1009
#define IDC_EDIT_IMAGE_FULLPATH         1010
#define IDC_BUTTON1                     1011
#define IDC_BUTTON_SEARCH               1011
#define IDC_BUTTON_DLG_APPLY            1011
#define IDC_BUTTON_BTN_PATH_EMPTY       1011
#define IDC_EDIT_X_COORD                1012
#define IDC_EDIT_DLG_X_COORD            1012
#define IDC_EDIT_Y_COORD                1013
#define IDC_EDIT_DLG_Y_COORD            1013
#define IDC_EDIT_BTN_WIDTH              1014
#define IDC_BUTTON_DLG_PATH_EMPTY2      1014
#define IDC_EDIT_BTN_HEIGHT             1015
#define IDC_EDIT_BTN_TILE               1016
#define IDC_EDIT_BTN_BG_TILE            1016
#define IDC_EDIT_START_FONT             1017
#define IDC_EDIT_DLG_START_FONT         1017
#define IDC_EDIT_BTN_TILE_IMAGE_NUM     1017
#define IDC_EDIT_BTN_BG_TILE_IMAGE_NUM  1017
#define IDC_EDIT_BG_WIDTH               1018
#define IDC_EDIT_DLG_BG_WIDTH           1018
#define IDC_EDIT_BG_HEIGHT              1019
#define IDC_EDIT_DLG_BG_HEIGHT          1019
#define IDC_EDIT_ID                     1020
#define IDC_EDIT_DLG_CALLBACK_POINTER   1020
#define IDC_EDIT_CAPTION                1021
#define IDC_EDIT_BTN_CAPTION            1021
#define IDC_EDIT_DLG_TITLE_STR          1021
#define IDC_EDIT_BTN_TEXT               1021
#define IDC_EDIT_GROUP_NUM              1022
#define IDC_EDIT_DLG_TITLE_VISIBLE      1022
#define IDC_EDIT_BTN_ANIMATION          1022
#define IDC_BUTTON2                     1023
#define IDC_HIDE                        1023
#define IDC_EDIT_DLG_MOVABLE            1023
#define IDC_BUTTON_STATT_HIDE           1023
#define IDC_EDIT_BTN_ID                 1024
#define IDC_EDIT_DLG_CLOSABLE           1024
#define IDC_EDIT_BTN_X_COORD            1025
#define IDC_EDIT_DLG_TEXT_COLOR2        1025
#define IDC_EDIT_DLG_TEXT_COLOR         1025
#define IDC_EDIT_BTN_Y_COORD            1026
#define IDC_EDIT_DLG_TILE_IMAGE_NUM2    1026
#define IDC_EDIT_DLG_BG_TILE_IMAGE_NUM2 1026
#define IDC_EDIT_DLG_BG_TILE_IMAGE_NUM  1026
#define IDC_EDIT_BTN_IMAGE_FULLPATH     1027
#define IDC_EDIT_DLG_PARENT_ID          1027
#define IDC_BUTTON_BTN_SEARCH           1028
#define IDC_EDIT_DLG_CALLBACK_POINTER3  1028
#define IDC_EDIT_DLG_CHILD_ID           1028
#define IDC_EDIT_DLG_CHILD_FILENAMES    1028
#define IDC_EDIT_BTN_BG_WIDTH           1029
#define IDC_EDIT_BTN_BG_HEIGHT          1030
#define IDC_EDIT_BTN_START_FONT         1031
#define IDC_EDIT_BTN_GROUP_NUM          1032
#define IDC_EDIT_DLG_ID                 1033
#define IDC_EDIT_BTN_TEXT_STYLE         1033
#define IDC_EDIT_DLG_IMAGE_FULLPATH     1034
#define IDC_EDIT_BTN_TEXT_SIZE          1034
#define IDC_BUTTON_DLG_SEARCH           1035
#define IDC_EDIT_BTN_START_FONT2        1035
#define IDC_EDIT_BTN_TEXT_COLOR         1035
#define IDC_EDIT_DLG_TILE               1036
#define IDC_EDIT_DLG_BG_TILE            1036
#define IDC_BUTTON_DLG_CLOSE            1037
#define IDC_EDIT_DLG_TEXT_STYLE2        1038
#define IDC_EDIT_DLG_TEXT_STYLE         1038
#define IDC_EDIT_CBX_KIND_NAME          1039
#define IDC_EDIT_DLG_TEXT_SIZE2         1039
#define IDC_EDIT_DLG_TEXT_SIZE          1039
#define IDC_EDIT_CBX_ID                 1040
#define IDC_EDIT_CBX_X_COORD            1041
#define IDC_EDIT_CBX_Y_COORD            1042
#define IDC_EDIT_CBX_WIDTH              1043
#define IDC_EDIT_CBX_HEIGHT             1044
#define IDC_EDIT_CBX_IMAGE_FULLPATH     1045
#define IDC_BUTTON_CBX_SEARCH           1046
#define IDC_EDIT_CBX_BG_WIDTH           1047
#define IDC_EDIT_CBX_BG_HEIGHT          1048
#define IDC_EDIT_CBX_TILE               1049
#define IDC_EDIT_CBX_BG_TILE            1049
#define IDC_EDIT_CBX_START_FONT         1050
#define IDC_EDIT_CBX_GROUP_NUM          1051
#define IDC_EDIT_CBX_POPUP_HEIGHT       1052
#define IDC_EDIT_CBX_LINE_HEIGHT        1053
#define IDC_EDIT_ETB_KIND_NAME          1054
#define IDC_EDIT_ETB_ID                 1055
#define IDC_EDIT_ETB_X_COORD            1056
#define IDC_EDIT_ETB_Y_COORD            1057
#define IDC_EDIT_ETB_WIDTH              1058
#define IDC_EDIT_ETB_HEIGHT             1059
#define IDC_EDIT_ETB_IMAGE_FULLPATH     1060
#define IDC_BUTTON_ETB_SEARCH           1061
#define IDC_EDIT_ETB_BG_WIDTH           1062
#define IDC_EDIT_ETB_BG_HEIGHT          1063
#define IDC_EDIT_ETB_TILE               1064
#define IDC_EDIT_ETB_BG_TILE            1064
#define IDC_EDIT_ETB_START_FONT         1065
#define IDC_EDIT_ETB_GROUP_NUM          1066
#define IDC_EDIT_ETB_TEXT               1067
#define IDC_EDIT_ETB_MULTILINE          1068
#define IDC_EDIT_ETB_READONLY           1069
#define IDC_EDIT_STATT_KIND_NAME        1069
#define IDC_EDIT_STATT_ID               1070
#define IDC_EDIT_LSTB_FIXED_ROW_VISIBLE 1070
#define IDC_EDIT_STATT_X_COORD          1071
#define IDC_EDIT_STATT_Y_COORD          1072
#define IDC_EDIT_STATT_WIDTH            1073
#define IDC_EDIT_STATT_HEIGHT           1074
#define IDC_EDIT_STATT_IMAGE_FULLPATH   1075
#define IDC_BUTTON_STATT_SEARCH         1076
#define IDC_EDIT_STATT_BG_WIDTH         1077
#define IDC_EDIT_STATT_BG_HEIGHT        1078
#define IDC_EDIT_STATT_TILE             1079
#define IDC_EDIT_STATT_BG_TILE          1079
#define IDC_EDIT_STATT_START_FONT       1080
#define IDC_EDIT_STATT_GROUP_NUM        1081
#define IDC_EDIT_STATT_TEXT             1082
#define IDC_EDIT_LSTB_KIND_NAME         1083
#define IDC_EDIT_LSTB_ID                1084
#define IDC_EDIT_LSTB_X_COORD           1085
#define IDC_EDIT_LSTB_Y_COORD           1086
#define IDC_EDIT_LSTB_WIDTH             1087
#define IDC_EDIT_LSTB_HEIGHT            1088
#define IDC_EDIT_LSTB_IMAGE_FULLPATH    1089
#define IDC_BUTTON_LSTB_SEARCH          1090
#define IDC_EDIT_LSTB_BG_WIDTH          1091
#define IDC_EDIT_LSTB_BG_HEIGHT         1092
#define IDC_EDIT_LSTB_TILE              1093
#define IDC_EDIT_LSTB_BG_TILE           1093
#define IDC_EDIT_LSTB_START_FONT        1094
#define IDC_EDIT_LSTB_GROUP_NUM         1095
#define IDC_EDIT_LSTB_MULTILINE         1096
#define IDC_EDIT_LSTB_MULTISELECTION    1097
#define IDC_EDIT_LSTB_LINE_HEIGHT       1098
#define IDC_EDIT_IMGSTT_KIND_NAME       1099
#define IDC_EDIT_IMGSTT_ID              1100
#define IDC_EDIT_IMGSTT_X_COORD         1101
#define IDC_EDIT_IMGSTT_Y_COORD         1102
#define IDC_EDIT_IMGSTT_WIDTH           1103
#define IDC_EDIT_IMGSTT_HEIGHT          1104
#define IDC_EDIT_IMGSTT_IMAGE_FULLPATH  1105
#define IDC_BUTTON_IMGSTT_SEARCH        1106
#define IDC_EDIT_IMGSTT_BG_WIDTH        1107
#define IDC_EDIT_IMGSTT_BG_HEIGHT       1108
#define IDC_EDIT_IMGSTT_TILE            1109
#define IDC_EDIT_IMGSTT_BG_TILE         1109
#define IDC_EDIT_IMGSTT_START_FONT      1110
#define IDC_EDIT_IMGSTT_GROUP_NUM       1111
#define IDC_EDIT_LSTV_KIND_NAME         1113
#define IDC_EDIT_LSTV_ID                1114
#define IDC_EDIT_LSTV_X_COORD           1115
#define IDC_EDIT_LSTV_Y_COORD           1116
#define IDC_EDIT_LSTV_WIDTH             1117
#define IDC_EDIT_LSTV_HEIGHT            1118
#define IDC_EDIT_LSTV_IMAGE_FULLPATH    1119
#define IDC_BUTTON_LSTV_SEARCH          1120
#define IDC_EDIT_LSTV_BG_WIDTH          1121
#define IDC_EDIT_LSTV_BG_HEIGHT         1122
#define IDC_EDIT_LSTV_TILE              1123
#define IDC_EDIT_LSTV_BG_TILE           1123
#define IDC_EDIT_LSTV_START_FONT        1124
#define IDC_EDIT_LSTV_GROUP_NUM         1125
#define IDC_EDIT_LSTV_ITEM_EMPTY        1127
#define IDC_BUTTON_TEXT_SEARCH          1127
#define IDC_BUTTON_STATT_TEXT_SEARCH    1127
#define IDC_EDIT_LSTV_ITEM_COUNT_VISIBLE 1128
#define IDC_EDIT_CBX_TILE_IMAGE_NUM     1128
#define IDC_EDIT_CBX_BG_TILE_IMAGE_NUM  1128
#define IDC_EDIT_LSTV_ITEM_TOOLTIP_USABLE 1129
#define IDC_BUTTON_CBX_PATH_EMPTY       1129
#define IDC_EDIT_LSTV_ITEM_TOOLTIP_WIDTH 1130
#define IDC_EDIT_CBX_TEXT_COLOR         1130
#define IDC_EDIT_LSTV_ITEM_TOOLTIP_HEIGHT 1131
#define IDC_EDIT_CBX_TEXT_STYLE         1131
#define IDC_EDIT_LSTV_ITEM_START_X      1132
#define IDC_EDIT_CBX_TEXT_SIZE          1132
#define IDC_EDIT_LSTV_ITEM_START_Y      1133
#define IDC_EDIT_ETB_TILE_IMAGE_NUM     1133
#define IDC_EDIT_ETB_BG_TILE_IMAGE_NUM  1133
#define IDC_EDIT_LSTV_ITEM_OFFSET_X     1134
#define IDC_EDIT_ETB_TEXT_COLOR         1134
#define IDC_EDIT_LSTV_ITEM_OFFSET_Y     1135
#define IDC_EDIT_ETB_TEXT_STYLE         1135
#define IDC_EDIT_ETB_TEXT_SIZE          1136
#define IDC_BUTTON_LSTV_TEXT_SEARCH     1136
#define IDC_EDIT_IMGSTT_TILE_IMAGE_NUM  1137
#define IDC_EDIT_IMGSTT_BG_TILE_IMAGE_NUM 1137
#define IDC_EDIT_LSTV_ITEM_SIZE_X       1137
#define IDC_EDIT_IMGSTT_TEXT_COLOR      1138
#define IDC_EDIT_LSTV_ITEM_OFFSET_Y3    1138
#define IDC_EDIT_LSTV_ITEM_SIZE_Y       1138
#define IDC_EDIT_IMGSTT_TEXT_STYLE      1139
#define IDC_EDIT_IMGSTT_TEXT_SIZE       1140
#define IDC_EDIT_LSTB_TILE_IMAGE_NUM    1141
#define IDC_EDIT_LSTB_BG_TILE_IMAGE_NUM 1141
#define IDC_EDIT_LSTB_TEXT_COLOR        1142
#define IDC_EDIT_LSTB_TEXT_STYLE        1143
#define IDC_EDIT_LSTB_TEXT_SIZE         1144
#define IDC_EDIT_LSTV_TILE_IMAGE_NUM    1145
#define IDC_EDIT_LSTV_BG_TILE_IMAGE_NUM 1145
#define IDC_EDIT_LSTV_TEXT_COLOR        1146
#define IDC_EDIT_LSTV_TEXT_STYLE        1147
#define IDC_EDIT_LSTV_TEXT_SIZE         1148
#define IDC_EDIT_STATT_TILE_IMAGE_NUM   1149
#define IDC_EDIT_STATT_BG_TILE_IMAGE_NUM 1149
#define IDC_EDIT_STATT_TEXT_COLOR       1150
#define IDC_EDIT_STATT_TEXT_STYLE       1151
#define IDC_EDIT_STATT_TEXT_SIZE        1152
#define IDC_BUTTON_DLG_TEXT_SEARCH      1154
#define IDC_BUTTON_BTN_TEXT_SEARCH      1155
#define IDC_BUTTON_BTN_APPLY            1156
#define IDC_BUTTON_BTN_HIDE             1157
#define IDC_BUTTON_CBX_TEXT_SEARCH      1158
#define IDC_BUTTON_CBX_APPLY            1159
#define IDC_BUTTON_CBX_HIDE             1160
#define IDC_BUTTON_ETB_PATH_EMPTY       1161
#define IDC_BUTTON_ETB_TEXT_SEARCH      1162
#define IDC_BUTTON_ETB_APPLY            1163
#define IDC_BUTTON_ETB_HIDE             1164
#define IDC_BUTTON_IMGSTT_PATH_EMPTY    1165
#define IDC_BUTTON_IMGSTT_TEXT_SEARCH   1166
#define IDC_BUTTON_IMGSTT_APPLY         1167
#define IDC_BUTTON_IMGSTT_HIDE          1168
#define IDC_BUTTON_LSTB_PATH_EMPTY      1169
#define IDC_BUTTON_LSTB_TEXT_SEARCH     1170
#define IDC_BUTTON_LSTB_APPLY           1171
#define IDC_BUTTON_LSTB_HIDE            1172
#define IDC_BUTTON_LSTV_PATH_EMPTY      1173
#define IDC_BUTTON_LSTV_APPLY           1174
#define IDC_BUTTON_LSTV_HIDE            1175
#define IDC_BUTTON_STATT_PATH_EMPTY     1176
#define IDC_BUTTON_STATT_APPLY          1177
#define IDC_EDIT_CHKB_KIND_NAME         1178
#define IDC_EDIT_CHKB_ID                1179
#define IDC_EDIT_CHKB_X_COORD           1180
#define IDC_EDIT_CHKB_Y_COORD           1181
#define IDC_EDIT_CHKB_WIDTH             1182
#define IDC_EDIT_CHKB_HEIGHT            1183
#define IDC_EDIT_CHKB_IMAGE_FULLPATH    1184
#define IDC_BUTTON_CHKB_PATH_EMPTY      1185
#define IDC_BUTTON_CHKB_SEARCH          1186
#define IDC_EDIT_CHKB_BG_WIDTH          1187
#define IDC_EDIT_CHKB_BG_HEIGHT         1188
#define IDC_EDIT_CHKB_BG_TILE           1189
#define IDC_EDIT_CHKB_BG_TILE_IMAGE_NUM 1190
#define IDC_EDIT_CHKB_START_FONT        1191
#define IDC_EDIT_CHKB_TEXT_COLOR        1192
#define IDC_EDIT_CHKB_TEXT_STYLE        1193
#define IDC_EDIT_CHKB_TEXT_SIZE         1194
#define IDC_BUTTON_CHKB_TEXT_SEARCH     1195
#define IDC_EDIT_CHKB_GROUP_NUM         1196
#define IDC_EDIT_CHKB_TEXT              1197
#define IDC_BUTTON_CHKB_APPLY           1198
#define IDC_BUTTON_CHKB_HIDE            1199
#define IDC_EDIT_RADB_KIND_NAME         1200
#define IDC_EDIT_RADB_ID                1201
#define IDC_EDIT_RADB_X_COORD           1202
#define IDC_EDIT_RADB_Y_COORD           1203
#define IDC_EDIT_RADB_WIDTH             1204
#define IDC_BUTTON_RADB_PATH_EMPTY      1205
#define IDC_EDIT_RADB_IMAGE_FULLPATH    1206
#define IDC_BUTTON_RADB_SEARCH          1207
#define IDC_EDIT_RADB_BG_WIDTH          1208
#define IDC_EDIT_RADB_BG_HEIGHT         1209
#define IDC_EDIT_RADB_BG_TILE           1210
#define IDC_EDIT_RADB_BG_TILE_IMAGE_NUM 1211
#define IDC_EDIT_RADB_START_FONT        1212
#define IDC_EDIT_RADB_TEXT_COLOR        1213
#define IDC_EDIT_RADB_TEXT_STYLE        1214
#define IDC_EDIT_RADB_TEXT_SIZE         1215
#define IDC_EDIT_RADB_GROUP_NUM         1216
#define IDC_BUTTON_RADB_TEXT_SEARCH     1217
#define IDC_EDIT_RADB_TEXT              1218
#define IDC_BUTTON_RADB_APPLY           1219
#define IDC_BUTTON_RADB_HIDE            1220
#define IDC_EDIT_RADB_HEIGHT            1221
#define IDC_EDIT_RADB_TEXT2             1222
#define IDC_EDIT_RADB_GROUP_ID          1222
#define IDC_EDIT_OUTLNE_KIND_NAME       1222
#define IDC_EDIT_OUTLNE_ID              1223
#define IDC_EDIT_OUTLNE_X_COORD         1224
#define IDC_EDIT_OUTLNE_Y_COORD         1225
#define IDC_EDIT_OUTLNE_WIDTH           1226
#define IDC_EDIT_OUTLNE_HEIGHT          1227
#define IDC_BUTTON_OUTLNE_PATH_EMPTY    1228
#define IDC_EDIT_OUTLNE_IMAGE_FULLPATH  1229
#define IDC_BUTTON_OUTLNE_SEARCH        1230
#define IDC_EDIT_OUTLNE_BG_WIDTH        1231
#define IDC_EDIT_OUTLNE_BG_HEIGHT       1232
#define IDC_EDIT_OUTLNE_BG_TILE         1233
#define IDC_EDIT_OUTLNE_BG_TILE_IMAGE_NUM 1234
#define IDC_EDIT_OUTLNE_START_FONT      1235
#define IDC_EDIT_OUTLNE_TEXT_COLOR      1236
#define IDC_EDIT_OUTLNE_TEXT_STYLE      1237
#define IDC_EDIT_OUTLNE_TEXT_SIZE       1238
#define IDC_BUTTON_OUTLNE_TEXT_SEARCH   1239
#define IDC_EDIT_OUTLNE_GROUP_NUM       1240
#define IDC_EDIT_OUTLNE_TEXT            1241
#define IDC_BUTTON_OUTLNE_APPLY         1242
#define IDC_BUTTON_OUTLNE_HIDE          1243
#define IDC_EDIT_CHTETB_KIND_NAME       1244
#define IDC_EDIT_CHTETB_ID              1245
#define IDC_EDIT_CHTETB_X_COORD         1246
#define IDC_EDIT_CHTETB_Y_COORD         1247
#define IDC_EDIT_CHTETB_WIDTH           1248
#define IDC_EDIT_CHTETB_HEIGHT          1249
#define IDC_BUTTON_CHTETB_PATH_EMPTY    1250
#define IDC_EDIT_CHTETB_IMAGE_FULLPATH  1251
#define IDC_BUTTON_CHTETB_SEARCH        1252
#define IDC_EDIT_CHTETB_BG_WIDTH        1253
#define IDC_EDIT_CHTETB_BG_HEIGHT       1254
#define IDC_EDIT_CHTETB_BG_TILE         1255
#define IDC_EDIT_CHTETB_BG_TILE_IMAGE_NUM 1256
#define IDC_EDIT_CHTETB_START_FONT      1257
#define IDC_EDIT_CHTETB_TEXT_COLOR      1258
#define IDC_EDIT_CHTETB_TEXT_STYLE      1259
#define IDC_EDIT_CHTETB_TEXT_SIZE       1260
#define IDC_BUTTON_CHTETB_TEXT_SEARCH   1261
#define IDC_EDIT_CHTETB_GROUP_NUM       1262
#define IDC_EDIT_CHTETB_LINE_HEIGHT     1263
#define IDC_BUTTON_CHTETB_APPLY         1264
#define IDC_BUTTON_CHTETB_HIDE          1265
#define IDC_EDIT_CHTETB_AUTOSCROLL      1266
#define IDC_EDIT_CHTETB_OFFSET_X        1267
#define IDC_EDIT_CHTETB_OFFSET_Y        1268
#define IDC_EDIT_BTN_R                  1268
#define IDC_EDIT_TEXT                   1269
#define IDC_EDIT_OUTLINE_TEXT           1269
#define IDC_EDIT_BTN_G                  1269
#define IDC_EDIT_BTN_B                  1270
#define IDC_EDIT_CHTETB_R               1270
#define IDC_EDIT_CHTETB_G               1271
#define IDC_EDIT_CHTETB_B               1272
#define IDC_EDIT_STATT_R                1274
#define IDC_EDIT_STATT_G                1275
#define IDC_EDIT_STATT_B                1276
#define IDC_EDIT_RADB_R                 1277
#define IDC_EDIT_RADB_G                 1278
#define IDC_EDIT_RADB_B                 1279
#define IDC_EDIT_CHKB_R                 1280
#define IDC_EDIT_CHKB_G                 1281
#define IDC_EDIT_CHKB_B                 1282
#define IDC_EDIT_CBX_R                  1283
#define IDC_EDIT_CBX_G                  1284
#define IDC_EDIT_CBX_B                  1285
#define IDC_EDIT_ETB_R                  1286
#define IDC_EDIT_ETB_G                  1287
#define IDC_EDIT_ETB_B                  1288
#define IDC_EDIT_IMGSTT_R               1289
#define IDC_EDIT_IMGSTT_G               1290
#define IDC_EDIT_IMGSTT_B               1291
#define IDC_EDIT_LSTB_R                 1292
#define IDC_EDIT_LSTB_G                 1293
#define IDC_EDIT_LSTB_B                 1294
#define IDC_EDIT_LSTV_R                 1295
#define IDC_EDIT_LSTV_G                 1296
#define IDC_EDIT_LSTV_B                 1297
#define IDC_EDIT_OUTLNE_R               1298
#define IDC_EDIT_OUTLNE_G               1299
#define IDC_EDIT_OUTLNE_B               1300
#define IDC_EDIT_BTN_WEIGHT             1301
#define IDC_EDIT_CHTETB_WEIGHT          1302
#define IDC_EDIT_CHKB_WEIGHT            1303
#define IDC_EDIT_CBX_WEIGHT             1304
#define IDC_EDIT_ETB_WEIGHT             1305
#define IDC_EDIT_IMGSTT_WEIGHT          1306
#define IDC_EDIT_LSTB_WEIGHT            1307
#define IDC_EDIT_LSTV_WEIGHT            1308
#define IDC_EDIT_OUTLNE_WEIGHT          1309
#define IDC_EDIT_RADB_WEIGHT            1310
#define IDC_EDIT_STATT_WEIGHT           1311
#define IDC_PROPERTIES                  32772
#define IDC_SETTINGS                    32774
#define ID_ADD_BUTTON                   32775
#define ID_ADD_EDIT                     32776
#define ID_ADD_STATIC                   32777
#define IDC_90PERC                      32778
#define IDC_80PERS                      32779
#define IDC_70PERC                      32780
#define IDC_60PERC                      32781
#define IDC_50PERC                      32782
#define IDC_25PERC                      32783
#define IDC_100PERC                     32784
#define IDC_110PERC                     32785
#define IDC_120PERC                     32786
#define IDC_130PERC                     32787
#define IDC_140PERC                     32788
#define IDC_150PERC                     32789
#define IDC_200PERC                     32790
#define IDC_80PERC                      32791
#define IDC_SELECT_ALL                  32792
#define ID_ADD_CHECKBOX                 32794
#define ID_ADD_RADIOBUTTON              32795
#define ID_ADD_LISTBOX                  32796
#define ID_ADD_GROUPBOX                 32798
#define ID_ZOOM_IN                      32799
#define ID_ZOOM_OUT                     32800
#define ID_ADD_COMBOBOX                 32801
#define ID_SNAP_TO_GRID                 32802
#define ID_SHOW_GRID                    32804
#define ID_SNAP_TO_MARGIN               32805
#define ID_MARGINS                      32806
#define ID_RESTRAIN                     32807
#define ID_LEFT_ALIGN                   32808
#define ID_RIGHT_ALIGN                  32809
#define ID_TOP_ALIGN                    32810
#define ID_BOTTOM_ALIGN                 32811
#define ID_MAKE_SAME_SIZE               32812
#define ID_UP                           32813
#define ID_DOWN                         32814
#define ID_FRONT                        32815
#define ID_BOTTOM                       32816
#define ID_EXPORT                       32817
#define ID_ADD_NONE                     32819
#define ID_BUTTON_MULTIDRAW             32821
#define ID_Menu                         32821
#define ID_DLG_PROPERTY                 32823
#define ID_ADD_IMAGESTATIC              32825
#define ID_ADD_LISTVIEW                 32827
#define ID_ADD_OUTLINE                  32833
#define ID_BUTTON32834                  32834
#define ID_ADD_CHATEDIT                 32834
#define ID_VIEW_MAGNET                  32837
#define ID_VIEW_MAGNET_MODE             32839

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1312
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
