#ifndef _BASEDEFINITION_H_
#define _BASEDEFINITION_H_

#define		CHARACTER_TILE_WIDTH	320
#define		CHARACTER_TILE_HEIGHT	240

#define		MAX_ITEMCODE_LENGTH		6
#define		MAX_ACTIONCODE_LENGTH	5
#define		MAX_FILE_NUM			50000
#define		MAX_ITEM_NAME			24

#define		MAX_DRAWING_SEQUENCE_NUM	8
#define		MAX_PART_NUM				9

#define				TILE_WIDTH				320
#define				TILE_HEIGHT				240

enum { HSU1, HTU2, HBU2, HGU2, HITU, MOVU, WT1U, WT2U, DTHU, SPCU, HSR1, HTR2, HBR2, HGR2, HITR, MOVR, WT1R, WT2R, DTHR, SPCR, SITU, FSHU, FAMU, MINU };
enum { SOUTH_EAST, SOUTH, SOUTH_WEST, WEST, NORTH_WEST, NORTH, NORTH_EAST, EAST };

#endif