//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GMTOOL.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_FORMVIEW                    101
#define IDD_BLOCKVIEW                   103
#define IDD_STATICSCENTERVIEW           104
#define IDD_INFORMATIONCHANGEVIEW       105
#define IDD_NOTICEVIEW                  107
#define IDD_ITEMVIEW                    108
#define IDD_GUILDVIEW                   109
#define IDD_IDVIEW                      110
#define IDR_HTML_CHAR_STATUS            111
#define IDR_HTML_ITEMVIEW               112
#define IDR_MAINFRAME                   128
#define IDR_GMTOOLTYPE                  129
#define IDR_MAINFRAME1                  129
#define IDD_LOGVIEW                     130
#define IDR_GMTOOL_TRADELOG             130
#define IDR_GMTOOL_LOG                  131
#define IDD_CHARVIEW                    132
#define IDR_GMTOOL_GUILD                132
#define IDR_GMTOOL_Item                 133
#define IDR_GMTOOL_CHAR                 133
#define IDR_GMTOOL_ITEM                 134
#define IDR_GMTOOL_BLOCKCHAR            135
#define IDD_INVENTORY                   136
#define IDR_GMTOOL_STATICS              136
#define IDD_EQUIP                       137
#define IDR_GMTOOL_CHANGEINFOR          137
#define IDD_BANK                        138
#define IDR_GMTOOL_RECOVER              138
#define IDD_CHAR_STAUS                  139
#define IDR_GMTOOL_NOTICE               139
#define IDR_GMTOOL_ID                   140
#define IDD_BLOCKREASON                 141
#define IDR_GMTOOL_NEWLOG               141
#define IDD_BLOCKEDIT                   142
#define IDR_GMTOOL_NEWLOG2              142
#define IDR_GMTOOL_GMCLIENT             142
#define IDD_ITEMSEARCH                  143
#define IDR_GMTOOL_SELLEDLOG            143
#define IDD_CHAR_SUB_SKILL              144
#define IDD_ITEM_SEARCH                 145
#define IDD_NEWLOGVIEW                  146
#define IDD_DIALOG_GMCLIENT             147
#define IDD_TRADELOGVIEW                148
#define IDD_SELLEDLOGVIEW               149
#define IDD_ITEMINFO                    150
#define IDC_LIST_RESULT                 1005
#define IDC_DATETIME_DATE               1015
#define IDC_DATETIME_STARTTIME          1016
#define IDC_DATETIME_ENDTIME            1017
#define IDC_EDIT_CHAR                   1018
#define IDC_DATETIME_ENDDATE_NEW        1018
#define IDC_EDIT_TCHAR                  1019
#define IDC_COMBO_SERVER                1020
#define IDC_EDIT_ITEMUNIQUE             1021
#define IDC_EDIT_CHAR_NEW               1021
#define IDC_RADIO_COMMAND               1022
#define IDC_EDIT_TCHAR_NEW              1022
#define IDC_EDIT_ITEMUNIQUE2            1022
#define IDC_RADIO_COMMANDFILTER         1023
#define IDC_EDIT_ITEMUNIQUE_NEW         1023
#define IDC_COMBO_COMMAND               1024
#define IDC_EDIT_ACCOUNTID_NEW          1024
#define IDC_COMBO_COMMANDFILTER         1025
#define IDC_EDIT_ITEMSID_NEW            1026
#define IDC_DATETIME_ENDDATE            1026
#define IDC_EDIT_DETAIL                 1027
#define IDC_EDIT_SEARCHINRESULT         1028
#define IDC_BUTTON_SEARCHINRESULT       1029
#define IDC_COMBO_ITEM                  1030
#define IDC_BUTTON_SEARCH               1031
#define IDC_BUTTON_STOP                 1032
#define IDC_BUTTON_SEL_DELETE           1034
#define IDC_BUTTON_SEL_EXPORT           1035
#define IDC_BUTTON_DESEL_DELETE         1036
#define IDC_BUTTON_ALL_DELETE           1038
#define IDC_BUTTON_ALL_EXPORT           1039
#define IDC_GROUP_SERVER                1040
#define IDC_GROUP_CHAR                  1041
#define IDC_STATIC_CHAR                 1042
#define IDC_STATIC_TCHAR                1043
#define IDC_GROUP_COMMAND               1044
#define IDC_STATIC_CHAR2                1044
#define IDC_GROUP_EXECUTE               1045
#define IDC_GROUP_SEARCHINRESULT        1046
#define IDC_GROUP_SERVER2               1047
#define IDC_GROUP_SEARCHINRESULT2       1047
#define IDC_STATIC_TCHAR2               1048
#define IDC_GROUP_SERVER3               1049
#define IDC_EDIT_CLICKEDITEM            1050
#define IDC_GROUP_CLICKEDITEM           1051
#define IDC_GROUP_DELETE                1052
#define IDC_GROUP_TEXTEXPORT            1053
#define IDC_CHECK_AUTOCLEAR             1054
#define IDC_GROUP_CLICKEDITEM2          1054
#define IDC_STATIC_SEARCHING            1055
#define IDC_GROUP_CLICKEDITEM3          1055
#define IDC_EDIT_LOGTEXT                1056
#define IDC_RADIO1                      1057
#define IDC_CHECK_TOTAB                 1057
#define IDC_STATIC_CHAR3                1057
#define IDC_RADIO_CHARACTER             1057
#define IDC_STATIC_TCHAR3               1058
#define IDC_RADIO_ACCOUNTID             1058
#define IDC_CHARNAME                    1059
#define IDC_GROUP_CHAR2                 1059
#define IDC_COMBO2                      1060
#define IDC_STATIC_CHAR4                1060
#define IDC_COMBO3                      1061
#define IDC_STATIC_TCHAR4               1061
#define IDC_COMBO4                      1062
#define IDC_BUTTON1                     1063
#define IDC_EDIT1                       1064
#define IDC_BUTTON6                     1064
#define IDC_BUTTON2                     1065
#define IDC_EDIT2                       1065
#define IDC_EDIT3                       1066
#define IDC_EDIT4                       1067
#define IDC_LIST5                       1068
#define IDC_BUTTON3                     1068
#define IDC_EDIT5                       1068
#define IDC_CHARVIEWR                   1068
#define IDC_BUTTON7                     1069
#define IDC_EDIT                        1070
#define IDC_EDITPOSITION                1071
#define IDC_EDIT10                      1072
#define IDC_EDIT11                      1073
#define IDC_LISTNAME                    1075
#define IDC_COMBO1                      1081
#define IDC_COMBO5                      1082
#define IDC_COMBO6                      1083
#define IDC_LIST1                       1084
#define IDC_COMBO7                      1084
#define IDC_COMBO8                      1085
#define IDC_LIST2                       1086
#define IDC_TAB1                        1087
#define IDC_BUTTON4                     1088
#define IDC_BUTTON5                     1089
#define IDC_LIST_ITEMRESULT             1089
#define IDC_EDIT6                       1090
#define IDC_EDIT7                       1091
#define IDC_EDIT8                       1092
#define IDC_EDIT9                       1093
#define IDC_LEVEL                       1094
#define IDC_ST_JOB                      1095
#define IDC_STATUSP                     1096
#define IDC_SKILLP                      1097
#define IDC_SKILL_RESET                 1098
#define IDC_MAPPOINT                    1099
#define IDC_POSITION                    1100
#define IDC_COM_JOB                     1101
#define IDC_LIST_IDRESULT               1102
#define IDC_EDIT_IDTEXT                 1103
#define IDC_LIST_GUILDLIST              1104
#define IDC_LISTID                      1105
#define IDC_BLOCK_LEFT                  1106
#define IDC_BLOCK_RIGHT                 1107
#define IDC_CHECK1                      1108
#define IDC_LIST3                       1109
#define IDC_NOTICE_LIST                 1110
#define IDC_LIST_GUILDL                 1111
#define IDC_EDIT_IDRESULT               1112
#define IDC_CHARVIEW_COMBOBOX_SERVER    1113
#define IDC_EDIT_INPUT                  1114
#define IDC_ID_IDNAME                   1116
#define IDC_ID_REALLIKE                 1117
#define IDC_CHAR_SINGLELIST             1118
#define IDC_ID_EDITLIST                 1119
#define IDC_COMBO_SERVER_NEW            1120
#define IDC_DATETIME_STARTDATE_NEW      1121
#define IDC_COMBO_ITEM_NEW              1123
#define IDC_COMBO_COMMANDTYPE           1124
#define IDC_COMBO_COMMANDINDEX          1125
#define IDC_BUTTON_SEARCH_NEW           1126
#define IDC_BUTTON_STOP_NEW             1127
#define IDC_CHECK_AUTOCLEAR_NEW         1128
#define IDC_LIST_RESULT_NEW             1129
#define IDC_EDIT_LOGTEXT_NEW            1130
#define IDC_EDIT_CLICKEDITEM_NEW        1131
#define IDC_BUTTON_SEL_DELETE_NEW       1132
#define IDC_BUTTON_DESEL_DELETE_NEW     1133
#define IDC_BUTTON_ALL_DELETE_NEW       1134
#define IDC_BUTTON_SEL_EXPORT_NEW       1135
#define IDC_BUTTON_ALL_EXPORT_NEW       1136
#define IDC_EDIT_SEARCHINRESULT_NEW     1137
#define IDC_BUTTON_SEARCHINRESULT_NEW   1138
#define IDC_LIST_COLUMNLIST             1139
#define IDC_BUTTON_ALL_EXPORT_NEW2      1140
#define IDC_BUTTON_APPLY                1140
#define IDC_EDIT_DETAILOPTION           1141
#define IDC_BUTTON_SELECT               1142
#define IDC_BUTTON_UNSELECT             1143
#define IDC_EDITID                      1148
#define IDC_EDITPW                      1149
#define IDC_LOGINBUTTON                 1150
#define IDC_EDIT_COMMAND                1151
#define IDC_SEARCHBUTTON                1152
#define IDC_INFOBOX                     1153
#define IDC_LOGINSECTION                1154
#define IDC_STATICID                    1155
#define IDC_STATICPW                    1156
#define IDC_COMBO_SERVERCODE            1157
#define IDC_COMBO_SERVERINDEX           1158
#define IDC_EDIT_CHARNAME               1159
#define IDC_EDIT_CHARID                 1160
#define IDC_COMBO_SELLSERVERCODE        1161
#define IDC_COMBO_SELLSERVERINDEX       1162
#define IDC_EDIT_SELLCHARID             1163
#define IDC_EDIT_SELLCHARNAME           1164
#define IDC_COMBO_BUYSERVERCODE         1165
#define IDC_COMBO_BUYSERVERINDEX        1166
#define IDC_EDIT_BUYCHARID              1168
#define IDC_EDIT_BUYCHARNAME            1169
#define IDC_IPADDRESS                   1172
#define IDC_RICHEDIT_ITEMINFO           1173
#define IDC_BTN_LOADNEWVIEWER           1174
#define IDC_EDIT_LOGTEXT2_NEW           1175
#define IDC_RICHEDIT22                  1177
#define ID_MENU_LOG                     32777
#define ID_Menu                         32778
#define ID_MENU_ID                      32780
#define ID_MENU_CHAR                    32781
#define ID_MENU_STATICSCENTER           32784
#define ID_MENU_INFOR                   32785
#define ID_MENU_CHARRECPVER             32786
#define ID_MENU_GUILD                   32787
#define ID_MENU_ITEM                    32789
#define ID_MENU_STATICS                 32790
#define ID_MENU_RECOVER                 32792
#define ID_MENU_NOTICE                  32793
#define ID_MENU_BLOCKCHAR               32804
#define ID_MENU_NEWLOG                  32806
#define ID_MENU_GMCLIENT                32809
#define ID_MENU_TRADELOG                32811
#define ID_MENU_SELLEDLOG               32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1178
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
