//---------------------------------
// 2003/6/6 김태곤
//---------------------------------

#include "..\CommonLogic\CommonLogic.h"
#include "Skill-Manager.h"
#include "..\Resource.h"
#include "..\CommonLogic\MagicMgr\MagicBaseInfo.h"

#define BITMAPINDEX(x) (x)


void cltSkillManager::SetSkillType()
{
	//	[종호_SKILLINTERFACE] 기존 스킬타입///////////////////////////////////////////////////////////////////////////

	//	// 스킬 타입을 추가한다. 
	///*	TCHAR* pText = GetTxtFromMgr(2841);
	//	AddSkillType(SKILLTYPE_MED,				TEXT("SKILLTYPE_MED"),			pText);*/
	//
	///*	pText = GetTxtFromMgr(2842);
	//	AddSkillType(SKILLTYPE_FOOD,			TEXT("SKILLTYPE_FOOD"),			pText);*/
	//
	//	TCHAR * pText = GetTxtFromMgr(2843);
	//	AddSkillType(SKILLTYPE_WEAR,			TEXT("SKILLTYPE_WEAR"),			pText);
	//
	//	pText = GetTxtFromMgr(2844);
	//	AddSkillType(SKILLTYPE_MAKEWEAPON,		TEXT("SKILLTYPE_MAKEWEAPON"),	pText);
	//
	//	pText = GetTxtFromMgr(2845);
	//	AddSkillType(SKILLTYPE_ACCESSARY,		TEXT("SKILLTYPE_ACCESSARY"),	pText);
	//
	//	pText = GetTxtFromMgr(2846);
	//	AddSkillType(SKILLTYPE_USEWEAPON,		TEXT("SKILLTYPE_USEWEAPON"),	pText);
	//
	//	pText = GetTxtFromMgr(2847);
	//	AddSkillType(SKILLTYPE_MAKETOOL,		TEXT("SKILLTYPE_MAKETOOL"),		pText);
	//
	//	pText = GetTxtFromMgr(2848);
	//	AddSkillType(SKILLTYPE_SEA,				TEXT("SKILLTYPE_SEA"),			pText);
	//
	//	pText = GetTxtFromMgr(2849);
	//	AddSkillType(SKILLTYPE_HARVEST,			TEXT("SKILLTYPE_HARVEST"),		pText);
	//
	//	pText = GetTxtFromMgr(2850);
	//	AddSkillType(SKILLTYPE_ETC,				TEXT("SKILLTYPE_ETC"),			pText);
	//
	//	pText = GetTxtFromMgr(5138);
	//	AddSkillType(SKILLTYPE_FIGHT,			TEXT("SKILLTYPE_FIGHT"),		pText,	FALSE);
	//
	//	pText = GetTxtFromMgr(10316);									
	//	AddSkillType(SKILLTYPE_MAKEAVATAR, TEXT("SKILLTYPE_MAKEAVATAR"), pText);				//	[종호] 아바타 제조술 타입 추가


	//	[종호_SKILLINTERFACE] 변경된 스킬타입 ////////////////////////////////////////////////////////////////////////////////
	//	무기사용술

	TCHAR * pText = NULL;

	pText = GetTxtFromMgr(2846);
	AddSkillType(SKILLTYPE_R_USEWEAPON, TEXT("SKILLTYPE_USEWEAPON"), pText);
	
	//	무기제작술
	pText = GetTxtFromMgr(2844);
	AddSkillType(SKILLTYPE_R_MAKEWEAPON, TEXT("SKILLTYPE_MAKEWEAPON"), pText);

	//	방어구제작술
	pText = GetTxtFromMgr(2843);
	AddSkillType(SKILLTYPE_R_ARMOR, TEXT("SKILLTYPE_ARMOR"), pText);
	
	//	생산제작술
	pText = GetTxtFromMgr(2849);
	AddSkillType(SKILLTYPE_R_MAKEHARVEST, TEXT("SKILLTYPE_MAKEHARVEST"), pText);

	//	생산기술
	pText = GetTxtFromMgr(10338);
	AddSkillType(SKILLTYPE_R_HARVEST, TEXT("SKILLTYPE_HARVEST"), pText);
	
	//	재단술
	pText = GetTxtFromMgr(10316);
	AddSkillType(SKILLTYPE_R_MAKECLOTH, TEXT("SKILLTYPE_MAKECLOTH"), pText);

	//	악세사리제작술
	pText = GetTxtFromMgr(10337);
	AddSkillType(SKILLTYPE_R_MAKEACCESSARY, TEXT("SKILLTYPE_MAKEACCESSARY"), pText);

	//	기타기술
	pText = GetTxtFromMgr(2850);
	AddSkillType(SKILLTYPE_R_ETC, TEXT("SKILLTYPE_ETC"), pText);

	//	전투력향상술
	pText = GetTxtFromMgr(2846);
	AddSkillType(SKILLTYPE_FIGHT, TEXT("SKILLTYPE_FIGHT"), pText);
}

void cltSkillManager::SetSkill()
{
	//	[종호_SKILLINTERFACE] 변경된 스킬 분류 ////////////////////////////////////////////////////////////////////////////////	
	//	소분류 스킬들을 중분류 스킬에 포함시킵니다.

	TCHAR * pText = NULL;

	//	무기사용술 - 검술
	pText = GetTxtFromMgr(2865);
	AddSkill(SKILL_USESWORD1, SKILLTYPE_R_USEWEAPON, 0, TEXT("USESWORD1"), pText,	30, 0, BITMAPINDEX(15),	100, WEAPONSKILLTYPE_SWORD);

	//	무기사용술 - 창술
	pText = GetTxtFromMgr(2866);
	AddSkill(SKILL_USESPEAR1, SKILLTYPE_R_USEWEAPON, 0, TEXT("USESPEAR1"), pText,	30,	0, BITMAPINDEX(16),	101, WEAPONSKILLTYPE_SPEAR);

	//	무기사용술 - 도끼술
	pText = GetTxtFromMgr(2867);
	AddSkill(SKILL_USEAXE1, SKILLTYPE_R_USEWEAPON, 0, TEXT("USEAXE1"), pText, 30, 0, BITMAPINDEX(18), 103, WEAPONSKILLTYPE_AXE);

	//	무기사용술 - 지팡이술
	pText = GetTxtFromMgr(2868);
	AddSkill(SKILL_USESTAFF1, SKILLTYPE_R_USEWEAPON, 0, TEXT("USESTAFF1"), pText, 30, 0, BITMAPINDEX(20),	105, WEAPONSKILLTYPE_STAFF);

	//	무기사용술 - 활술
	pText = GetTxtFromMgr(2869);
	AddSkill(SKILL_USEBOW1, SKILLTYPE_R_USEWEAPON, 0, TEXT("USEBOW1"), pText, 30, 0, BITMAPINDEX(17),	102, WEAPONSKILLTYPE_BOW);

	//	무기사용술 - 총술
	pText = GetTxtFromMgr(2870);
	AddSkill(SKILL_USEGUN1,	SKILLTYPE_R_USEWEAPON, 0,	TEXT("USEGUN1"), pText,	30,	0, BITMAPINDEX(19),	104, WEAPONSKILLTYPE_GUN);

	//	무기제작술 - 검제작술
	pText = GetTxtFromMgr(2854);
	AddSkill(SKILL_MAKESWORD1, SKILLTYPE_R_MAKEWEAPON, SKILLATB_LIST, TEXT("MAKESWORD1"), pText, 30, 0, BITMAPINDEX(4), 89);

	//	무기제작술 - 창제작술
	pText = GetTxtFromMgr(2855);
	AddSkill(SKILL_MAKESPEAR1, SKILLTYPE_R_MAKEWEAPON, SKILLATB_LIST, TEXT("MAKESPEAR1"), pText, 30, 0, BITMAPINDEX(5), 90);

	//	무기제작술 - 도끼제작술
	pText = GetTxtFromMgr(2856);
	AddSkill(SKILL_MAKEAXE1, SKILLTYPE_R_MAKEWEAPON,SKILLATB_LIST, TEXT("MAKEAXE1"), pText, 30, 0, BITMAPINDEX(6), 91);

	//	무기제작술 - 지팡이제작술
	pText = GetTxtFromMgr(2857);
	AddSkill(SKILL_MAKESTAFF1, SKILLTYPE_R_MAKEWEAPON, SKILLATB_LIST, TEXT("MAKESTAFF1"), pText, 30, 0, BITMAPINDEX(7), 92);

	//	무기제작술 - 활제작술
	pText = GetTxtFromMgr(2858);
	AddSkill(SKILL_MAKEBOW1, SKILLTYPE_R_MAKEWEAPON, SKILLATB_LIST, TEXT("MAKEBOW1"), pText, 30, 0, BITMAPINDEX(8), 93);

	//	무기제작술 - 총제작술
	pText = GetTxtFromMgr(2859);
	AddSkill(SKILL_MAKEGUN1, SKILLTYPE_R_MAKEWEAPON, SKILLATB_LIST, TEXT("MAKEGUN1"), pText, 30, 0, BITMAPINDEX(9), 94);

	//	방어구제작술 - 갑옷제작술
	pText = GetTxtFromMgr(2852);
	AddSkill(SKILL_MAKEARMOUR1, SKILLTYPE_R_ARMOR, SKILLATB_LIST, TEXT("MAKEARMOUR1"), pText, 30, 0, BITMAPINDEX(2), 87);

	//	방어구제작술 - 투구제작술
	pText = GetTxtFromMgr(2853);
	AddSkill(SKILL_MAKEHELMET1, SKILLTYPE_R_ARMOR, SKILLATB_LIST, TEXT("MAKEHELMET1"), pText, 30, 0, BITMAPINDEX(3), 88);	

	//	방어구제작술 - 벨트제작술
	pText = GetTxtFromMgr(2862);
	AddSkill(SKILL_MAKEBELT1, SKILLTYPE_R_ARMOR, SKILLATB_LIST, TEXT("MAKEBELT1"), pText, 30, 0, BITMAPINDEX(11),	96);

	//	방어구제작술 - 신발제작술
	pText = GetTxtFromMgr(2861);
	AddSkill(SKILL_MAKESHOES1, SKILLTYPE_R_ARMOR,	SKILLATB_LIST, TEXT("MAKESHOES"), pText, 30, 0, BITMAPINDEX(10), 95);

	//	생산제작술 - 약제조술
	pText = GetTxtFromMgr(2851);
	AddSkill(SKILL_MAKEMED, SKILLTYPE_R_MAKEHARVEST, SKILLATB_LIST, TEXT("MAKEMED"), pText, 30, 0, BITMAPINDEX(0), 85);

	//	생산제작술 - 요리제조술
	pText = GetTxtFromMgr(2842);
	AddSkill(SKILL_MAKEFOOD, SKILLTYPE_R_MAKEHARVEST, SKILLATB_LIST, TEXT("MAKEFOOD"), pText, 30, 0, BITMAPINDEX(1), 86);

	//	생산제작술 - 철물제작술
	pText = GetTxtFromMgr(2871);
	AddSkill(SKILL_MAKEIRON1, SKILLTYPE_R_MAKEHARVEST, SKILLATB_LIST, TEXT("MAKEIRON1"), pText, 30, 0, BITMAPINDEX(26), 111);

	//	생산제작술 - 생산도구제작술
	pText = GetTxtFromMgr(5774);
	AddSkill(SKILL_MAKETOOL1, SKILLTYPE_R_MAKEHARVEST, SKILLATB_LIST,	TEXT("MAKETOOL1"), pText, 30, 0, BITMAPINDEX(27), 121);


	//	생산제작술 - 결정체제작술
	if( pclClient->IsCountrySwitch( Switch_Artifact ) ) // 아이템 타입 변경에 따른 스위치 변경예정.
	{
		// [추가 : 황진성 2008. 2. 25 => 아티팩트 술 (결정체 제조술) ]
		pText = GetTxtFromMgr(8225);
		AddSkill(SKILL_ARTIFACT, SKILLTYPE_R_MAKEHARVEST, SKILLATB_LIST, TEXT( "ARTFACT" ), pText, 30, 0, BITMAPINDEX( 35 ), 8226 );
	}

	//	생산기술 - 어획술
	pText = GetTxtFromMgr(2881);
	AddSkill(SKILL_FISH, SKILLTYPE_R_HARVEST, SKILLATB_LIST, TEXT("FISH"), pText, 20, 0, BITMAPINDEX(22), 107);

	//	생산기술 - 농경술
	pText = GetTxtFromMgr(2883);
	AddSkill(SKILL_FARM, SKILLTYPE_R_HARVEST, SKILLATB_LIST, TEXT("FARM"), pText, 30, 0, BITMAPINDEX(33),	119);

	//	생산기술 - 채광술
	pText = GetTxtFromMgr(2884);
	AddSkill(SKILL_MINE, SKILLTYPE_R_HARVEST, SKILLATB_LIST, TEXT("MINE"), pText,	30, 0, BITMAPINDEX(33),	120);


	if ( TRUE == pclClient->IsCountrySwitch(Switch_Avatar_artisan) )
	{
		//	재단술 - 의복제작술
		pText = GetTxtFromMgr(10317); 
		AddSkill(SKILL_MAKEAVATAR_DRESS, SKILLTYPE_R_MAKECLOTH, SKILLATB_LIST, TEXT("MAKEAVATAR_DRESS"), pText, 30, 0, BITMAPINDEX(36), 10322);

		//	재단술 - 모자제작술
		pText = GetTxtFromMgr(10318); 
		AddSkill(SKILL_MAKEAVATAR_HAT, SKILLTYPE_R_MAKECLOTH, SKILLATB_LIST, TEXT("MAKEAVATAR_HAT"), pText, 30, 0, BITMAPINDEX(37), 10323);

		//	재단술 - 망토제작술
		pText = GetTxtFromMgr(10319); 
		AddSkill(SKILL_MAKEAVATAR_MANTLE, SKILLTYPE_R_MAKECLOTH, SKILLATB_LIST, TEXT("MAKEAVATAR_MANTLE"), pText, 30, 0, BITMAPINDEX(38), 10324);

		//	악세사리제작술 - 반지제작술
		pText = GetTxtFromMgr(10320); 
		AddSkill(SKILL_MAKEAVATAR_RING, SKILLTYPE_R_MAKEACCESSARY, SKILLATB_LIST, TEXT("MAKEAVATAR_RING"), pText, 30, 0, BITMAPINDEX(39),	10325);

		//	악세사리제작술 - 목걸이제작술
		pText = GetTxtFromMgr(10321); 
		AddSkill(SKILL_MAKEAVATAR_NECK, SKILLTYPE_R_MAKEACCESSARY, SKILLATB_LIST, TEXT("MAKEAVATAR_NECK"), pText, 30, 0, BITMAPINDEX(40),	10326);
	}

	//	기타기술 - 소환술
	pText = GetTxtFromMgr(2877);
	AddSkill(SKILL_CAPTURE, SKILLTYPE_R_ETC, SKILLATB_LIST, TEXT("CAPTURE"), pText, 30, 0, BITMAPINDEX(30), 114);

	//	기타기술 - 포획술
	pText = GetTxtFromMgr(2878);
	AddSkill(SKILL_SUMMON, SKILLTYPE_R_ETC, SKILLATB_LIST, TEXT("SUMMON"), pText, 30, 0, BITMAPINDEX(21),	117);

	//	기타기술 - 말조련술
	pText = GetTxtFromMgr(2876);
	AddSkill(SKILL_HORSETRAINING, SKILLTYPE_R_ETC, SKILLATB_LIST, TEXT("HORSETRAINING1"), pText, 30, 0, BITMAPINDEX(25), 110);



	// 전투향상술
	pText = GetTxtFromMgr(5132);
	AddSkill(	SKILL_SWORD_INCDR, SKILLTYPE_FIGHT, 0, TEXT("SWORD_INCDR"), pText,	
				MAX_WEAPONSKILL_LEVEL, 0, BITMAPINDEX(15), 5145, WEAPONSKILLTYPE_SWORD);

	pText = GetTxtFromMgr(5131);
	AddSkill(	SKILL_SWORD_INCVIT, SKILLTYPE_FIGHT, 0, TEXT("SWORD_INCVIT"), 
				pText, MAX_WEAPONSKILL_LEVEL, SKILL_SWORD_INCDR, BITMAPINDEX(15), 5144, WEAPONSKILLTYPE_SWORD);

	pText = GetTxtFromMgr(5133);
	AddSkill(	SKILL_SPEAR_INCAC, SKILLTYPE_FIGHT, 0, TEXT("SPEAR_INCAC"), pText, 
				MAX_WEAPONSKILL_LEVEL, 0, BITMAPINDEX(16), 5146, WEAPONSKILLTYPE_SPEAR);

	pText = GetTxtFromMgr(5136);
	AddSkill(SKILL_SPEAR_DOUBLEAT, SKILLTYPE_FIGHT, 0, TEXT("SPEAR_DOUBLEAT"), pText, 
		MAX_WEAPONSKILL_LEVEL, SKILL_SPEAR_INCAC,	BITMAPINDEX(16), 5149, WEAPONSKILLTYPE_SPEAR);

	pText = GetTxtFromMgr(5134);
	AddSkill(	SKILL_AXE_DECGAP, SKILLTYPE_FIGHT, 0, TEXT("AXE_DECGAP"), pText, 
				MAX_WEAPONSKILL_LEVEL, 0, BITMAPINDEX(18), 5147, WEAPONSKILLTYPE_AXE);

	pText = GetTxtFromMgr(5199);
	AddSkill(	SKILL_AXE_INDURE, SKILLTYPE_FIGHT, 0, TEXT("AXE_INDURE"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_AXE_DECGAP, BITMAPINDEX(18),	5203, WEAPONSKILLTYPE_AXE);

	pText = GetTxtFromMgr(5126);
	AddSkill(	SKILL_BOW_DRAIN, SKILLTYPE_FIGHT, 0, TEXT("BOW_DRAIN"), pText, 
				MAX_WEAPONSKILL_LEVEL, 0, BITMAPINDEX(17), 5139, WEAPONSKILLTYPE_BOW);

	pText = GetTxtFromMgr(5130);
	AddSkill(	SKILL_BOW_INCRANGE, SKILLTYPE_FIGHT, 0, TEXT("BOW_INCRANGE"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_BOW_DRAIN, BITMAPINDEX(17), 5143, WEAPONSKILLTYPE_BOW);

	pText = GetTxtFromMgr(5200);
	AddSkill(	SKILL_GUN_INCPHYAR, SKILLTYPE_FIGHT, 0, TEXT("GUN_INCPHYAR"), pText, 
				MAX_WEAPONSKILL_LEVEL, 0, BITMAPINDEX(19), 5204, WEAPONSKILLTYPE_GUN);

	pText = GetTxtFromMgr(5137);
	AddSkill(	SKILL_GUN_DECMAGDELAY, SKILLTYPE_FIGHT, 0, TEXT("GUN_DECMAGDELAY"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_GUN_INCPHYAR, BITMAPINDEX(19), 5150, WEAPONSKILLTYPE_GUN);

	pText = GetTxtFromMgr(5135);
	AddSkill(	SKILL_STAFF_INCMAG, SKILLTYPE_FIGHT, 0, TEXT("STAFF_INCMAG"), pText, 
				MAX_WEAPONSKILL_LEVEL, 0, BITMAPINDEX(20), 5148, WEAPONSKILLTYPE_STAFF);

	pText = GetTxtFromMgr(5201);
	AddSkill(	SKILL_STAFF_DECUSEMANA, SKILLTYPE_FIGHT, 0, TEXT("STAFF_DECUSEMANA"),	pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_STAFF_INCMAG, BITMAPINDEX(20), 5205, WEAPONSKILLTYPE_STAFF);

	// 히든 전투향상술
	pText = GetTxtFromMgr(5133); 
	AddSkill(	SKILL_SWORD_SPEAR_INCAC, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("SWORD_SPEAR_INCAC"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_SPEAR_INCAC, BITMAPINDEX(16), 5146, WEAPONSKILLTYPE_SWORD);

	pText = GetTxtFromMgr(5134); 
	AddSkill(	SKILL_SWORD_AXE_DECGAP, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("SWORD_AXE_DECGAP"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_AXE_DECGAP, BITMAPINDEX(18),	5147, WEAPONSKILLTYPE_SWORD);

	pText = GetTxtFromMgr(5126); 
	AddSkill(	SKILL_SWORD_BOW_DRAIN, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1,	TEXT("SWORD_BOW_DRAIN"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_BOW_DRAIN, BITMAPINDEX(17), 5139, WEAPONSKILLTYPE_SWORD);

	pText = GetTxtFromMgr(5200); 
	AddSkill(	SKILL_SWORD_GUN_INCPHYAR, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1,	TEXT("SWORD_GUN_INCPHYAR"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_GUN_INCPHYAR, BITMAPINDEX(19), 5204, WEAPONSKILLTYPE_SWORD);

	pText = GetTxtFromMgr(5135); 
	AddSkill(	SKILL_SWORD_STAFF_INCMAG, SKILLTYPE_FIGHT,	SKILLATB_HIDDENGRADE1, TEXT("SWORD_STAFF_INCMAG"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_STAFF_INCMAG, BITMAPINDEX(20), 5148, WEAPONSKILLTYPE_SWORD);

	pText = GetTxtFromMgr(5136); 
	AddSkill(	SKILL_SWORD_SPEAR_DOUBLEAT, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("SWORD_SPEAR_DOUBLEAT"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_SPEAR_DOUBLEAT, BITMAPINDEX(16),	5149, WEAPONSKILLTYPE_SWORD);

	pText = GetTxtFromMgr(5199); 
	AddSkill(	SKILL_SWORD_AXE_INDURE, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("SWORD_AXE_INDURE"), pText,		
				MAX_WEAPONSKILL_LEVEL, SKILL_AXE_INDURE, BITMAPINDEX(18), 5203, WEAPONSKILLTYPE_SWORD);

	pText = GetTxtFromMgr(5130); 
	AddSkill(	SKILL_SWORD_BOW_INCRANGE,	SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2,	TEXT("SWORD_BOW_INCRANGE"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_BOW_INCRANGE, BITMAPINDEX(17), 5143, WEAPONSKILLTYPE_SWORD);

	pText = GetTxtFromMgr(5137); 
	AddSkill(	SKILL_SWORD_GUN_DECMAGDELAY, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("SWORD_GUN_DECMAGDELAY"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_GUN_DECMAGDELAY, BITMAPINDEX(19), 5150, WEAPONSKILLTYPE_SWORD);

	pText = GetTxtFromMgr(5201); 
	AddSkill(	SKILL_SWORD_STAFF_DECUSEMANA, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("SWORD_STAFF_DECUSEMANA"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_STAFF_DECUSEMANA, BITMAPINDEX(20), 5205, WEAPONSKILLTYPE_SWORD);

	pText = GetTxtFromMgr(5132); 
	AddSkill(	SKILL_SPEAR_SWORD_INCDR, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("SPEAR_SWORD_INCDR"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_SWORD_INCDR, BITMAPINDEX(15), 5145, WEAPONSKILLTYPE_SPEAR);

	pText = GetTxtFromMgr(5134); 
	AddSkill(	SKILL_SPEAR_AXE_DECGAP, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("SPEAR_AXE_DECGAP"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_AXE_DECGAP, BITMAPINDEX(18), 5147, WEAPONSKILLTYPE_SPEAR);

	pText = GetTxtFromMgr(5126); 
	AddSkill(	SKILL_SPEAR_BOW_DRAIN, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1,	TEXT("SPEAR_BOW_DRAIN"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_BOW_DRAIN, BITMAPINDEX(17), 5139, WEAPONSKILLTYPE_SPEAR);

	pText = GetTxtFromMgr(5200); 
	AddSkill(	SKILL_SPEAR_GUN_INCPHYAR, SKILLTYPE_FIGHT,	SKILLATB_HIDDENGRADE1, TEXT("SPEAR_GUN_INCPHYAR"),	pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_GUN_INCPHYAR, BITMAPINDEX(19), 5204, WEAPONSKILLTYPE_SPEAR);

	pText = GetTxtFromMgr(5135); 
	AddSkill(	SKILL_SPEAR_STAFF_INCMAG, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("SPEAR_STAFF_INCMAG"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_STAFF_INCMAG, BITMAPINDEX(20), 5148, WEAPONSKILLTYPE_SPEAR);

	pText = GetTxtFromMgr(5131); 
	AddSkill(	SKILL_SPEAR_SWORD_INCVIT, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("SPEAR_SWORD_INCVIT"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_SWORD_INCVIT, BITMAPINDEX(15), 5144, WEAPONSKILLTYPE_SPEAR);

	pText = GetTxtFromMgr(5199); 
	AddSkill(	SKILL_SPEAR_AXE_INDURE, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("SPEAR_AXE_INDURE"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_AXE_INDURE, BITMAPINDEX(18), 5203, WEAPONSKILLTYPE_SPEAR);

	pText = GetTxtFromMgr(5130); 
	AddSkill(	SKILL_SPEAR_BOW_INCRANGE, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("SPEAR_BOW_INCRANGE"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_BOW_INCRANGE, BITMAPINDEX(17), 5143, WEAPONSKILLTYPE_SPEAR);

	pText = GetTxtFromMgr(5137); 
	AddSkill(	SKILL_SPEAR_GUN_DECMAGDELAY, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("SPEAR_GUN_DECMAGDELAY"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_GUN_DECMAGDELAY, BITMAPINDEX(19), 5150, WEAPONSKILLTYPE_SPEAR);

	pText = GetTxtFromMgr(5201); 
	AddSkill(	SKILL_SPEAR_STAFF_DECUSEMANA, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("SPEAR_STAFF_DECUSEMANA"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_STAFF_DECUSEMANA, BITMAPINDEX(20), 5205, WEAPONSKILLTYPE_SPEAR);

	pText = GetTxtFromMgr(5132); 
	AddSkill(	SKILL_AXE_SWORD_INCDR, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("AXE_SWORD_INCDR"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_SWORD_INCDR, BITMAPINDEX(15), 5145, WEAPONSKILLTYPE_AXE);

	pText = GetTxtFromMgr(5133); 
	AddSkill(	SKILL_AXE_SPEAR_INCAC, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("AXE_SPEAR_INCAC"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_SPEAR_INCAC, BITMAPINDEX(16), 5146, WEAPONSKILLTYPE_AXE);

	pText = GetTxtFromMgr(5126); 
	AddSkill(	SKILL_AXE_BOW_DRAIN, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("AXE_BOW_DRAIN"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_BOW_DRAIN, BITMAPINDEX(17), 5139, WEAPONSKILLTYPE_AXE);

	pText = GetTxtFromMgr(5200);
	AddSkill(	SKILL_AXE_GUN_INCPHYAR, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("AXE_GUN_INCPHYAR"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_GUN_INCPHYAR, BITMAPINDEX(19), 5204, WEAPONSKILLTYPE_AXE);

	pText = GetTxtFromMgr(5135); 
	AddSkill(	SKILL_AXE_STAFF_INCMAG, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("AXE_STAFF_INCMAG"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_STAFF_INCMAG, BITMAPINDEX(20), 5148, WEAPONSKILLTYPE_AXE);

	pText = GetTxtFromMgr(5131); 
	AddSkill(	SKILL_AXE_SWORD_INCVIT, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("AXE_SWORD_INCVIT"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_SWORD_INCVIT, BITMAPINDEX(15), 5144, WEAPONSKILLTYPE_AXE );

	pText = GetTxtFromMgr(5136); 
	AddSkill(	SKILL_AXE_SPEAR_DOUBLEAT, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("AXE_SPEAR_DOUBLEAT"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_SPEAR_DOUBLEAT, BITMAPINDEX(16), 5149, WEAPONSKILLTYPE_AXE );

	pText = GetTxtFromMgr(5130); 
	AddSkill(	SKILL_AXE_BOW_INCRANGE, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("AXE_BOW_INCRANGE"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_BOW_INCRANGE, BITMAPINDEX(17), 5143, WEAPONSKILLTYPE_AXE);

	pText = GetTxtFromMgr(5137); 
	AddSkill(	SKILL_AXE_GUN_DECMAGDELAY, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2,	TEXT("AXE_GUN_DECMAGDELAY"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_GUN_DECMAGDELAY, BITMAPINDEX(19), 5150, WEAPONSKILLTYPE_AXE );

	pText = GetTxtFromMgr(5201); 
	AddSkill(	SKILL_AXE_STAFF_DECUSEMANA, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("AXE_STAFF_DECUSEMANA"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_STAFF_DECUSEMANA, BITMAPINDEX(20), 5205, WEAPONSKILLTYPE_AXE );

	pText = GetTxtFromMgr(5132); 
	AddSkill(	SKILL_BOW_SWORD_INCDR, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("BOW_SWORD_INCDR"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_SWORD_INCDR, BITMAPINDEX(15), 5145, WEAPONSKILLTYPE_BOW );

	pText = GetTxtFromMgr(5133); 
	AddSkill(	SKILL_BOW_SPEAR_INCAC, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1,	TEXT("BOW_SPEAR_INCAC"), pText,	
				MAX_WEAPONSKILL_LEVEL, SKILL_SPEAR_INCAC, BITMAPINDEX(16), 5146, WEAPONSKILLTYPE_BOW );

	pText = GetTxtFromMgr(5134); 
	AddSkill(	SKILL_BOW_AXE_DECGAP, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("BOW_AXE_DECGAP"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_AXE_DECGAP, BITMAPINDEX(18), 5147, WEAPONSKILLTYPE_BOW );

	pText = GetTxtFromMgr(5200); 
	AddSkill(	SKILL_BOW_GUN_INCPHYAR, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1,	TEXT("BOW_GUN_INCPHYAR"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_GUN_INCPHYAR, BITMAPINDEX(19), 5204, WEAPONSKILLTYPE_BOW );

	pText = GetTxtFromMgr(5135); 
	AddSkill(	SKILL_BOW_STAFF_INCMAG, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1,	TEXT("BOW_STAFF_INCMAG"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_STAFF_INCMAG, BITMAPINDEX(20), 5148, WEAPONSKILLTYPE_BOW );

	pText = GetTxtFromMgr(5131); 
	AddSkill(	SKILL_BOW_SWORD_INCVIT, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2,	TEXT("BOW_SWORD_INCVIT"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_SWORD_INCVIT, BITMAPINDEX(15), 5144, WEAPONSKILLTYPE_BOW );

	pText = GetTxtFromMgr(5136); 
	AddSkill(	SKILL_BOW_SPEAR_DOUBLEAT, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("BOW_SPEAR_DOUBLEAT"), pText,	
				MAX_WEAPONSKILL_LEVEL, SKILL_SPEAR_DOUBLEAT, BITMAPINDEX(16), 5149, WEAPONSKILLTYPE_BOW );

	pText = GetTxtFromMgr(5199); 
	AddSkill(	SKILL_BOW_AXE_INDURE, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("BOW_AXE_INDURE"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_AXE_INDURE, BITMAPINDEX(18), 5203, WEAPONSKILLTYPE_BOW );

	pText = GetTxtFromMgr(5137); 
	AddSkill(	SKILL_BOW_GUN_DECMAGDELAY, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("BOW_GUN_DECMAGDELAY"),	pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_GUN_DECMAGDELAY, BITMAPINDEX(19), 5150, WEAPONSKILLTYPE_BOW );

	pText = GetTxtFromMgr(5201); 
	AddSkill(	SKILL_BOW_STAFF_DECUSEMANA,	SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2,	TEXT("BOW_STAFF_DECUSEMANA"),	pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_STAFF_DECUSEMANA, BITMAPINDEX(20), 5205, WEAPONSKILLTYPE_BOW );

	pText = GetTxtFromMgr(5132); 
	AddSkill(	SKILL_GUN_SWORD_INCDR, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("GUN_SWORD_INCDR"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_SWORD_INCDR, BITMAPINDEX(15), 5145, WEAPONSKILLTYPE_GUN );

	pText = GetTxtFromMgr(5133); 
	AddSkill(	SKILL_GUN_SPEAR_INCAC, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1,	TEXT("GUN_SPEAR_INCAC"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_SPEAR_INCAC, BITMAPINDEX(16), 5146, WEAPONSKILLTYPE_GUN );

	pText = GetTxtFromMgr(5134); 
	AddSkill(	SKILL_GUN_AXE_DECGAP, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("GUN_AXE_DECGAP"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_AXE_DECGAP, BITMAPINDEX(18), 5147, WEAPONSKILLTYPE_GUN );

	pText = GetTxtFromMgr(5126); 
	AddSkill(	SKILL_GUN_BOW_DRAIN, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("GUN_BOW_DRAIN"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_BOW_DRAIN, BITMAPINDEX(17), 5139, WEAPONSKILLTYPE_GUN );

	pText = GetTxtFromMgr(5135); 
	AddSkill(	SKILL_GUN_STAFF_INCMAG, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1,	TEXT("GUN_STAFF_INCMAG"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_STAFF_INCMAG, BITMAPINDEX(20), 5148, WEAPONSKILLTYPE_GUN );

	pText = GetTxtFromMgr(5131); 
	AddSkill(	SKILL_GUN_SWORD_INCVIT, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2,	TEXT("GUN_SWORD_INCVIT"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_SWORD_INCVIT, BITMAPINDEX(15), 5144, WEAPONSKILLTYPE_GUN );

	pText = GetTxtFromMgr(5136); 
	AddSkill(	SKILL_GUN_SPEAR_DOUBLEAT, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("GUN_SPEAR_DOUBLEAT"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_SPEAR_DOUBLEAT, BITMAPINDEX(16), 5149, WEAPONSKILLTYPE_GUN );

	pText = GetTxtFromMgr(5199); 
	AddSkill(	SKILL_GUN_AXE_INDURE, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("GUN_AXE_INDURE"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_AXE_INDURE, BITMAPINDEX(18), 5203, WEAPONSKILLTYPE_GUN );

	pText = GetTxtFromMgr(5130); 
	AddSkill(	SKILL_GUN_BOW_INCRANGE, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2,	TEXT("GUN_BOW_INCRANGE"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_BOW_INCRANGE, BITMAPINDEX(17), 5143, WEAPONSKILLTYPE_GUN );

	pText = GetTxtFromMgr(5201); 
	AddSkill(	SKILL_GUN_STAFF_DECUSEMANA, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("GUN_STAFF_DECUSEMANA"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_STAFF_DECUSEMANA, BITMAPINDEX(20), 5205, WEAPONSKILLTYPE_GUN );

	pText = GetTxtFromMgr(5132); 
	AddSkill(	SKILL_STAFF_SWORD_INCDR, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("STAFF_SWORD_INCDR"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_SWORD_INCDR, BITMAPINDEX(15), 5145, WEAPONSKILLTYPE_STAFF );

	pText = GetTxtFromMgr(5133); 
	AddSkill(	SKILL_STAFF_SPEAR_INCAC, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("STAFF_SPEAR_INCAC"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_SPEAR_INCAC, BITMAPINDEX(16), 5146, WEAPONSKILLTYPE_STAFF );

	pText = GetTxtFromMgr(5134); 
	AddSkill(	SKILL_STAFF_AXE_DECGAP, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("STAFF_AXE_DECGAP"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_AXE_DECGAP, BITMAPINDEX(18), 5147, WEAPONSKILLTYPE_STAFF );

	pText = GetTxtFromMgr(5126); 
	AddSkill(	SKILL_STAFF_BOW_DRAIN, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("STAFF_BOW_DRAIN"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_BOW_DRAIN, BITMAPINDEX(17), 5139, WEAPONSKILLTYPE_STAFF );

	pText = GetTxtFromMgr(5200); 
	AddSkill(	SKILL_STAFF_GUN_INCPHYAR, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE1, TEXT("STAFF_GUN_INCPHYAR"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_GUN_INCPHYAR, BITMAPINDEX(19), 5204, WEAPONSKILLTYPE_STAFF );

	pText = GetTxtFromMgr(5131); 
	AddSkill(	SKILL_STAFF_SWORD_INCVIT, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("STAFF_SWORD_INCVIT"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_SWORD_INCVIT, BITMAPINDEX(15), 5144, WEAPONSKILLTYPE_STAFF );

	pText = GetTxtFromMgr(5136); 
	AddSkill(	SKILL_STAFF_SPEAR_DOUBLEAT, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("STAFF_SPEAR_DOUBLEAT"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_SPEAR_DOUBLEAT, BITMAPINDEX(16), 5149, WEAPONSKILLTYPE_STAFF );

	pText = GetTxtFromMgr(5199); 
	AddSkill(	SKILL_STAFF_AXE_INDURE, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2,	TEXT("STAFF_AXE_INDURE"), pText, 
				MAX_WEAPONSKILL_LEVEL, SKILL_AXE_INDURE, BITMAPINDEX(18), 5203, WEAPONSKILLTYPE_STAFF );

	pText = GetTxtFromMgr(5130); 
	AddSkill(	SKILL_STAFF_BOW_INCRANGE, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("STAFF_BOW_INCRANGE"), pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_BOW_INCRANGE, BITMAPINDEX(17), 5143, WEAPONSKILLTYPE_STAFF );

	pText = GetTxtFromMgr(5137); 
	AddSkill(	SKILL_STAFF_GUN_DECMAGDELAY, SKILLTYPE_FIGHT, SKILLATB_HIDDENGRADE2, TEXT("STAFF_GUN_DECMAGDELAY"),	pText,
				MAX_WEAPONSKILL_LEVEL, SKILL_GUN_DECMAGDELAY, BITMAPINDEX(19), 5150, WEAPONSKILLTYPE_STAFF );


	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//
//
//
//
//
//	TCHAR* pText = GetTxtFromMgr(2851);
//	AddSkill(SKILL_MAKEMED,				SKILLTYPE_HARVEST,		SKILLATB_LIST,		TEXT("MAKEMED"),			pText,
//			30,							0,						BITMAPINDEX(0),		85);
//	
//	pText = GetTxtFromMgr(2842);
//	AddSkill(SKILL_MAKEFOOD,			SKILLTYPE_HARVEST,		SKILLATB_LIST,		TEXT("MAKEFOOD"),			pText,
//			30,							0,						BITMAPINDEX(1),		86);
//	
//	pText = GetTxtFromMgr(2852);
//	AddSkill(SKILL_MAKEARMOUR1,			SKILLTYPE_WEAR,			SKILLATB_LIST,		TEXT("MAKEARMOUR1"),		pText,
//			30,							0,						BITMAPINDEX(2),		87);
//
//	pText = GetTxtFromMgr(2853);
//	AddSkill(SKILL_MAKEHELMET1,			SKILLTYPE_WEAR,			SKILLATB_LIST,		TEXT("MAKEHELMET1"),		pText,
//			30,							0,						BITMAPINDEX(3),		88);	
//
//	pText = GetTxtFromMgr(2854);
//	AddSkill(SKILL_MAKESWORD1,			SKILLTYPE_MAKEWEAPON,	SKILLATB_LIST,		TEXT("MAKESWORD1"),			pText,
//			30,							0,						BITMAPINDEX(4),		89);
//
//	pText = GetTxtFromMgr(2855);
//	AddSkill(SKILL_MAKESPEAR1,			SKILLTYPE_MAKEWEAPON,	SKILLATB_LIST,		TEXT("MAKESPEAR1"),			pText,
//			30,							0,						BITMAPINDEX(5),		90);
//
//	pText = GetTxtFromMgr(2856);
//	AddSkill(SKILL_MAKEAXE1,			SKILLTYPE_MAKEWEAPON,	SKILLATB_LIST,		TEXT("MAKEAXE1"),			pText,
//			30,							0,						BITMAPINDEX(6),		91);
//
//	pText = GetTxtFromMgr(2857);
//	AddSkill(SKILL_MAKESTAFF1,			SKILLTYPE_MAKEWEAPON,	SKILLATB_LIST,		TEXT("MAKESTAFF1"),			pText,
//			30,							0,						BITMAPINDEX(7),		92);
//
//	pText = GetTxtFromMgr(2858);
//	AddSkill(SKILL_MAKEBOW1,			SKILLTYPE_MAKEWEAPON,	SKILLATB_LIST,		TEXT("MAKEBOW1"),			pText,
//			30,							0,						BITMAPINDEX(8),		93);
//
//	pText = GetTxtFromMgr(2859);
//	AddSkill(SKILL_MAKEGUN1,			SKILLTYPE_MAKEWEAPON,	SKILLATB_LIST,		TEXT("MAKEGUN1"),			pText,
//			30,							0,						BITMAPINDEX(9),		94);
//
//	/*cyj 대포제작술 삭제
//	pText = GetTxtFromMgr(2860);
//	AddSkill(SKILL_MAKECANNON,		SKILLTYPE_MAKEWEAPON,			SKILLATB_LIST,	TEXT("MAKECANNON"),		
//		pText,	30, 0,		BITMAPINDEX(28), 116);
//	*/
//	
//	pText = GetTxtFromMgr(2861);
//	AddSkill(SKILL_MAKESHOES1,			SKILLTYPE_ACCESSARY,	SKILLATB_LIST,		TEXT("MAKESHOES"),			pText,
//			30,							0,						BITMAPINDEX(10),	95);
//	
//	pText = GetTxtFromMgr(2862);
//	AddSkill(SKILL_MAKEBELT1,			SKILLTYPE_ACCESSARY,	SKILLATB_LIST,		TEXT("MAKEBELT1"),			pText,
//			30,							0,						BITMAPINDEX(11),	96);
//
//
//	/*cyj 반지제작술 삭제
//	pText = GetTxtFromMgr(2863);
//	AddSkill(SKILL_MAKERING1,		SKILLTYPE_ACCESSARY,			SKILLATB_LIST,	TEXT("MAKERING1"),		
//		pText,	30, 0,		BITMAPINDEX(12), 97);
//	*/
//
//	//pText = GetTxtFromMgr(2864);
//	//AddSkill(SKILL_MAKENECK1,		SKILLTYPE_ACCESSARY,			SKILLATB_LIST,	TEXT("MAKENECK1"),		
//	//	pText,	30, 0,		BITMAPINDEX(24), 109);
//	
//	pText = GetTxtFromMgr(2865);
//	AddSkill(SKILL_USESWORD1,			SKILLTYPE_USEWEAPON,	0,					TEXT("USESWORD1"),			pText,
//			30,							0,						BITMAPINDEX(15),	100,						WEAPONSKILLTYPE_SWORD);
//
//	pText = GetTxtFromMgr(2866);
//	AddSkill(SKILL_USESPEAR1,			SKILLTYPE_USEWEAPON,	0,					TEXT("USESPEAR1"),			pText,
//			30,							0,						BITMAPINDEX(16),	101,						WEAPONSKILLTYPE_SPEAR);
//
//	pText = GetTxtFromMgr(2867);
//	AddSkill(SKILL_USEAXE1,				SKILLTYPE_USEWEAPON,	0,					TEXT("USEAXE1"),			pText,
//			30,							0,						BITMAPINDEX(18),	103,						WEAPONSKILLTYPE_AXE);
//
//	pText = GetTxtFromMgr(2868);
//	AddSkill(SKILL_USESTAFF1,			SKILLTYPE_USEWEAPON,	0,					TEXT("USESTAFF1"),			pText,
//			30,							0,						BITMAPINDEX(20),	105,						WEAPONSKILLTYPE_STAFF);
//
//	pText = GetTxtFromMgr(2869);
//	AddSkill(SKILL_USEBOW1,				SKILLTYPE_USEWEAPON,	0,					TEXT("USEBOW1"),			pText,
//			30,							0,						BITMAPINDEX(17),	102,						WEAPONSKILLTYPE_BOW);
//
//	pText = GetTxtFromMgr(2870);
//	AddSkill(SKILL_USEGUN1,				SKILLTYPE_USEWEAPON,	0,					TEXT("USEGUN1"),			pText,
//			30,							0,						BITMAPINDEX(19),	104,						WEAPONSKILLTYPE_GUN);
//	
//	pText = GetTxtFromMgr(2871);
//	AddSkill(SKILL_MAKEIRON1,			SKILLTYPE_MAKETOOL,		SKILLATB_LIST,		TEXT("MAKEIRON1"),			pText,	 
//			30,							0,						BITMAPINDEX(26),	111);
//
//	/*cyj 도기/ 문방구/ 어구 제작술 통합
//	pText = GetTxtFromMgr(2872);
//	AddSkill(SKILL_MAKEDISH1,		SKILLTYPE_MAKETOOL,				SKILLATB_LIST,	TEXT("MAKEDISH1"),		
//		pText,	 20, 0,		BITMAPINDEX(27), 112);
//
//	pText = GetTxtFromMgr(2882);
//	AddSkill(SKILL_MAKEFISHINGROD,	SKILLTYPE_SEA,					SKILLATB_LIST,	TEXT("MAKEFISHINGROD"),	
//		pText,	20, 0,		BITMAPINDEX(23), 108);
//	*/
//	pText = GetTxtFromMgr(5774);
//	AddSkill(SKILL_MAKETOOL1,			SKILLTYPE_MAKETOOL,		SKILLATB_LIST,		TEXT("MAKETOOL1"),			pText,
//			30,							0,						BITMAPINDEX(27),	121);
//
//
//	/*
//	pText = GetTxtFromMgr(2873);
//	AddSkill(SKILL_MAKEDRESS1,		SKILLTYPE_WEAR,					SKILLATB_LIST,	TEXT("MAKEDRESS1"),		
//		pText,	30, 0,		BITMAPINDEX(13), 98);
//	*/
///*
//	pText = GetTxtFromMgr(2874);
//	AddSkill(SKILL_MAKEHAT1,		SKILLTYPE_WEAR,					SKILLATB_LIST,	TEXT("MAKEHAT1"),			
//		pText,	30, 0,		BITMAPINDEX(31), 115);
//*/
//	//pText = GetTxtFromMgr(2875);
//	//AddSkill(SKILL_MAKESCROLL,		SKILLTYPE_ETC,					SKILLATB_LIST,	TEXT("MAKESCROLL"),		
//	//	pText,	30, 0,		BITMAPINDEX(29), 113);		
//
//	pText = GetTxtFromMgr(2876);
//	AddSkill(SKILL_HORSETRAINING,		SKILLTYPE_ETC,			SKILLATB_LIST,		TEXT("HORSETRAINING1"),		pText,
//			30,							0,						BITMAPINDEX(25),	110);
//
//	pText = GetTxtFromMgr(2877);
//	AddSkill(SKILL_CAPTURE,				SKILLTYPE_ETC,			SKILLATB_LIST,		TEXT("CAPTURE"),			pText,
//			30,							0,						BITMAPINDEX(30),	114);
//
//	pText = GetTxtFromMgr(2878);
//	AddSkill(SKILL_SUMMON,				SKILLTYPE_ETC,			SKILLATB_LIST,		TEXT("SUMMON"),				pText,
//			30,							0,						BITMAPINDEX(21),	117);
//
//	//if( pclClient->IsWhereServiceArea( ConstSwitch_Artifact ) )
//	if( pclClient->IsCountrySwitch( Switch_Artifact ) ) // 아이템 타입 변경에 따른 스위치 변경예정.
//	{
//		// [추가 : 황진성 2008. 2. 25 => 아티팩트 술 (결정체 제조술) ]
//		pText = GetTxtFromMgr(8225);
//		AddSkill( SKILL_ARTIFACT,	SKILLTYPE_ETC,	SKILLATB_LIST,	TEXT( "ARTFACT" ),			
//				  pText,			30,				0,				BITMAPINDEX( 35 ), 8226 );
//	}
//	
//	//pText = GetTxtFromMgr(2879);
//	//AddSkill(SKILL_ALCHEMY,			SKILLTYPE_ETC,	`				SKILLATB_LIST,	TEXT("ALCHEMY"),			
//	//	pText,		30, 0,	BITMAPINDEX(32), 118);
//
//	pText = GetTxtFromMgr(2881);
//	AddSkill(SKILL_FISH,				SKILLTYPE_SEA,			SKILLATB_LIST,		TEXT("FISH"),				pText,	
//			20,							0,						BITMAPINDEX(22),	107);
//
//	pText = GetTxtFromMgr(2883);
//	AddSkill(SKILL_FARM,				SKILLTYPE_HARVEST,		SKILLATB_LIST,		TEXT("FARM"),				pText,
//			30,							0,						BITMAPINDEX(33),	119);
//	
//	pText = GetTxtFromMgr(2884);
//	AddSkill(SKILL_MINE,				SKILLTYPE_HARVEST,		SKILLATB_LIST,		TEXT("MINE"),				pText,	
//			30,							0,						BITMAPINDEX(33),	120);
//
//	// 전투향상술
//	pText = GetTxtFromMgr(5132);
//	AddSkill(SKILL_SWORD_INCDR,			SKILLTYPE_FIGHT,		0,					TEXT("SWORD_INCDR"),		pText,	
//			MAX_WEAPONSKILL_LEVEL,		0,						BITMAPINDEX(15),	5145,						WEAPONSKILLTYPE_SWORD);
//
//	pText = GetTxtFromMgr(5131);
//	AddSkill(SKILL_SWORD_INCVIT,		SKILLTYPE_FIGHT,		0,					TEXT("SWORD_INCVIT"),		pText,	
//			MAX_WEAPONSKILL_LEVEL,		SKILL_SWORD_INCDR,		BITMAPINDEX(15),	5144,						WEAPONSKILLTYPE_SWORD);
//
//	/*pText = GetTxtFromMgr(5128);
//	AddSkill(SKILL_SWORD_INCMAGAT,		SKILLTYPE_FIGHT,		0,					TEXT("SWORD_INCMAGAT"),		pText,
//			MAX_WEAPONSKILL_LEVEL,		SKILL_SWORD_INCVIT,		BITMAPINDEX(15),	5141,						WEAPONSKILLTYPE_SWORD);*/
//
//	pText = GetTxtFromMgr(5133);
//	AddSkill(SKILL_SPEAR_INCAC,			SKILLTYPE_FIGHT,		0,					TEXT("SPEAR_INCAC"),		pText,
//			MAX_WEAPONSKILL_LEVEL,		0,						BITMAPINDEX(16),	5146,						WEAPONSKILLTYPE_SPEAR);
//
//	pText = GetTxtFromMgr(5136);
//	AddSkill(SKILL_SPEAR_DOUBLEAT,		SKILLTYPE_FIGHT,		0,					TEXT("SPEAR_DOUBLEAT"),		pText,
//			MAX_WEAPONSKILL_LEVEL,		SKILL_SPEAR_INCAC,		BITMAPINDEX(16),	5149,						WEAPONSKILLTYPE_SPEAR);
//
//	/*pText = GetTxtFromMgr(5128);
//	AddSkill(SKILL_SPEAR_INCMAGAT,		SKILLTYPE_FIGHT,		0,					TEXT("SPEAR_INCMAGAT"),		pText,
//			MAX_WEAPONSKILL_LEVEL,		SKILL_SPEAR_DOUBLEAT,	BITMAPINDEX(16),	5141,						WEAPONSKILLTYPE_SPEAR);*/
//
//	pText = GetTxtFromMgr(5134);
//	AddSkill(SKILL_AXE_DECGAP,			SKILLTYPE_FIGHT,		0,					TEXT("AXE_DECGAP"),		pText,
//			MAX_WEAPONSKILL_LEVEL,		0,						BITMAPINDEX(18),	5147,						WEAPONSKILLTYPE_AXE);
//
//	pText = GetTxtFromMgr(5199);
//	AddSkill(SKILL_AXE_INDURE,			SKILLTYPE_FIGHT,		0,					TEXT("AXE_INDURE"),			pText,
//			MAX_WEAPONSKILL_LEVEL,		SKILL_AXE_DECGAP,		BITMAPINDEX(18),	5203,						WEAPONSKILLTYPE_AXE);
//
//	/*pText = GetTxtFromMgr(5129);
//	AddSkill(SKILL_AXE_INCCRI,			SKILLTYPE_FIGHT,		0,					TEXT("AXE_INCCRI"),			pText,
//			MAX_WEAPONSKILL_LEVEL,		SKILL_AXE_INDURE,		BITMAPINDEX(18),	5142,						WEAPONSKILLTYPE_AXE);*/
//
//	pText = GetTxtFromMgr(5126);
//	AddSkill(SKILL_BOW_DRAIN,			SKILLTYPE_FIGHT,		0,					TEXT("BOW_DRAIN"),			pText,
//			MAX_WEAPONSKILL_LEVEL,		0,						BITMAPINDEX(17),	5139,						WEAPONSKILLTYPE_BOW);
//
//	pText = GetTxtFromMgr(5130);
//	AddSkill(SKILL_BOW_INCRANGE,		SKILLTYPE_FIGHT,		0,					TEXT("BOW_INCRANGE"),		pText,
//			MAX_WEAPONSKILL_LEVEL,		SKILL_BOW_DRAIN,		BITMAPINDEX(17),	5143,						WEAPONSKILLTYPE_BOW);
//
//	/*pText = GetTxtFromMgr(5128);
//	AddSkill(SKILL_BOW_INCMAGAT,		SKILLTYPE_FIGHT,		0,					TEXT("BOW_INCMAGAT"),		pText,
//			MAX_WEAPONSKILL_LEVEL,		SKILL_BOW_INCRANGE,		BITMAPINDEX(17),	5141,						WEAPONSKILLTYPE_BOW);*/
//
//	pText = GetTxtFromMgr(5200);
//	AddSkill(SKILL_GUN_INCPHYAR,		SKILLTYPE_FIGHT,		0,					TEXT("GUN_INCPHYAR"),		pText,
//			MAX_WEAPONSKILL_LEVEL,		0,						BITMAPINDEX(19),	5204,						WEAPONSKILLTYPE_GUN);
//
//	pText = GetTxtFromMgr(5137);
//	AddSkill(SKILL_GUN_DECMAGDELAY,		SKILLTYPE_FIGHT,		0,					TEXT("GUN_DECMAGDELAY"),	pText,
//			MAX_WEAPONSKILL_LEVEL,		SKILL_GUN_INCPHYAR,		BITMAPINDEX(19),	5150,						WEAPONSKILLTYPE_GUN);
//
//	/*pText = GetTxtFromMgr(5127);
//	AddSkill(SKILL_GUN_INCWEAAT,		SKILLTYPE_FIGHT,		0,					TEXT("GUN_INCWEAAT"),		pText,
//			MAX_WEAPONSKILL_LEVEL,		SKILL_GUN_DECMAGDELAY,	BITMAPINDEX(19),	5140,						WEAPONSKILLTYPE_GUN);*/
//
//	pText = GetTxtFromMgr(5135);
//	AddSkill(SKILL_STAFF_INCMAG,		SKILLTYPE_FIGHT,		0,					TEXT("STAFF_INCMAG"),		pText,
//			MAX_WEAPONSKILL_LEVEL,		0,						BITMAPINDEX(20),	5148,						WEAPONSKILLTYPE_STAFF);
//
//	pText = GetTxtFromMgr(5201);
//	AddSkill(SKILL_STAFF_DECUSEMANA,	SKILLTYPE_FIGHT,		0,					TEXT("STAFF_DECUSEMANA"),	pText,
//			MAX_WEAPONSKILL_LEVEL,		SKILL_STAFF_INCMAG,		BITMAPINDEX(20),	5205,						WEAPONSKILLTYPE_STAFF);
//
//	/*pText = GetTxtFromMgr(5128);
//	AddSkill(SKILL_STAFF_INCMAGAT,		SKILLTYPE_FIGHT,		0,					TEXT("STAFF_INCMAGAT"),		pText,
//			MAX_WEAPONSKILL_LEVEL,		SKILL_STAFF_DECUSEMANA,	BITMAPINDEX(20),	5141,						WEAPONSKILLTYPE_STAFF);*/
//
//	// 히든 전투향상술
//	pText = GetTxtFromMgr(5133); 
//	AddSkill(SKILL_SWORD_SPEAR_INCAC,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("SWORD_SPEAR_INCAC"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SPEAR_INCAC,		BITMAPINDEX(16),		5146,							WEAPONSKILLTYPE_SWORD );
//
//	pText = GetTxtFromMgr(5134); 
//	AddSkill(SKILL_SWORD_AXE_DECGAP,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("SWORD_AXE_DECGAP"),	pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_AXE_DECGAP,		BITMAPINDEX(18),		5147,							WEAPONSKILLTYPE_SWORD );
//
//	pText = GetTxtFromMgr(5126); 
//	AddSkill(SKILL_SWORD_BOW_DRAIN,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("SWORD_BOW_DRAIN"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_BOW_DRAIN,		BITMAPINDEX(17),		5139,							WEAPONSKILLTYPE_SWORD );
//
//	pText = GetTxtFromMgr(5200); 
//	AddSkill(SKILL_SWORD_GUN_INCPHYAR,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("SWORD_GUN_INCPHYAR"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_GUN_INCPHYAR,		BITMAPINDEX(19),		5204,							WEAPONSKILLTYPE_SWORD );
//
//	pText = GetTxtFromMgr(5135); 
//	AddSkill(SKILL_SWORD_STAFF_INCMAG,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("SWORD_STAFF_INCMAG"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_STAFF_INCMAG,		BITMAPINDEX(20),		5148,							WEAPONSKILLTYPE_SWORD );
//
//	pText = GetTxtFromMgr(5136); 
//	AddSkill(SKILL_SWORD_SPEAR_DOUBLEAT,	SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("SWORD_SPEAR_DOUBLEAT"),	pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SPEAR_DOUBLEAT,	BITMAPINDEX(16),		5149,							WEAPONSKILLTYPE_SWORD );
//
//	pText = GetTxtFromMgr(5199); 
//	AddSkill(SKILL_SWORD_AXE_INDURE,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("SWORD_AXE_INDURE"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_AXE_INDURE,		BITMAPINDEX(18),		5203,							WEAPONSKILLTYPE_SWORD );
//
//	pText = GetTxtFromMgr(5130); 
//	AddSkill(SKILL_SWORD_BOW_INCRANGE,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("SWORD_BOW_INCRANGE"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_BOW_INCRANGE,		BITMAPINDEX(17),		5143,							WEAPONSKILLTYPE_SWORD );
//
//	pText = GetTxtFromMgr(5137); 
//	AddSkill(SKILL_SWORD_GUN_DECMAGDELAY,	SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("SWORD_GUN_DECMAGDELAY"),	pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_GUN_DECMAGDELAY,	BITMAPINDEX(19),		5150,							WEAPONSKILLTYPE_SWORD );
//
//	pText = GetTxtFromMgr(5201); 
//	AddSkill(SKILL_SWORD_STAFF_DECUSEMANA,	SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("SWORD_STAFF_DECUSEMANA"),	pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_STAFF_DECUSEMANA,	BITMAPINDEX(20),		5205,							WEAPONSKILLTYPE_SWORD );
//
//	pText = GetTxtFromMgr(5132); 
//	AddSkill(SKILL_SPEAR_SWORD_INCDR,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("SPEAR_SWORD_INCDR"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SWORD_INCDR,		BITMAPINDEX(15),		5145,							WEAPONSKILLTYPE_SPEAR );
//    
//	pText = GetTxtFromMgr(5134); 
//	AddSkill(SKILL_SPEAR_AXE_DECGAP,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("SPEAR_AXE_DECGAP"),	pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_AXE_DECGAP,		BITMAPINDEX(18),		5147,							WEAPONSKILLTYPE_SPEAR );
//
//	pText = GetTxtFromMgr(5126); 
//	AddSkill(SKILL_SPEAR_BOW_DRAIN,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("SPEAR_BOW_DRAIN"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_BOW_DRAIN,		BITMAPINDEX(17),		5139,							WEAPONSKILLTYPE_SPEAR );
//
//	pText = GetTxtFromMgr(5200); 
//	AddSkill(SKILL_SPEAR_GUN_INCPHYAR,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("SPEAR_GUN_INCPHYAR"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_GUN_INCPHYAR,		BITMAPINDEX(19),		5204,							WEAPONSKILLTYPE_SPEAR );
//
//	pText = GetTxtFromMgr(5135); 
//	AddSkill(SKILL_SPEAR_STAFF_INCMAG,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("SPEAR_STAFF_INCMAG"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_STAFF_INCMAG,		BITMAPINDEX(20),		5148,							WEAPONSKILLTYPE_SPEAR );
//
//	pText = GetTxtFromMgr(5131); 
//	AddSkill(SKILL_SPEAR_SWORD_INCVIT,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("SPEAR_SWORD_INCVIT"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SWORD_INCVIT,		BITMAPINDEX(15),		5144,							WEAPONSKILLTYPE_SPEAR );
//
//	pText = GetTxtFromMgr(5199); 
//	AddSkill(SKILL_SPEAR_AXE_INDURE,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("SPEAR_AXE_INDURE"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_AXE_INDURE,		BITMAPINDEX(18),		5203,							WEAPONSKILLTYPE_SPEAR );
//
//	pText = GetTxtFromMgr(5130); 
//	AddSkill(SKILL_SPEAR_BOW_INCRANGE,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("SPEAR_BOW_INCRANGE"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_BOW_INCRANGE,		BITMAPINDEX(17),		5143,							WEAPONSKILLTYPE_SPEAR );
//
//	pText = GetTxtFromMgr(5137); 
//	AddSkill(SKILL_SPEAR_GUN_DECMAGDELAY,	SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("SPEAR_GUN_DECMAGDELAY"),	pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_GUN_DECMAGDELAY,	BITMAPINDEX(19),		5150,							WEAPONSKILLTYPE_SPEAR );
//
//	pText = GetTxtFromMgr(5201); 
//	AddSkill(SKILL_SPEAR_STAFF_DECUSEMANA,	SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("SPEAR_STAFF_DECUSEMANA"),	pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_STAFF_DECUSEMANA,	BITMAPINDEX(20),		5205,							WEAPONSKILLTYPE_SPEAR );
//
//	pText = GetTxtFromMgr(5132); 
//	AddSkill(SKILL_AXE_SWORD_INCDR,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("AXE_SWORD_INCDR"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SWORD_INCDR,		BITMAPINDEX(15),		5145,							WEAPONSKILLTYPE_AXE );
//
//	pText = GetTxtFromMgr(5133); 
//	AddSkill(SKILL_AXE_SPEAR_INCAC,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("AXE_SPEAR_INCAC"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SPEAR_INCAC,		BITMAPINDEX(16),		5146,							WEAPONSKILLTYPE_AXE );
//
//	pText = GetTxtFromMgr(5126); 
//	AddSkill(SKILL_AXE_BOW_DRAIN,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("AXE_BOW_DRAIN"),			pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_BOW_DRAIN,		BITMAPINDEX(17),		5139,							WEAPONSKILLTYPE_AXE );
//
//	pText = GetTxtFromMgr(5200);
//	AddSkill(SKILL_AXE_GUN_INCPHYAR,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("AXE_GUN_INCPHYAR"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_GUN_INCPHYAR,		BITMAPINDEX(19),		5204,							WEAPONSKILLTYPE_AXE );
//    
//	pText = GetTxtFromMgr(5135); 
//	AddSkill(SKILL_AXE_STAFF_INCMAG,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("AXE_STAFF_INCMAG"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_STAFF_INCMAG,		BITMAPINDEX(20),		5148,							WEAPONSKILLTYPE_AXE );
//
//	pText = GetTxtFromMgr(5131); 
//	AddSkill(SKILL_AXE_SWORD_INCVIT,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("AXE_SWORD_INCVIT"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SWORD_INCVIT,		BITMAPINDEX(15),		5144,							WEAPONSKILLTYPE_AXE );
//
//	pText = GetTxtFromMgr(5136); 
//	AddSkill(SKILL_AXE_SPEAR_DOUBLEAT,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("AXE_SPEAR_DOUBLEAT"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SPEAR_DOUBLEAT,	BITMAPINDEX(16),		5149,							WEAPONSKILLTYPE_AXE );
//
//	pText = GetTxtFromMgr(5130); 
//	AddSkill(SKILL_AXE_BOW_INCRANGE,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("AXE_BOW_INCRANGE"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_BOW_INCRANGE,		BITMAPINDEX(17),		5143,							WEAPONSKILLTYPE_AXE );
//
//	pText = GetTxtFromMgr(5137); 
//	AddSkill(SKILL_AXE_GUN_DECMAGDELAY,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("AXE_GUN_DECMAGDELAY"),	pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_GUN_DECMAGDELAY,	BITMAPINDEX(19),		5150,							WEAPONSKILLTYPE_AXE );
//
//	pText = GetTxtFromMgr(5201); 
//	AddSkill(SKILL_AXE_STAFF_DECUSEMANA,	SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("AXE_STAFF_DECUSEMANA"),	pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_STAFF_DECUSEMANA,	BITMAPINDEX(20),		5205,							WEAPONSKILLTYPE_AXE );
//
//	pText = GetTxtFromMgr(5132); 
//	AddSkill(SKILL_BOW_SWORD_INCDR,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("BOW_SWORD_INCDR"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SWORD_INCDR,		BITMAPINDEX(15),		5145,							WEAPONSKILLTYPE_BOW );
//
//	pText = GetTxtFromMgr(5133); 
//	AddSkill(SKILL_BOW_SPEAR_INCAC,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("BOW_SPEAR_INCAC"),		pText,	
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SPEAR_INCAC,		BITMAPINDEX(16),		5146,							WEAPONSKILLTYPE_BOW );
//
//	pText = GetTxtFromMgr(5134); 
//	AddSkill(SKILL_BOW_AXE_DECGAP,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("BOW_AXE_DECGAP"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_AXE_DECGAP,		BITMAPINDEX(18),		5147,							WEAPONSKILLTYPE_BOW );
//
//	pText = GetTxtFromMgr(5200); 
//	AddSkill(SKILL_BOW_GUN_INCPHYAR,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("BOW_GUN_INCPHYAR"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_GUN_INCPHYAR,		BITMAPINDEX(19),		5204,							WEAPONSKILLTYPE_BOW );
//
//	pText = GetTxtFromMgr(5135); 
//	AddSkill(SKILL_BOW_STAFF_INCMAG,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("BOW_STAFF_INCMAG"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_STAFF_INCMAG,		BITMAPINDEX(20),		5148,							WEAPONSKILLTYPE_BOW );
//
//	pText = GetTxtFromMgr(5131); 
//	AddSkill(SKILL_BOW_SWORD_INCVIT,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("BOW_SWORD_INCVIT"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SWORD_INCVIT,		BITMAPINDEX(15),		5144,							WEAPONSKILLTYPE_BOW );
//
//	pText = GetTxtFromMgr(5136); 
//	AddSkill(SKILL_BOW_SPEAR_DOUBLEAT,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("BOW_SPEAR_DOUBLEAT"),		pText,	
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SPEAR_DOUBLEAT,	BITMAPINDEX(16),		5149,							WEAPONSKILLTYPE_BOW );
//
//	pText = GetTxtFromMgr(5199); 
//	AddSkill(SKILL_BOW_AXE_INDURE,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("BOW_AXE_INDURE"),			pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_AXE_INDURE,		BITMAPINDEX(18),		5203,							WEAPONSKILLTYPE_BOW );
//
//	pText = GetTxtFromMgr(5137); 
//	AddSkill(SKILL_BOW_GUN_DECMAGDELAY,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("BOW_GUN_DECMAGDELAY"),	pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_GUN_DECMAGDELAY,	BITMAPINDEX(19),		5150,							WEAPONSKILLTYPE_BOW );
//
//	pText = GetTxtFromMgr(5201); 
//	AddSkill(SKILL_BOW_STAFF_DECUSEMANA,	SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("BOW_STAFF_DECUSEMANA"),	pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_STAFF_DECUSEMANA,	BITMAPINDEX(20),		5205,							WEAPONSKILLTYPE_BOW );
//
//	pText = GetTxtFromMgr(5132); 
//	AddSkill(SKILL_GUN_SWORD_INCDR,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("GUN_SWORD_INCDR"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SWORD_INCDR,		BITMAPINDEX(15),		5145,							WEAPONSKILLTYPE_GUN );
//
//	pText = GetTxtFromMgr(5133); 
//	AddSkill(SKILL_GUN_SPEAR_INCAC,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("GUN_SPEAR_INCAC"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SPEAR_INCAC,		BITMAPINDEX(16),		5146,							WEAPONSKILLTYPE_GUN );
//
//	pText = GetTxtFromMgr(5134); 
//	AddSkill(SKILL_GUN_AXE_DECGAP,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("GUN_AXE_DECGAP"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_AXE_DECGAP,		BITMAPINDEX(18),		5147,							WEAPONSKILLTYPE_GUN );
//
//	pText = GetTxtFromMgr(5126); 
//	AddSkill(SKILL_GUN_BOW_DRAIN,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("GUN_BOW_DRAIN"),			pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_BOW_DRAIN,		BITMAPINDEX(17),		5139,							WEAPONSKILLTYPE_GUN );
//
//	pText = GetTxtFromMgr(5135); 
//	AddSkill(SKILL_GUN_STAFF_INCMAG,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("GUN_STAFF_INCMAG"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_STAFF_INCMAG,		BITMAPINDEX(20),		5148,							WEAPONSKILLTYPE_GUN );
//
//	pText = GetTxtFromMgr(5131); 
//	AddSkill(SKILL_GUN_SWORD_INCVIT,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("GUN_SWORD_INCVIT"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SWORD_INCVIT,		BITMAPINDEX(15),		5144,							WEAPONSKILLTYPE_GUN );
//
//	pText = GetTxtFromMgr(5136); 
//	AddSkill(SKILL_GUN_SPEAR_DOUBLEAT,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("GUN_SPEAR_DOUBLEAT"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SPEAR_DOUBLEAT,	BITMAPINDEX(16),		5149,							WEAPONSKILLTYPE_GUN );
//
//	pText = GetTxtFromMgr(5199); 
//	AddSkill(SKILL_GUN_AXE_INDURE,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("GUN_AXE_INDURE"),			pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_AXE_INDURE,		BITMAPINDEX(18),		5203,							WEAPONSKILLTYPE_GUN );
//
//	pText = GetTxtFromMgr(5130); 
//	AddSkill(SKILL_GUN_BOW_INCRANGE,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("GUN_BOW_INCRANGE"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_BOW_INCRANGE,		BITMAPINDEX(17),		5143,							WEAPONSKILLTYPE_GUN );
//
//	pText = GetTxtFromMgr(5201); 
//	AddSkill(SKILL_GUN_STAFF_DECUSEMANA,	SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("GUN_STAFF_DECUSEMANA"),	pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_STAFF_DECUSEMANA,	BITMAPINDEX(20),		5205,							WEAPONSKILLTYPE_GUN );
//
//	pText = GetTxtFromMgr(5132); 
//	AddSkill(SKILL_STAFF_SWORD_INCDR,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("STAFF_SWORD_INCDR"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SWORD_INCDR,		BITMAPINDEX(15),		5145,							WEAPONSKILLTYPE_STAFF );
//
//	pText = GetTxtFromMgr(5133); 
//	AddSkill(SKILL_STAFF_SPEAR_INCAC,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("STAFF_SPEAR_INCAC"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SPEAR_INCAC,		BITMAPINDEX(16),		5146,							WEAPONSKILLTYPE_STAFF );
//
//	pText = GetTxtFromMgr(5134); 
//	AddSkill(SKILL_STAFF_AXE_DECGAP,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("STAFF_AXE_DECGAP"),	pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_AXE_DECGAP,		BITMAPINDEX(18),		5147,							WEAPONSKILLTYPE_STAFF );
//
//	pText = GetTxtFromMgr(5126); 
//	AddSkill(SKILL_STAFF_BOW_DRAIN,			SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("STAFF_BOW_DRAIN"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_BOW_DRAIN,		BITMAPINDEX(17),		5139,							WEAPONSKILLTYPE_STAFF );
//
//	pText = GetTxtFromMgr(5200); 
//	AddSkill(SKILL_STAFF_GUN_INCPHYAR,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE1,	TEXT("STAFF_GUN_INCPHYAR"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_GUN_INCPHYAR,		BITMAPINDEX(19),		5204,							WEAPONSKILLTYPE_STAFF );
//
//	pText = GetTxtFromMgr(5131); 
//	AddSkill(SKILL_STAFF_SWORD_INCVIT,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("STAFF_SWORD_INCVIT"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SWORD_INCVIT,		BITMAPINDEX(15),		5144,							WEAPONSKILLTYPE_STAFF );
//
//	pText = GetTxtFromMgr(5136); 
//	AddSkill(SKILL_STAFF_SPEAR_DOUBLEAT,	SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("STAFF_SPEAR_DOUBLEAT"),	pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_SPEAR_DOUBLEAT,	BITMAPINDEX(16),		5149,							WEAPONSKILLTYPE_STAFF );
//
//	pText = GetTxtFromMgr(5199); 
//	AddSkill(SKILL_STAFF_AXE_INDURE,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("STAFF_AXE_INDURE"),		pText, 
//			MAX_WEAPONSKILL_LEVEL,			SKILL_AXE_INDURE,		BITMAPINDEX(18),		5203,							WEAPONSKILLTYPE_STAFF );
//
//	pText = GetTxtFromMgr(5130); 
//	AddSkill(SKILL_STAFF_BOW_INCRANGE,		SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("STAFF_BOW_INCRANGE"),		pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_BOW_INCRANGE,		BITMAPINDEX(17),		5143,							WEAPONSKILLTYPE_STAFF );
//
//	pText = GetTxtFromMgr(5137); 
//	AddSkill(SKILL_STAFF_GUN_DECMAGDELAY,	SKILLTYPE_FIGHT,		SKILLATB_HIDDENGRADE2,	TEXT("STAFF_GUN_DECMAGDELAY"),	pText,
//			MAX_WEAPONSKILL_LEVEL,			SKILL_GUN_DECMAGDELAY,	BITMAPINDEX(19),		5150,							WEAPONSKILLTYPE_STAFF );
//
//	if ( TRUE == pclClient->IsCountrySwitch(Switch_Avatar_artisan) )
//	{
//	//[종호] 아바타 장인 스킬들
//	pText = GetTxtFromMgr(10317); 
//	AddSkill(SKILL_MAKEAVATAR_DRESS,	SKILLTYPE_MAKEAVATAR,	SKILLATB_LIST,		TEXT("MAKEAVATAR_DRESS"),	pText,
//		30,							0,						BITMAPINDEX(85),	10322);
//
//	pText = GetTxtFromMgr(10318); 
//	AddSkill(SKILL_MAKEAVATAR_HAT,		SKILLTYPE_MAKEAVATAR,	SKILLATB_LIST,		TEXT("MAKEAVATAR_HAT"),		pText,
//		30,							0,						BITMAPINDEX(85),	10323);
//
//	pText = GetTxtFromMgr(10319); 
//	AddSkill(SKILL_MAKEAVATAR_MANTLE,	SKILLTYPE_MAKEAVATAR,	SKILLATB_LIST,		TEXT("MAKEAVATAR_MANTLE"),	pText,
//		30,							0,						BITMAPINDEX(85),	10324);
//
//	pText = GetTxtFromMgr(10320); 
//	AddSkill(SKILL_MAKEAVATAR_RING,		SKILLTYPE_MAKEAVATAR,	SKILLATB_LIST,		TEXT("MAKEAVATAR_RING"),	pText,
//		30,							0,						BITMAPINDEX(85),	10325);
//
//	pText = GetTxtFromMgr(10321); 
//	AddSkill(SKILL_MAKEAVATAR_NECK,		SKILLTYPE_MAKEAVATAR,	SKILLATB_LIST,		TEXT("MAKEAVATAR_NECK"),	pText,
//		30,							0,						BITMAPINDEX(85),	10326);
//	}

}